### ISSUE TITLE
Maybe add javax.lang.model API

### ISSUE THREAD

**Issue by lukehutch** [classgraph/classgraph#143]
From @Alexander--, re, `javax.lang.model`:

> It is a bit exotic. More widely known in Android land (thanks to popularity of annotation processors there), not so much elsewhere. You probably don't want it as the only API, more like a supplement for situations, when loading classes to use reflection is unacceptable. Either way, learning how javac developers approached issue of compile-time introspection might be a good idea.

Look into supporting this as an alternative API?

**Comment by lukehutch** [comment]
`javax.lang.model` is used by the annotation processing API -- see:

https://youtu.be/2Dlo8OSwzaI?t=15m

Therefore, this issue is related to #184.

**Comment by johnou** [comment]
@lukehutch I think #184 is good enough to warrant closing this issue to keep things simple?

**Comment by lukehutch** [comment]
@johnou Well, that bug is about a very different issue (build-time scanning), and this one is about supporting an already-out-there API in the Java platform that is (very roughly) equivalent to the new ClassGraph v4 API. Actually the suggestion to support `javax.lang.model` is a very good one (at least as a secondary API). However, it's a bit of an obscure API and it may turn out to be a ton of work for not very much benefit.

Also, I took a look at the API, and it's mostly interfaces, but it's complex enough that I anticipate I'd get deep in the guts of implementing shims between `javax.lang.model` and the ClassGraph API, and then I'd find a huge "gotcha" that meant I couldn't cleanly map the APIs over. (I ran into similar issues when I was in the middle of implementing my own `ByteBuffer` that worked over the top of InputStream, for ClassGraph v4 -- I had almost the whole thing done, and it's a real pain of a class to implement, when I found that it's actually impossible to extend `ByteBuffer` because you have to define an abstract method that is package-private or something.)

So I have been mulling over whether to just close this. I think the new ClassGraph API is simple enough and complete enough that supporting a second parallel API doesn't make too much sense. If anyone finds this bug though and can point out a clear usecase where having ClassGraph plug into a `javax.lang.model` API consumer would be a huge win, please let me know, and I'll consider it.

Thanks, @johnou!
