### ISSUE TITLE
Feedback on Version 4 beta

### ISSUE THREAD

**Issue by lukehutch** [classgraph/classgraph#215]
@GedMarc @HybridHB @miho @ahamana @johnou @seanf @hepin1989 @davidmoshal @johnfg10 @anthonykeenan @danthegoodman @sbespalov @sergey-morenets @dantesun @PascalSchumacher @mrlambeth @Wafflemon @andrebrait:

You all reported bugs recently for FastClasspathScanner. I just pushed out the biggest update to date for this project, as version 4.0.0-beta-1, with a signifcantly revamped API. I would really appreciate it if you could please test out porting your existing code to this new API. Please let me know about any porting difficulties you run into, as well as any performance regressions.

Release notes and porting tips are here:

https://github.com/lukehutch/fast-classpath-scanner/releases/tag/fast-classpath-scanner-4.0.0-beta-1

The new API docs are here:

https://github.com/lukehutch/fast-classpath-scanner/wiki

Thanks!

**Comment by andrebrait** [comment]
Wow. Very nice. I liked the changes to the API a lot. I still have to see them in my own software, but so far I like them.

One minor concern, though:

```unBlacklistSystemPackages()``` feels like a double negative. Wouldn't something along the lines of ```whitelistSystemPackages()``` better for naming purposes even if what it actually does is more along the lines of removing the system packages from the default blacklist? (I don't even know if it does that, I'm just going for the worst case scenario here)

**Comment by lukehutch** [comment]
@andrebrait good suggestion. I renamed `.unBlacklistSystemPackages()` to `.enableSystemPackages()`.

Released in 4.0.0-beta-2, along with some bugfixes for JSON serialization and deserialization.

**Comment by GedMarc** [comment]
Will do but I'm pushing 3.1.13 into prod this weekend, will be focusing on that for this week a bit  :+1: 

I'll see if I can pull it into my 100 odd apps on sat :)

**Comment by GedMarc** [comment]
P.S. Thank you for being so reliable when it comes to urgent fixes, life changing :)

**Comment by lukehutch** [comment]
@GedMarc Dang, that's pretty amazing that you have found so many uses for FCS! And that you are so prolific as a programmer :-)

I do try to drop everything when a bug is reported. This is a result of way too many years of reporting literally thousands of bugs across many bug trackers of many projects, and averaging seeing the developers fix about 5% of them :-/

**Comment by seanf** [comment]
@lukehutch The migration guide recommends calling `.getClassNames()` in a few places, but it seems it's actually `.getNames()`.

I suppose `getClasspathURLs()` is the replacement for `ScanResult.getUniqueClasspathElementURLs()`?

**Comment by seanf** [comment]
@lukehutch The tests for my library CDI-Unit are all working in my FCS4 branch, but I'm not sure what to do about the upgrade. 

The small part of the FCS API I use does seem a bit cleaner. But the fact that it's not backward compatible means that CDI-Unit has to commit to one version or another. This will cause a problem for any application which wants to use CDI-Unit with another library which uses the other version of FCS. This could affect any app which uses two libraries which depend on FCS.

Would you please consider putting FCS4 into a different package, with a different Maven groupId/artifactId? This should make it possible for FCS 3 and 4 to co-exist in the same project. Otherwise libraries like CDI-Unit may have to provide both FCS3 and FCS4 versions (or call FCS via ugly reflection instead of using the nice API).

**Comment by giacgbj** [comment]
@lukehutch I would be glad to test it, but I can't find it in a Maven snapshot repository.

**Comment by seanf** [comment]
@giacgbj It's not a snapshot, it's already in Central: http://search.maven.org/#artifactdetails%7Cio.github.lukehutch%7Cfast-classpath-scanner%7C4.0.0-beta-1%7Cjar

**Comment by lukehutch** [comment]
@seanf I think that's what Maven Shade plugin was created to fix? It is a very common problem, for all libraries that ever have an API change. Is Maven Shade an option for you?

**Comment by lukehutch** [comment]
@seanf sorry, I forgot to respond to your other questions -- I fixed the `.getClassNames()` references, thanks for that, and yes, `getClasspathURLs()` is the replacement for `ScanResult.getUniqueClasspathElementURLs()`.

**Comment by seanf** [comment]
> I think that's what Maven Shade plugin was created to fix? It is a very common problem, for all libraries that ever have an API change. Is Maven Shade an option for you?

Well, for all libraries that have a breaking API change. But the complexity of Shade can cause other problems (see https://www.elastic.co/blog/to-shade-or-not-to-shade). Plus FCS is kind of big to start embedding extra copies.

But as I said, I'm not using much of the API, so last night I managed to make a runtime-compiled facade (with javassist) for FCS 3 compatibility. 

Hopefully other libraries using FCS will be able to find solutions (assuming they get updates). There's quite a few of them (congratulations!): http://www.mvnrepository.com/artifact/io.github.lukehutch/fast-classpath-scanner/usages

**Comment by lukehutch** [comment]
@seanf You do raise a good point. The module system "solves" this problem by allowing multiple versions of the same library, but you're totally right that this can do more harm than good (some projects in npm in the Javascript world pull in dozens of versions of the same library, through the transitive dependency graph -- what a mess).

I actually want to change the package name at some point anyway, since I don't think having my own name ("lukehutch") in the package name is good for a mature project (it has outgrown my own usecases -- thanks for the Maven usages link, that's interesting) . The reason my name is there in the package name is because when I was first figuring out how to put this in Maven Central, Sonatype would only let me submit packages for a domain that I owned, and I didn't want to pay for a domain for FCS long-term. They suggested using my GitHub name instead. I should have created a GitHub organization at that point.

I'll work on moving this to a GitHub organization (which will change the package name) for the 4.0 final release. (There's a ton of stuff involved with that, including setting up crypto keys, submitting a request ticket to Sonatype, updating the Maven configuration, etc.)

**Comment by lukehutch** [comment]
@seanf Moved the repo to this new organization. Glad I get to keep the GitHub stars ;-)

**Comment by andrebrait** [comment]
Even the URL to the old repo works (it redirects to the new location).

I loved when I found that out about GitHub, when I moved one of my projects to its own organization.

**Comment by lukehutch** [comment]
@andrebrait You're right, that was a really nice surprise! Even "git push" to the old repo redirects to the new organization without changing anything.

@seanf The package name is now changed to `io.github.fastclasspathscanner`, to reflect the new GitHub organization. I'm glad you brought this up now -- if this was ever going to be changed, now would be the time :-)  For now, the Maven details are the same.

To everybody else: if you have already started porting code, my apologies on changing the package name out from under you. However, "Organize Imports" should fix this immediately, since class names have not changed.

Released in 4.0.0-beta-7.

**Comment by GedMarc** [comment]
Only saw this now, pardon the question in the issue log (but pls include it in the docs as well)~!~

<3

**Comment by lukehutch** [comment]
The release is shaping up -- I want to try to push out 4.0 final around mid week next week, assuming everything looks good, to give some time to fix any post-release bugs before I go on vacation for 3 weeks. If anyone would like to still take a shot at porting existing code to the new API, to help with testing, I'd really appreciate it! 

I should ask though about the name. Java has outgrown the class path, and the future is modular. FastClasspathScanner scans both the class path and the module path (or, really, the visible modules, since it's more a module layer system than a path system). The name has become familiar, but should I look at changing it in the future? Or should I even consider changing the name for this release, since I changed the package name already anyway, and since this release is intended to be stable for a long time? Your feedback would be appreciated.

**Comment by andrebrait** [comment]
Without leaving the FCS initials, one obvious alternative would be FastClassScanner.
I really don't see something that can encompass both classpath and modules.

If you're really into changing it, this release should be the one to do it. You've already changed a lot (the API, the repo moved to an organization, etc.) so if the name's going to change, why not this one?

Btw, since you're moving this to a new group/artifact ID in Maven central, make sure the entries to the old one reference the new one (like it usually does when a project moves to another group/artifact ID).

**Comment by lukehutch** [comment]
@andrebrait That's actually a brilliant solution, thanks. Really FCS is now about scanning the class graph, more than the classpath, so the name you suggest is actually perfect.

I totally agree that if I am ever to change it, the time is now. Yes, a lot has changed already -- my apologies again to you all for the churn, and thanks for your patience. I really do want to make this *the* long-term release for FCS. The codebase is in better shape than ever, and almost the entire classfile format is finally covered by a clean, uniform API. I don't know of any other major things that need doing to the codebase (famous last words, I know).

Thanks also for the pointer on redirecting Maven when the group/artifact id changes, I didn't know that was a possibility, and that should help a lot.

**Comment by lukehutch** [comment]
@andrebrait I started going through the motions of renaming FastClasspathScanner to FastClassScanner, then I realized that it's a bit awkward to say "Fast Class Scanner" because of all the 's's (try saying it five times fast), but even more so, the package name has three 's's in a row: fastclassscanner -- which is just plain confusing to type and to look at :-)

In the end, I settled on simply "ClassGraph". It's nice, simple and clean, and surprisingly not taken, as far as I can tell.

**Comment by lukehutch** [comment]
I wrote a message to the mailing list describing the name change to ClassGraph:

https://groups.google.com/d/msg/classgraph-users/aC_mVkTgrs0/qTZk1qgxCAAJ

**Comment by lukehutch** [comment]
Things are stabilizing, so I'm going to close this bug, but please feel free to open new bugs for any new problems you come across, or for any feature or change requests you may have.

Thanks everyone for your testing and suggestions so far.

**Comment by PascalSchumacher** [comment]
There seems to be a small error in https://github.com/classgraph/classgraph/wiki/Porting-FastClasspathScanner-code-to-ClassGraph I guess:

>Classpath-fetching methods have been renamed: `.getUniqueClasspathElementURLs()` becomes `.getClasspathElementURLs()`, etc.

should be:

>Classpath-fetching methods have been renamed: `.getUniqueClasspathElementURLs()` becomes `.getClasspathURLs()`, etc.

**Comment by PascalSchumacher** [comment]
There seems to be no direct replacement for `getNamesOfAnnotationsWithMetaAnnotation`.

I guess `getClassesWithAnnotation` also returns Annotations?

**Comment by lukehutch** [comment]
@PascalSchumacher Thanks, I fixed the classpath element URLs porting documentation. For meta-annotations, I added:

* Annotation APIs now handle meta-annotations (so methods with "Meta" in them have been removed). For example, `scanResult.getNamesOfAnnotationsWithMetaAnnotation()` becomes `ScanResult.getAllAnnotations().filter(ci -> !ci.getAnnotations().isEmpty()).getNames()`. If you want direct annotations on a class (without including meta-annotations), you call `ClassInfoList#getDirect()`.

Please let me know if that's clear enough.

**Comment by PascalSchumacher** [comment]
@lukehutch Thank you very much!

**Comment by lukehutch** [comment]
You're welcome.. I think there was a method too for getting annotations with a specific meta-annotation.. For that, just change the filter function in the example I gave to `ci -> ci.hasAnnotation(metaAnnotationName)`.

This is a lot of the point of the new API, that it be completely generic and composable.

**Comment by lukehutch** [comment]
I just released version 4.0.0: https://github.com/classgraph/classgraph/releases/tag/classgraph-4.0.0
Thanks to all for your contributions.
