### ISSUE TITLE
Please include in official documentation v3 and v4 package requires for JDK9^

### ISSUE THREAD

**Issue by GedMarc** [classgraph/classgraph#217]
I know for me this is just an important thing :)

FCS v3 - requires io.github.lukehutch.fastclasspathscanner; To use the global class fetcher opens xxx.xxx.xx to io.github.lukehutch.fastclasspathscanner;

FCS v4 - requires io.github.fastclasspathscanner; To use the global class fetcher opens xxx.xxx.xx to io.github.lukehutch.fastclasspathscanner;

Did the package/groupid change in the maven artifact repository?

**Comment by lukehutch** [comment]
Yes, sorry, the package name and Maven artifact name did change. See #215 for info.

The main `README.md` file has the updated `requires` line, and the updated Maven dependency rule:

https://github.com/fast-classpath-scanner/fast-classpath-scanner

Please let me know if this has all the necessary info for v4. (v3 docs can be checked out of github using a tag... Not great, I know, but v3 really is deprecated now, v4 is the way forward).

**Comment by lukehutch** [comment]
The instructions for fetching the v3 documentation is at the bottom of this new Wiki page, split out from the release notes. It's a bit obscure and maybe hard to find, but the old Maven rules are there. It's a bit more obvious you have to change the Maven name now that the whole project name has changed.

The updated Maven rule and module dep are here:

https://github.com/classgraph/classgraph/wiki

Also, I added Maven package relocation notification for the old project branches. Thanks for the heads-up on that.
