### ISSUE TITLE
NPE on simple scan

### ISSUE THREAD

**Issue by devgianlu** [classgraph/classgraph#220]
This is all I'm doing:
``` 
ScanResult scanResult = new ClassGraph()
                .verbose()
                .enableClassInfo()
                .enableAnnotationInfo()
                .scan();
``` 

It works if I add `#whitelistPackages(String...)`.

I'm using version 4.0.0-beta-11. I've attached the stacktrace: [stacktrace.txt](https://github.com/classgraph/classgraph/files/2238982/stacktrace.txt)

**Comment by lukehutch** [comment]
@devgianlu Thanks for the report, should be fixed in -beta-12, which I'll push out in a second.

**Comment by devgianlu** [comment]
Working fine now.

**Comment by lukehutch** [comment]
Thanks for confirming.
