### ISSUE TITLE
4.0.3 is not usable as Java 9 module

### ISSUE THREAD

**Issue by aholstenson** [classgraph/classgraph#230]
In version 4.0.3 it seems like the `module-info.java` is included directly instead of being compiled into a class. This makes it impossible to require `io.github.classgraph` as the Java 9 compiler will error with: `module not found: io.github.classgraph`

**Comment by lukehutch** [comment]
Thanks for reporting this. Large sections of the `pom.xml` got reverted to an old version when I merged a PR. I should have checked that PR more carefully, sorry about that!

Fixed and released in 4.0.4. Should work, so I'll close this, but please do report back to let me know if it's working again. Thanks!

**Comment by aholstenson** [comment]
Requiring the module now works again. Thanks for the quick fix!

**Comment by lukehutch** [comment]
Great, you're welcome, thanks for confirming!
