### ISSUE TITLE
Feature Request: Include degree of separation in ClassInfo

### ISSUE THREAD

**Issue by cjnygard** [classgraph/classgraph#238]
Example:  Search for the nearest ancestor which contains a specific annotation.  

In the present API, I can use `intersect()` to find all ancestors which also have the annotation, but there's no specific order to the list returned.  Consequently, I still need to walk back through the ancestry to find nearest superclass.  I can test for membership within the intersection, but I can't stop until I reach Object. 

Alternatively, it would be a simple matter of sorting the results if the ClassInfo were to include a metric for degree of separation from the "anchor" class.

**Comment by lukehutch** [comment]
The current order is the result of sorting by name. I think you're saying you're calling `ClassInfo#getSuperclasses()`, and you want the classes to be returned in reverse ancestry order? Are there other methods you are using that also need a different sort order?

**Comment by lukehutch** [comment]
Released in 4.0.7. I expect this will solve the problem for you, but please comment here to let me know whether this is the case, and I will re-open this bug if there are more corner cases I missed. Thanks!
