### ISSUE TITLE
ScanResult leaks shutdown hooks

### ISSUE THREAD

**Issue by seanf** [classgraph/classgraph#240]
This code shows that a shutdown hook (ie unstarted thread) is created but not destroyed for each scan, even when using try-with-resources for ScanResult.

Seems like `Runtime.getRuntime().removeShutdownHook()` might be needed. [EDIT: was addShutdownHook, nonsensically.]

```java
import java.lang.reflect.Field;
import java.util.Map;

import io.github.classgraph.ClassGraph;
import io.github.classgraph.ScanResult;

public class ClassGraphShutdownHooks {
    public static void main(String[] args) throws Exception {
        for (int i = 0; i < 100_000; i++) {
            try (ScanResult scan = new ClassGraph().scan()) {
            }
            System.out.printf("Number of shutdown hooks: %d%n", countShutdownHooks());
        }
    }

    // thanks to https://stackoverflow.com/a/6865509/14379
    // works on Java 8
    private static int countShutdownHooks() throws ReflectiveOperationException {
        Class clazz = Class.forName("java.lang.ApplicationShutdownHooks");
        Field field = clazz.getDeclaredField("hooks");
        field.setAccessible(true);
        Map<?, ?> hooks = (Map<?, ?>) field.get(null);
        return hooks.size();
    }
}
```

Output:

```
Number of shutdown hooks: 1
Number of shutdown hooks: 2
Number of shutdown hooks: 3
Number of shutdown hooks: 4
Number of shutdown hooks: 5
Number of shutdown hooks: 6
Number of shutdown hooks: 7
Number of shutdown hooks: 8
Number of shutdown hooks: 9
Number of shutdown hooks: 10
...
```

(Related to https://github.com/classgraph/classgraph/issues/233)

**Comment by lukehutch** [comment]
@seanf Good point, thanks. I will change this to a single static shutdown hook, and a `ConcurrentHashSet` that stores a `WeakReference<ScanResult>` to each `ScanResult` that has not yet been closed.

Just curious -- how on earth did you notice this?

**Comment by lukehutch** [comment]
Should be fixed in 4.1.2.

**Comment by seanf** [comment]
> Just curious -- how on earth did you notice this?

@lukehutch 
I was reviewing the release notes, saw mention of [try-with-resources and shutdown hooks](https://github.com/classgraph/classgraph/releases/tag/classgraph-4.0.5), and wondered how these two different approaches were interacting, so I looked at the code and noticed that the addShutdownHook didn't have a matching removeShutdownHook. I guess I don't fully trust shutdown hooks.

**Comment by lukehutch** [comment]
Good to know. I have never needed them before, and there are tons of gotchas to using them right, so this has been a step learning curve. It was a good catch, thanks.

**Comment by seanf** [comment]
@lukehutch Re: the "100,000 scans in production" :-), no, but CDI-Unit currently runs between 1 and 3 ClassGraph scans for every test method in a CDI-Unit test. So it can add up.
