### ISSUE TITLE
getParameterInfo - NullPointerException

### ISSUE THREAD

**Issue by MrChebik** [classgraph/classgraph#241]
Hi, I tried to get info about parameters in method. But I catch an exception:
```java
System.out.println(Arrays.toString(method.getParameterInfo()));
```

```
Exception in thread "Thread-6" java.lang.NullPointerException
	at io.github.classgraph.MethodParameterInfo.getAnnotationInfo(MethodParameterInfo.java:138)
	at io.github.classgraph.MethodParameterInfo.toString(MethodParameterInfo.java:167)
```

Snippet of scaner:
```java
try (ScanResult scanResult = new ClassGraph()
        .enableAllInfo()
        .enableSystemPackages()
        .disableJarScanning()
        .disableDirScanning()
        .whitelistPackages("java", "java.lang", "javax", "javafx")
        .blacklistPackages("java.applet", "java.awt")
        .scan()) {
// ...
}
```

**Comment by lukehutch** [comment]
Hi @MrChebik, I believe this is a bug that was fixed a few versions ago. Can you please test with the latest version and see if it resolves the problem?

**Comment by MrChebik** [comment]
Everything turned out with the version from the source.
As I understand it, is not implemented to get the name of the methods? Because I get everywhere `_unnamed_param`.
Thank you for the wonderful library!

**Comment by lukehutch** [comment]
@MrChebik Glad it's working for you with the latest version.

See the Javadoc for `MethodParameterInfo#getName()`:

https://github.com/classgraph/classgraph/blob/master/src/main/java/io/github/classgraph/MethodParameterInfo.java#L74

You need to compile your code with the `-parameters` switch (and you have to be using JDK 8+) for method parameter names to be stored in the classfile by the compiler. If you don't do that, then the `toString()` method just uses "_unnamed_param" instead.

**Comment by MrChebik** [comment]
Only two hours later, I realized that it would only help for my code...
That I only not has tried, but okay.

What about system libraries? It turns out that I will not be able to see their parameter names, and I will have to decompile the class?

**Comment by lukehutch** [comment]
ClassGraph has the same information as a decompiler. If the class wasn't compiled with parameters, the information simply isn't there. It's not there at all in JDK < 7, and it's only there in later versions if it was manually enabled. I don't know how OpenJDK or Oracle JDK were compiled, but you could check yourself to be sure.

**Comment by MrChebik** [comment]
Okay, Thanks.
I'll just make releases of the project with this argument.
