### ISSUE TITLE
Sharing 'point-free' usage example (kotlin)

### ISSUE THREAD

**Issue by davidmoshal** [classgraph/classgraph#250]
```kotlin       
 ClassGraph()
                .enableAllInfo()
                .whitelistPackages("app")
                .scan().apply {

                    getSubclasses(Entity::class.java.name)
                            .forEach {
                                val c: Class<*> = it.loadClass()
                                println(it)
                                println(c)                           
                            }

                    getSubclasses(Payload::class.java.name)
                            .forEach {
                            }
                }
```

**Comment by lukehutch** [comment]
Hi, what is this illustrating? What do you mean by "point-free"?

**Comment by lukehutch** [comment]
Oh, I see what you are illustrating -- `apply` allows you to eliminate `this` and call several `ScanResult` methods in a row without having to explicitly specify the receiver in each case?

This is probably useful for some users, but with the new recommendation for `ScanResult` to be specified in a try-with-resources block, this would become

```
          ClassGraph()
                .enableAllInfo()
                .whitelistPackages("app")
                .scan()
                .use { 
                    it.apply {

                      getSubclasses(Entity::class.java.name)
                            .forEach {
                                val c: Class<*> = it.loadClass()
                                println(it)
                                println(c)                           
                            }

                      getSubclasses(Payload::class.java.name)
                            .forEach {
                            }
                    }
                }
```

Did I get that right? I don't use Kotlin :-)

Are you suggesting this should be added to the docs?

**Comment by lukehutch** [comment]
I added mention of `.use{...}` to the docs, at least:

>  💡 The `ScanResult` should be assigned to a local variable in a try-with-resources block (or use the `ScanResult` inside a `.use{...}` block in Kotlin, or close the `ScanResult` in a `finally` block in Scala), so that the resources associated with the `ScanResult` (including any temporary files created by unzipping inner jars) are freed/deleted once the `ScanResult` is no longer needed.

**Comment by lukehutch** [comment]
Closing, feel free to comment if you think this needs to be added to the docs. It might be better to get a bunch of Kotlin-related advice (maybe language-specific advice, for Java, Scala, Kotlin etc.) together on one page in the docs. Feel free to submit a PR if you would like to kick this off.

**Comment by davidmoshal** [comment]
Ok, will fo, thanks

**Comment by davidmoshal** [comment]
Ok, will do, thanks
