### ISSUE TITLE
Incompatible types

### ISSUE THREAD

**Issue by aaloise** [classgraph/classgraph#265]
I have the following code:

ScanResult result = new ClassGraph().verbose().enableAllInfo().scan();
ClassInfoList infolist = result.getSubclasses("org.codehaus.groovy.runtime.m12n.ExtensionModule").directOnly();
ClassInfo info = infolist.get("VertxExtensionModule");                            
ExtensionModule module = info.loadClass().newInstance();

The last line complains abou incompatible types when compiling...

"incompatible types: capture#1 of ? cannot be converted to org.codehaus.groovy.runtime.m12n.ExtensionModule"

Is this a normal behaviour?

**Comment by lukehutch** [comment]
No, that should probably work. Can you please create a minimal test case so I have all the Maven dependencies etc.?

**Comment by aaloise** [comment]
This is the project in github

https://github.com/aaloise/vertx-lang-groovy

The class is https://github.com/aaloise/vertx-lang-groovy/blob/master/vertx-lang-groovy-gen/src/main/java/io/vertx/lang/groovy/VertxExtensionMethodBoostrap.java

**Comment by aaloise** [comment]
You only have to try to build the project and you will see the compilation error mentioned above.

I tried to include verbose() but didn't see any difference

**Comment by aaloise** [comment]
FYI this is the old cold that was working with FastClasspathScanner:

try {
        MetaClassRegistryImpl registryImpl = (MetaClassRegistryImpl) registry;
        ExtensionModuleRegistry moduleRegistry = registryImpl.getModuleRegistry();
        HashMap<CachedClass, List<MetaMethod>> map = new HashMap<>();
        new FastClasspathScanner().matchSubclassesOf(ExtensionModule.class, subclass -> {
          if (subclass.getSimpleName().equals("VertxExtensionModule")) {
            try {
              ExtensionModule module = subclass.newInstance();
              if (!moduleRegistry.hasModule(module.getName())) {
                moduleRegistry.addModule(module);
                for (MetaMethod metaMethod : module.getMetaMethods()) {
                  List<MetaMethod> metaMethods = map.computeIfAbsent(metaMethod.getDeclaringClass(), k -> new ArrayList<>());
                  metaMethods.add(metaMethod);
                  FastArray methods = metaMethod.isStatic() ? registryImpl.getStaticMethods() : registryImpl.getInstanceMethods();
                  methods.add(metaMethod);
                }
              }
            } catch (Exception e) {
              e.printStackTrace();
            }
          }
        }).scan();
        for (Map.Entry<CachedClass, List<MetaMethod>> e : map.entrySet()) {
          CachedClass cls = e.getKey();
          List<MetaMethod> metaMethods = new ArrayList<>();
          Collections.addAll(metaMethods, cls.getNewMetaMethods());
          metaMethods.addAll(e.getValue());
          cls.setNewMopMethods(metaMethods);
        }
      } catch (Throwable ignore) {
      }

**Comment by lukehutch** [comment]
I get a whole lot of errors when I try to build:

```
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-no-vertx-snapshots) @ vertx-lang-groovy ---
[WARNING] Rule 1: org.apache.maven.plugins.enforcer.RequireReleaseDeps failed with message:
No Vert.x Snapshots Allowed during a release!
Found Banned Dependency: io.vertx:vertx-dropwizard-metrics:jar:3.6.0-SNAPSHOT
Found Banned Dependency: io.vertx:vertx-service-discovery-backend-consul:jar:3.6.0-SNAPSHOT
Found Banned Dependency: io.vertx:vertx-auth-jwt:jar:3.6.0-SNAPSHOT
Found Banned Dependency: io.vertx:vertx-web-templ-handlebars:jar:3.6.0-SNAPSHOT
Found Banned Dependency: io.vertx:vertx-config-zookeeper:jar:3.6.0-SNAPSHOT
Found Banned Dependency: io.vertx:vertx-config-git:jar:3.6.0-SNAPSHOT
Found Banned Dependency: io.vertx:vertx-service-discovery:jar:3.6.0-SNAPSHOT
[...]
```

**Comment by lukehutch** [comment]
Please provide me with some clear instructions of how to build and reproduce this (just `git clone <URL> ; mvn package` is not sufficient), as well as the verbose logs I requested, or (even better) a standalone project that contains only the bare minimum necessary to illustrate the problem. I can't figure out what's going wrong if I can't replicate the problem. Thanks.

**Comment by GedMarc** [comment]
Ok so I also can't get this to build - there must be a lot of tricks to getting the code base up and running

But off the bat :

1) Stop using class.newInstance() - use class.getDeclaredConstrutors().newInstance(). This will highlight the problem with abstract classes and correctly throw ReflectiveOperationException. newInstance on class is deprecated and should not be used AT ALL/ever

Also, it looks like your bug is a generic groovy problem.

https://github.com/szantopeter/groovy-compile-failure
https://issues.apache.org/jira/browse/GROOVY-7306

**Comment by lukehutch** [comment]
@GedMarc thanks trying to build this too, and thanks for the links. +1 on not using newInstance (though it's good to know the reason why, I didn't know some of those details).

This bug may be caused by the same issue as the links you provided, but the links actually seem to indicate two different problems (one to do with constructor stubs being generated wrong, and one to do with casting, but both involving generics), and in this case, the example given by @aaloise doesn't even involve generics, so I'm not convinced that this is even the same issue, it might be something different again.

From the little I know of Groovy, it has always tried really hard to pretend it was dynamically typed, and has played fast and loose with types as a result, so these sorts of bugs are hardly surprising... but I'm surprised Groovy has been around for so long and these bugs are only being discovered and reported now. Maybe this represents a regression. But that should have been caught by some regression tests, surely?

(Then again, this may be a ClassGraph bug instead, or (very possibly) it could be an issue with a class and its superclass being loaded by unrelated classloaders, due to one of the classes in question being loaded by another ClassLoader before the ClassGraph code is even run.)

**Comment by aaloise** [comment]
@lukehutch and @GedMarc I always use Travis CI to test the build. Seems more practicle for me.

**Comment by aaloise** [comment]
What gets my attention is that with FastClasspathScanner the piece of code I sent above, it works. But when I tried to "translate" to ClassGraph, that error happens. Please try to build using Travis CI.

**Comment by aaloise** [comment]
@GedMarc this is what happens when getDeclaringClass().newInstance() is used:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project vertx-lang-groovy-gen: Compilation failure
[ERROR] /home/travis/build/aaloise/vertx-lang-groovy/vertx-lang-groovy-gen/src/main/java/io/vertx/lang/groovy/VertxExtensionMethodBoostrap.java:[48,56] cannot find symbol
[ERROR]   symbol:   variable getDeclaringClass
[ERROR]   location: class java.lang.Class<capture#1 of ?>
[ERROR] -> [Help 1]

**Comment by lukehutch** [comment]
@aaloise "just build on Travis" doesn't help. Can you please provide a list of commands or steps, starting from a blank slate? In fact if you can please provide the steps for building in Eclipse or another IDE, it would be even better, since this may need to be run in a debugger.

I have asked for verbose logs twice ready and I'll ask a third time. There may be information in the logs that will indicate what's going on. Please help us help you! There's a reason the bug template asks for exact reproduction instructions and verbose logs.

**Comment by lukehutch** [comment]
Re. Your last comment: "cannot find symbol
[ERROR] symbol: variable getDeclaringClass" indicates you're trying to access that method as a variable, rather than calling it as a method...

**Comment by aaloise** [comment]
@lukehutch I already put verbose () and honestly didn't see anything being printed, but will give another try. The only way I test is using Travis because this project is actually a fork from https://github.com/vert-x3/vertx-lang-groovy which i'm trying to help by replacing FastClasspathScanner with ClassGraph


As for getDeclaringClasd you are rigth. It was my mistake

**Comment by lukehutch** [comment]
Your stderr is probably being redirected to a log file then.

I see, well let's try to get to the bottom of this so you can get your PR submitted to Vert.x!

**Comment by GedMarc** [comment]
Yeah I came across the logging verbose() thing quite a while ago - its when console output is redirected to use system.out through jdk logging (but the problem is not the library)

```
public class ClassgraphTest {
    public static void main(String[] args) {
        ScanResult sr =  new ClassGraph().verbose().scan();
    }
}
```
Logs verbose perfectly, ahoy add java.util.logging custom console handler and poof, verbose logs gone, system.err is not used
quick hint though there is probably a million ways to kill the bird
```
System.setErr(System.out);
```

Ok, I just did a quick project with vert.x core and groovy - i didn't check the versions of the dependencies, the parent pom hierarchy for vert.x is horrific.

```
2018-10-25T06:29:19.691+0200	ClassGraph	-- Found module descriptor module-info but module was included in traditional classpath -- will not create ModuleInfo for this classpath element
2018-10-25T06:29:19.738+0200	ClassGraph	Completed (took 1.445516 sec)
Exception in thread "main" java.lang.NullPointerException
	at ClassgraphTest.main(ClassgraphTest.java:19)
```

[classgraph.zip](https://github.com/classgraph/classgraph/files/2513270/classgraph.zip)

**Comment by lukehutch** [comment]
I added the `vertx-lang-groovy` dependency to @GedMarc's classgraph.zip project, and found the full name of `VertxExtensionModule` (`io.vertx.groovy.core.VertxExtensionModule`).

This test project exposed a bug, which may or may not be the cause of the bug that @aaloise reported. It is only triggered if a class is defined two different ways (e.g. with two different type signatures) in the classpath. In this case, @GedMarc included `groovy:3.0.0-alpha-3`, but `vertx-lang-groovy:3.5.4` depends upon `groovy-all:2.4.15`, and some of the Groovy internal classes changed signature.

I don't know if this will fix the original problem or not, but I released this as 4.4.8. @aaloise please let me know if this resolves the problem.

**Comment by aaloise** [comment]
Ok @GedMarc , changes made. DIfferent error now:

```
java.lang.NullPointerException
	at io.vertx.lang.groovy.VertxExtensionMethodBoostrap.install(VertxExtensionMethodBoostrap.java:49)
```
Just to be sure, I put a System.out.println(info) and got null printed

**Comment by lukehutch** [comment]
@aaloise well what's at that line (49)? What object is null?

**Comment by aaloise** [comment]
module is the null object

**Comment by lukehutch** [comment]
`module` can't be the problem, it is the destination of the assignment. Is `info` null? If so, the flag is not being found. Can you please attach the logs now, after doing the following?:

```
System.setErr(System.out);
```

**Comment by aaloise** [comment]
I got confused, but yes, info is null. So if it is null, module is direclty affected. Actually infolist is empty, thats why info is null.

I guess line 2488 is what you're looking for?

[log.txt](https://github.com/classgraph/classgraph/files/2516014/log.txt)

**Comment by GedMarc** [comment]
second one much better!

**Comment by GedMarc** [comment]
2018-10-25T17:21:38.142+0000	ClassGraph	---------------- Skipping non-whitelisted path: io/vertx/lang/groovy/VertxExtensionMethodBoostrap.class

oops..
2018-10-25T17:21:38.000+0000	ClassGraph	-- packagePrefixWhiteBlackList: whitelistPrefixes: [io.vertx.groovy.core.]

Try including io/vertx/lang/groovy in the whitelist

**Comment by aaloise** [comment]
@GedMarc dit it. Same result

2018-10-25T17:49:56.987+0000	ClassGraph	-- packagePrefixWhiteBlackList: whitelistPrefixes: [io.vertx.groovy.core., io.vertx.lang.groovy.]

**Comment by GedMarc** [comment]
please post the logs with both packages in the white list

**Comment by aaloise** [comment]
[log3.txt](https://github.com/classgraph/classgraph/files/2516169/log3.txt)

**Comment by GedMarc** [comment]
Ohhhhh my bad!! Wrong class xD xD

Where is io.vertx.groovy.core.VertxExtensionModule? Luke mentions he found the class file in the all- module for groovy, but this class is not in your classpath at all.

Please make sure you have the required dependency in your project - you can see the full list on line 

There is
com/acme/groovy/pkg/VertxExtensionModule.class
io/vertx/groovy/codegen/extra/VertxExtensionModule.class
io/vertx/groovy/codegen/testmodel/VertxExtensionModule
io.vertx.groovy.ext.web.templ.handlebars.VertxExtensionModule
io.vertx.groovy.ext.auth.mongo.VertxExtensionModule

**Comment by aaloise** [comment]
Seems that a VertxExtensionModule class is generated at compile phase, based on a template.

https://github.com/aaloise/vertx-lang-groovy/blob/master/vertx-lang-groovy-gen/src/main/resources/vertx-groovy/template/gen-ext-module.templ

After that, io.vertx.groovy.codegen.testmodel.VertxExtensionModule was created and the error now changed, but I think that is nothing to do with ClassGraph. Log attached.

[log4.txt](https://github.com/classgraph/classgraph/files/2516386/log4.txt)

**Comment by lukehutch** [comment]
@aaloise This latest log doesn't have any ClassGraph output anywhere in the log, and yes, the two test failures don't seem to have anything to do with ClassGraph, it would seem, unless the null key put into the map was again the result of a class not being found.

Maybe you can send the vertx-groovy developers a PR for what you have so far, and get them to test it on their build system? It appears your Travis build may not be set up right.

**Comment by lukehutch** [comment]
@aaloise All good, thanks for reporting it, and for your patience in working through this. This did result in the discovery of a bug regression in ClassGraph, whether or not it was the cause of what you were seeing, so I appreciate the report. Best of luck with your Vert.x work, it's a cool project.

@GedMarc Thanks for your help with this!

**Comment by aaloise** [comment]
Unfortunately I have to reopen the issue. As you can see in the logs, NPE still happen with the line:

```
ExtensionModule module =(ExtensionModule) info.loadClass().getDeclaredConstructor().newInstance();
```

Any chances that ClassGraph is scaning the package before io.vertx.groovy.codegen.testmodel.VertxExtensionModule gets generated? Since the class is based on a template, perhaps that's why info is null. May it's looking for something that is not there yet. Makes any sense?

**Comment by lukehutch** [comment]
No, it finds it OK:

```
INFO: Generated model io.vertx.codegen.testmodel.AbstractHandlerUserType: io.vertx.groovy.codegen.testmodel.VertxExtensionModule
[...]
2018-10-28T18:22:44.314+0000	ClassGraph	-- Parsing classfile file:/home/travis/build/aaloise/vertx-lang-groovy/vertx-lang-groovy-gen/target/test-classes/io/vertx/groovy/codegen/testmodel/VertxExtensionModule.class (took 0.010470 sec)
2018-10-28T18:22:44.318+0000	ClassGraph	---- Found class io.vertx.groovy.codegen.testmodel.VertxExtensionModule
2018-10-28T18:22:44.318+0000	ClassGraph	------ Superclass: org.codehaus.groovy.runtime.m12n.ExtensionModule
[...]
public class io.vertx.groovy.codegen.testmodel.VertxExtensionModule extends org.codehaus.groovy.runtime.m12n.ExtensionModule
```

And this happens after the codegen step.

Which object is null this time? Is it `info` again? The code you quoted is not in the log, is it the line referenced by this?:

```
java.lang.NullPointerException
	at io.vertx.lang.groovy.VertxExtensionMethodBoostrap.install(VertxExtensionMethodBoostrap.java:49)
```

What prints this line in the log? This seems to be some of your code, indicating that the class was actually found:

```
public class io.vertx.groovy.codegen.testmodel.VertxExtensionModule extends org.codehaus.groovy.runtime.m12n.ExtensionModule
```

**Comment by aaloise** [comment]
Info is not returning null. I even printed module.getClass().getName() and it even show io.vertx.groovy.codegen.testmodel.VertxExtensionModule.

That line, the 49th, points to that piece of code I sent. But I didn't get it. Info is not null, module gets the class instanciated....

**Comment by aaloise** [comment]
NPE shows that GroovyVerticleFactory calls VertxExtensionMethodBoostrap, which is the class that contains the ClassGraph code. I'm confused now. If info isn't null, and module receives a new instance of VertxExtensionModule, don't know why NPE gets thrown.

**Comment by lukehutch** [comment]
Can you run this in a debugger, and set a breakpoint before the exception is thrown?

**Comment by lukehutch** [comment]
@aaloise if `info` is not null, then ClassGraph finds the class you're interested in. The `NullPointerException` is coming from something else. Try printing out the values of each object reference that you get in that method.

If the `ClassCastException` is fixed at this point too, it sounds like this bug is not in ClassGraph. Please respond with what you find.

**Comment by aaloise** [comment]
@lukehutch did what you asked... debuuger shows info as null...

![info_null](https://user-images.githubusercontent.com/1064972/47749283-38588b00-dc63-11e8-81c8-4214ac85ffc9.JPG)

**Comment by lukehutch** [comment]
@aaloise can you please provide **detailed instructions** about how exactly to modify the code to the form you have, and how to build and run it?

**Comment by aaloise** [comment]
I used Intellij Idea. With it's git plugin, got the project https://github.com/aaloise/vertx-lang-groovy/ locally.

Set the breakpoint one line below info and run the class DeploymentTest in debug mode.

**Comment by GedMarc** [comment]
jurre but the pom downloads the internet xD

**Comment by GedMarc** [comment]
Error: Could not find or load main class @{surefireArgLine}

**Comment by GedMarc** [comment]
you're making this very difficult :(

**Comment by lukehutch** [comment]
@aaloise closed? Did you get it working?

**Comment by aaloise** [comment]
@lukehutch no, but I'm convinced that's is not a ClassGraph issue. There are a lot NPE being throw, but any of them are related to VertxExtensionModule, which is the Class I needed to be found by ClassGraph.

**Comment by lukehutch** [comment]
OK, good luck!
