### ISSUE TITLE
SPI Config JPMS

### ISSUE THREAD

**Issue by GedMarc** [classgraph/classgraph#273]
Caused by: java.util.ServiceConfigurationError: io.github.classgraph.ClassLoaderHandler: module io.github.classgraph does not declare `uses`

JDK 10 and 11 for your SPI's, can you place the uses clause in your module.info :)

**Comment by GedMarc** [comment]
Caused by: java.util.ServiceConfigurationError: io.github.classgraph.ClassLoaderHandler: module io.github.classgraph does not declare `uses`
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
	at java.base/java.util.ServiceLoader.checkCaller(ServiceLoader.java:574)
	at java.base/java.util.ServiceLoader.<init>(ServiceLoader.java:503)
	at java.base/java.util.ServiceLoader.load(ServiceLoader.java:1691)
	at io.github.classgraph@4.4.10/io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry.loadAdditionalClassLoaderHandlers(ClassLoaderHandlerRegistry.java:137)
	at io.github.classgraph@4.4.10/io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry.<clinit>(ClassLoaderHandlerRegistry.java:67)
	at io.github.classgraph@4.4.10/io.github.classgraph.utils.ClasspathFinder.<init>(ClasspathFinder.java:229)
	at io.github.classgraph@4.4.10/io.github.classgraph.Scanner.call(Scanner.java:411)

**Comment by lukehutch** [comment]
@michael-simons I think this is for the service discovery you added / got working... Sounds like a one-line fix...

**Comment by GedMarc** [comment]
![image](https://user-images.githubusercontent.com/5367513/47618745-70cf5c00-dadf-11e8-9017-ebbc5a95c94b.png)
 should do it

**Comment by lukehutch** [comment]
@GedMarc Thanks for the info, I didn't know about that. @michael-simons the descriptor is in `src/moditect`. But actually I'll need to push out a new release anyway, so since it's such a simple change, I can save you the trouble of sending me a PR -- I'll fix it. Sorry to bother you!

**Comment by lukehutch** [comment]
@GedMarc Interesting that this doesn't bomb until runtime when you try to actually use the service. Runtime failures that could be statically detected (e.g. at the time you try to load the module) are an antipattern :-/

**Comment by michael-simons** [comment]
Sorry for the inconvenience I have caused. I even have JDK 10 / 11 demos around, but Neo4j OGM is compiled on JDK 8, so I didn't noticed. I've opened another PR, that opens up

`exports io.github.classgraph.utils;`

Otherwise libraries on module path cannot implement custom handlers. See attached example on the PR.

**Comment by GedMarc** [comment]
This was something I came across a while ago hey, I thought it was very weird, only errors out on ServiceLoader.load,
While JRE 8 only needs it in meta-inf services, jdk 9 and 10 needs it in both locations, and jre 11 only in as a uses clause module.
Some other interesting things I came across is that it only requires a public constructor, but the class itself doesn't have to be public at all, and the package it is in doesn't need to be exposed - this adds quite a bit of encapsulation frustrations xD 

But I must say, actually declaring that you are 'providing' and 'using' services (jre 8 you can use wherever, jpms only one 'uses' per provider is allowed) draws out a really good graph on references, 
With injection it's a bit of overhead, as you have to construct and then provide, AOP you've already instantiated an instance, but to get the proxy/enhanced class you have to run it through anyway.

Still faster amazingly...

**Comment by GedMarc** [comment]
@michael-simons Is this required? As long as the package the interface/class is in is exported it should be fine?
Are you extending any classes in the util package?

**Comment by michael-simons** [comment]
Seems required. 

Given the following handler

```
package com.example.classgraph;

import io.github.classgraph.ClassLoaderHandler;
import io.github.classgraph.ScanSpec;
import io.github.classgraph.utils.ClasspathOrder;
import io.github.classgraph.utils.LogNode;

public class CustomHandler implements ClassLoaderHandler {
	@Override
	public String[] handledClassLoaders() {
		System.out.println("This handle handles nothing.");
		return new String[0];
	}

	@Override
	public ClassLoader getEmbeddedClassLoader(ClassLoader outerClassLoaderInstance) {
		return null;
	}

	@Override
	public DelegationOrder getDelegationOrder(ClassLoader classLoaderInstance) {
		return null;
	}

	@Override
	public void handle(ScanSpec scanSpec, ClassLoader classLoader, ClasspathOrder classpathOrderOut, LogNode log) {
	}
}
```

Compilation fails with

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/msimons/Projects/Issues/classgraphtest/src/main/java/com/example/classgraph/CustomHandler.java:[5,28] package io.github.classgraph.utils is not visible
  (package io.github.classgraph.utils is declared in module io.github.classgraph, which does not export it)
[ERROR] /Users/msimons/Projects/Issues/classgraphtest/src/main/java/com/example/classgraph/CustomHandler.java:[6,28] package io.github.classgraph.utils is not visible
  (package io.github.classgraph.utils is declared in module io.github.classgraph, which does not export it)
[INFO] 2 errors 
```

**Comment by GedMarc** [comment]
Sorry sorry :) method object are in the package

**Comment by michael-simons** [comment]
Full example here:

[classgraphtest-issue273.zip](https://github.com/classgraph/classgraph/files/2522973/classgraphtest-issue273.zip)

You can run it with `./mvnw spring-boot:run`

**Comment by michael-simons** [comment]
No need to be sorry, I'm learning so much here. Thanks for that.

**Comment by GedMarc** [comment]
Yeah the example is busy downloading the internet xD some interesting choices, the battle for clean module paths continues :)

I was looking at your module-info, opening everything to spring. I've been thinking about doing that... But was that just for the example?

This is trying to do it "properly", exporting with given requirements, only opening to the injector, one module one package exported (lord this is terrifying). 
I get a performance boost, running the same thing in jdk 8 (just switch the profiles from jre8 to jre11) its almost 6 seconds longer to startup - and that's just the strict encapsulation and SPI), the classpath scanner from 1.4seconds went to 400ms

but is it worth the hassle cause omfg.... 

https://github.com/GedMarc/JWebMPHomePage/blob/master/src/jre10/java/module-info.java

**Comment by lukehutch** [comment]
I should have looked back at this before pushing out a release (4.4.11)! 

Actually I didn't want to export `io.github.classgraph.utils` -- that's for internal usage only. I didn't realize that `ClasspathOrder` was in the utils package... I might have to move that to the main package. It shouldn't break API for anybody, since as far as I'm aware, nobody is actually implementing their own `ClassLoaderHandler` yet. (I'd hate to bump the version number up to 4.6.x for this...)

**Comment by lukehutch** [comment]
Oh, and `LogNode` is in `utils` too... 

The main package is getting huge now. So many classes. But Java has no way of making something "jar-private" or "module-private" (beyond the level of individual packages, for modules), which is why the main package has become a dumping-ground for classes!

@michael-simons The reason for the speedup on JDK9+ is that listing the resources in a module is blazingly fast.

**Comment by lukehutch** [comment]
@GedMarc wow -- I wondered how complex module descriptors could get. Now I know.

**Comment by lukehutch** [comment]
I tried moving the relevant classes to the main package, and now I'm in the middle of dependency hell -- they refer to other classes in the `utils` package... and I have to head out. I guess I'll have to fix this later :-/

**Comment by michael-simons** [comment]
OMG the module descriptor @GedMarc.

**Comment by GedMarc** [comment]
True Story.... xD xD

**Comment by lukehutch** [comment]
@michael-simons I think rather than do this refactoring (which is quite invasive, given Java's myopic visibility limiting options), maybe I should get rid of the ability to supply a user-defined `ClassLoaderHandler`. I just realized this can be worked around anyway -- if you know how to read paths or URLs from a custom `ClassLoader`, you can just override the scanning classpath with those paths or URLs. It's not a perfect solution, but it should work in the general case. (And anyway, if anyone creates a `ClassLoaderHandler`, I would hope they would contribute it upstream to ClassGraph so that others can benefit from it.) What do you think?

**Comment by lukehutch** [comment]
Disabling custom `ClassLoaderHandler` implementations (released in 4.4.12).

**Comment by GedMarc** [comment]
Unrelated : 
Gave it a lot of thought xD 
Decided to go back and open up the base module - it is much *much* cleaner, had to do the requires transitive route (which I think is defeating the purpose of the module system?) - but it comes with a 4 second boot penalty - runs at the same pace however xD

So I'm in this real pickle... 
A) Go for the clean pom and module-info files taking the penalty?
or go back to direct explicit definitions... ??

HELP :'( :'(

**Comment by lukehutch** [comment]
You have to require all your transitive dependencies? That does seem broken.

What incurs the extra 4s start time? Is that a scanning thing?

**Comment by GedMarc** [comment]
Naw, its 3 TreeSets of SPI's loading + hibernate + btm + hazelcast on 3 db's

The transitive dependencies to keep the module-info's small yes, otherwise you have to explicitly define them for that module :(

I have a few automatic named as well (btm jackson ;/) and transitive doesn't like it at all on jdk 10... so whoops dropping support for that one I guess.. ;/

**Comment by GedMarc** [comment]
nope scratch that, requires transitive doesn't open it up to the class, only declares it as required... weird its not happening in my IDE... ;/

[Compiler] Compilation failure
/ObjectMapperBinder.java:[9,36] package com.fasterxml.jackson.module.paramnames is not visible
  (package com.fasterxml.jackson.module.paramnames is declared in the unnamed module, but module com.fasterxml.jackson.module.paramnames does not read it)

**Comment by GedMarc** [comment]
thats a very interesting choice

**Comment by lukehutch** [comment]
You're not supposed to see the inner workings of anything, and a transitive dependency is considered an inner working. Most of the time, this is exactly what should be expected, and is not limiting. However, for a lot of authors of deeper or more intrusive libraries, this can be really limiting, yes. Strong encapsulation is the bane of a lot of library writers' existence.

**Comment by GedMarc** [comment]
I guess I did have it right xD 
Rolllllllback xD 

It is definitely a lot faster though

**Comment by lukehutch** [comment]
That's also part of the point. Java doesn't have to do as many costly security checks if there aren't many module dependencies...
