### ISSUE TITLE
getPackageName() in ClassInfo returns the class simple name, not the package

### ISSUE THREAD

**Issue by danielpoq** [classgraph/classgraph#276]
The method getPackageName() in ClassInfo returns **name.substring(name.lastIndexOf('.') + 1)**, that gives the substring from the last '.' char to the end of the name. https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#substring-int-

**Comment by lukehutch** [comment]
Copy-paste error -- thanks for reporting!

**Comment by lukehutch** [comment]
Released in 4.6.0. Thanks!
