### ISSUE TITLE
Calling `blacklistLibOrExtJars` without arguments causes an Exception

### ISSUE THREAD

**Issue by larsgrefer** [classgraph/classgraph#277]
Calling `blacklistLibOrExtJars()` without arguments throws `java.lang.IllegalArgumentException: Can only blacklist jars by leafname: /System/Library/Java/Extensions/MRJToolkit.jar` while `whitelistLibOrExtJars()` without arguments works fine.

**Comment by lukehutch** [comment]
Thanks, I should fix the error message, but lib and ext jars are already blacklisted by default. What behavior were you trying to achieve by calling it without arguments?

**Comment by larsgrefer** [comment]
I need to call `enableSystemPackages()` in order to find `com.sun.faces` and `javax.faces` classes but don't want to scan `rt.jar`

**Comment by larsgrefer** [comment]
This is my current workaround: https://github.com/joinfaces/joinfaces/pull/565/files#diff-1ad3611e83b5274657ca3924a729d319R92

**Comment by lukehutch** [comment]
Thanks for the fix!
