### ISSUE TITLE
Disable logging output

### ISSUE THREAD

**Issue by pedegie** [classgraph/classgraph#283]
Hello, is there any possibility for disabling log output on scanning?

**Comment by lukehutch** [comment]
Yes, don't call `.verbose()` before `.scan()`. Logging output is disabled by default.

**Comment by lukehutch** [comment]
@pedegie Did this work for you?

**Comment by lukehutch** [comment]
Closing this, as logging is disabled by default. If you are seeing verbose logging output, somewhere in your code (or code that uses ClassGraph) has called `new ClassGraph().verbose()`.

**Comment by pedegie** [comment]
Yep, thanks! :)
