### ISSUE TITLE
Error while scanning due to NoSuchMethodError on ByteBuffer (LATEST, 4.60?) 

### ISSUE THREAD

**Issue by bbougon** [classgraph/classgraph#284]
Hello,

I was unit testing my project when all of a sudden I had the error you may see into the logs attached.
Doing a downgrade to 4.4.12, the latest release on maven central fixed the scan.
FYI, I am building my project on a java 1.8 version (back compatiblity with jdk 9?).

thank you for your help

Bertrand

**Comment by lukehutch** [comment]
Hi Betrand, can you please attach the logs?

**Comment by bbougon** [comment]
[scan.log](https://github.com/classgraph/classgraph/files/2638242/scan.log)
Hi,

sorry about that.

Thanks

**Comment by bbougon** [comment]
Hi,

yes I followed a lot of thread from github to stackoverflow complaining about this issue that many are facing.

Thank you ;)

**Comment by lukehutch** [comment]
I filed an Eclipse bug on this to see if Eclipse can at least warn users about it:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=541804

I also just released the fix in 4.6.1. Can you please test this and let me know if it solves the problem for you? Thank you.

**Comment by bbougon** [comment]
I was on my way to do it, but the release is not available for now.
I will do it tonight back home.

**Comment by lukehutch** [comment]
Yes, Travis often has different behavior (and so does Maven vs. Eclipse). I also never saw the bug on my own system. Weird :)

**Comment by bbougon** [comment]
Hello Luke,

so I did try with the latest version it ran perfectly under idea and mvn command line as well.

Thank you for the fix ;)

**Comment by lukehutch** [comment]
Great, thanks for testing! FYI I just pushed out 4.6.2 which fixes a possible NPE on `ScanResult#close()`.
