### ISSUE TITLE
An error occurs when calling ScanResult.close().

### ISSUE THREAD

**Issue by ahamana** [classgraph/classgraph#285]
After upgrading from 4.4.12 to 4.6.1, an error occurs when calling ScanResult.close().
The stack trace in the "my-application-log.txt" wrote "nonapi.io.github.classgraph.fastzipfilereader.NestedJarHandler.close(NestedJarHandler.java:562)", so It seems that physicalZipFile is null.
\* The ClassGraph log is "classgraph-log.txt".

[logs.zip](https://github.com/classgraph/classgraph/files/2639222/logs.zip)

**Comment by lukehutch** [comment]
@ahamana Thanks for reporting! This should be fixed in 4.6.2.

**Comment by ahamana** [comment]
@lukehutch Many thanks for the quick fix.
