### ISSUE TITLE
Problem with jar file inside another shaded jar

### ISSUE THREAD

**Issue by vince-bickers** [classgraph/classgraph#289]
When a jar file doing class scanning is included in a maven shaded jar, the class scan fails:

2018-12-10T09:08:58.676+0000    ClassGraph      ---- Could not open jarfile: java.io.IOException: Invalid central directory signature: 0x8080014: <path_to_jar>

When the main class in the class scanning jar file is executed outside of the shaded jar, it works fine.

**Comment by lukehutch** [comment]
@vince-bickers Thanks for the report. Is there any chance you could please attach a jar that exhibits this problem, along with instructions on how to launch the scan?

The problem is in the new code that handles nested jar parsing, by reading the zipfile central directory directly. It will be very hard to debug what is going on without an actual file that triggers the bug. Thanks!

**Comment by vince-bickers** [comment]
Hi @lukehutch I can't give you a jar unfortunately as its not open source code. But the design is straightforward.

1. there is an initialisation jar that finds all implementations of an interface X using ClassGraph

2. The initialisation jar provides a number implementations of X. The main jar defines some additional ones as well. All implementations are then made available to the main jar by the initialisation jar. 

The main jar is built using the maven shade plugin, with the initialisation jar as a dependency.

I have a workaround for the time being, so its not urgent.

**Comment by lukehutch** [comment]
@vince-bickers Is it possible for you to create a minimal testcase that demonstrates the problem please, by following the same exact steps? Classgraph routinely scans thousands of shaded jars without problem, so something is unique about your jar.

The alternative would be for you to step through the code in `LogicalZipFile` in a debugger, comparing its behavior while parsing the central directory of the jarfile to the zipfile specification, and you can tell me where it is going wrong:

https://en.wikipedia.org/wiki/Zip_(file_format)

https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

**Comment by lukehutch** [comment]
@vince-bickers I tried scanning every jar in my Maven cache (`~/.m2`), consisting of ~2500 jars, and I couldn't trigger this bug, so really something must be unusual about the jar you are generating.

**Comment by lukehutch** [comment]
@vince-bickers I just released version 4.6.8 with a fix for a buffer underflow bug. It's possible that this is what was causing your issue too. Can you please see if the bug you were experiencing is fixed with this new version? Thanks.

**Comment by gitmotte** [comment]
I had just now the same error for a war - file including jars with version 4.6.10

> 2018-12-28T21:02:37.104+0100	ClassGraph	---- Could not open jarfile product.war!/WEB-INF/lib-provided/spring-boot-starter-tomcat-2.1.1.RELEASE.jar! : java.lang.IllegalArgumentException: Previous call to newInstance(key) returned null

**Comment by lukehutch** [comment]
@gimotte that is a different error, but it is caused by an earlier error that may or may not be the same as the originally reported problem. Can you please attach more of the log?

**Comment by gitmotte** [comment]
[scan.log](https://github.com/classgraph/classgraph/files/2715739/scan.log)

**Comment by lukehutch** [comment]
@vince-bickers I believe this was fixed in 4.6.8, so I decided to close this bug. Nevertheless please still test the latest released version, and I will reopen this bug if it is still not fixed. Thank you for the report!

**Comment by lukehutch** [comment]
@rvaidya Reopening then. I couldn't reproduce, since @vince-bickers' code is proprietary. Can you please generate a minimal testcase project and attach it here?

> Does this link help? EvanOxfeld/node-unzip#73

That's super interesting -- I might not be properly supporting some sort of zip extension or something. I don't understand the fix described in that comment though. Do you know what the impact of that code change would be?

**Comment by lukehutch** [comment]
Fixed by #304, many thanks to @rvaidya for this PR!

@vince-bickers This should be properly fixed now.

Released in 4.6.22.
