### ISSUE TITLE
Problem with jar file inside a war 

### ISSUE THREAD

**Issue by gitmotte** [classgraph/classgraph#296]
@gitmotte This is definitely unrelated, but I just checked a change into github master that may fix your issue. Can you please test this, and if it is not fixed, can you please open a new issue for this?

_Originally posted by @lukehutch in https://github.com/classgraph/classgraph/issues/289#issuecomment-450442558_

The error is the same but without the ending !/

> 2018-12-29T00:58:08.039+0100	ClassGraph	---- Could not open jarfile project.war!/WEB-INF/lib-provided/javax.el-api-3.0.0.jar : java.lang.IllegalArgumentException: Previous call to newInstance(key) returned null

**Comment by lukehutch** [comment]
Thanks -- can you please try again with latest github master -- I may have fixed the problem (and I improved logging, so it should be easier to see what's going on).

**Comment by gitmotte** [comment]
The fix works, thanks a lot!

**Comment by lukehutch** [comment]
Tha ms for confirming! I'll push out a change once I finish fixing a couple of other things.

By the way, since you tested this, how do you include a custom-built ClassGraph jar as a local dependency in a Maven project? I don't know how to do that :)

**Comment by lukehutch** [comment]
Released in 4.6.11. Thanks for the report!
