### ISSUE TITLE
Support for registering custom ClassLoaderHandlers or Support for Tomcat8+ WebAppClassLoader

### ISSUE THREAD

**Issue by JensRunge** [classgraph/classgraph#298]
In my Eclipse IDE I'm using the "Serve Modules without publishing" option to run the Tomcat.
In this scenario classgraph don't find any classes / jars from within the WebApp. 

The reason is, that classgraph is using the URLClassLoaderHandler instead of a customized ClassLoaderHandler which is also checking the Resources (org.apache.catalina.loader.WebappClassLoaderBase.getResources()). 
The Description for the overridden getURLs()-Method says, that the returned URLs-Array ist not complete and additional Resources accessed via .getResources().

Is it possible to add Support for registering custom ClassLoaderHandlers in the ClassLoaderHandlerRegistry or Support for Tomcat8+ WebAppClassLoader?

**Comment by lukehutch** [comment]
There used to be support for registering custom ClassLoaderHandlers, and it was removed for complex reasons. It could perhaps be added back, but in this case, since Tomcat is a common runtime environment, the right solution is to fix this for everybody by adding a ClassLoaderHandler to ClassGraph itself. Can you please submit a pull request for a ClassLoaderHandler that contains the required getResources() call?

**Comment by lukehutch** [comment]
@JensRunge OK, since that is the case I just committed a skeleton that you can work with. I have no idea if the code works or not :-)

**Comment by lukehutch** [comment]
@JensRunge I just released 4.6.13, which happens to have the skeleton code for `WebappClassLoaderBase` as part of the release (though it is still untested). This will make it easier for you to test whether this initial cut at a `ClassLoaderHandler` actually works or not. (I have no idea how to launch Tomcat projects, so I can't test it.)

**Comment by lukehutch** [comment]
@JensRunge I have another `ClassLoaderHandler` update to release -- would love to get Tomcat8+ support into this same release, if you have some time to test this.

**Comment by lukehutch** [comment]
@JensRunge : @GedMarc sent me a Tomcat example project that I was able to use to get this (I hope) fully working. Released in 4.6.27. Please comment here if it is not working for you, and I'll reopen the bug.

**Comment by JensRunge** [comment]
Today I've found some time to deal with the bug, setted up a test project an was wondering that I can't get the error again. Then I read all the mails about your commits and recocknized that yuo've allready fixed the bug. It works perfectly now. Thank you very much.
