### ISSUE TITLE
EquinoxClassLoaderHandler does not  lookup bundle fragments

### ISSUE THREAD

**Issue by eddi-weiss** [classgraph/classgraph#301]
When using the scanner in PDE, the bundle fragment classpaths  are not scanned. The equinox ClasspathManager provides field "fragments" of type FragmentClasspath[] and FragmentClasspath provides field "entries" of type ClasspathEntry.  I expect that all classpath entries of all fragments  are added to the "classpathOrderOut" list.
I am using eclipse 2018-09 and java 8.

**Comment by eddi-weiss** [comment]
I provided a fix:
https://github.com/classgraph/classgraph/pull/302

**Comment by lukehutch** [comment]
@eddi-weiss many thanks for the report and the pull request! I'm waiting on feedback on a couple of other bug reports before I push out another release.

**Comment by lukehutch** [comment]
Released in 4.6.19. Thanks again!
