### ISSUE TITLE
Classes missed in PackageInfo.getClassListRecursive?

### ISSUE THREAD

**Issue by GedMarc** [classgraph/classgraph#303]
Got a bit of a funny - 
Not sure if some of my parameters are incorrect,

Getting different results between getPackageInfo().getClassInfoRecursive and getAllClasses()

[packageinfolisting.zip](https://github.com/classgraph/classgraph/files/2803872/packageinfolisting.zip)

Thanks!

**Comment by lukehutch** [comment]
@GedMarc Turns out I forgot to finish implementing the "recursive" part of `getClassInfoRecursive()` :-D

Fixed in 4.6.21. Thanks!

**Comment by GedMarc** [comment]
I've got this strange scenario where I keep the ScanResult alive for the duration of the app xD
During an app restart I go through a couple of "pre-destroys" to shut down the scan result - I haven't felt/seen any leaks, but can't say I've actually tested it thoroughly enough to be sure -
It's definitely going like a Boeing and I honestly couldn't be happier with this library!

My "OpenAPI for Java" using this is really coming smoothly!

**Comment by lukehutch** [comment]
@GedMarc Glad it's working well for you! You have been instrumental in getting ClassGraph really polished and bug-free over the last few months. Thanks again!
