### ISSUE TITLE
An error occurs when calling nonapi.io.github.classgraph.concurrency.SingletonMap.get().

### ISSUE THREAD

**Issue by ahamana** [classgraph/classgraph#317]
After upgrading from 4.6.32 to 4.8.0, an error occurs when calling nonapi.io.github.classgraph.concurrency.SingletonMap.get().
I tried obtaining ClassGraph log with verbose() method, but an error occurred(its stacktrace is in "verbose-error.txt") which is related with the issue(#316).
So, I put the original stacktrace(original-stacktrace.txt) in the attached logs.zip.
Could you please see it?

[logs.zip](https://github.com/classgraph/classgraph/files/2865138/logs.zip)

**Comment by lukehutch** [comment]
@ahamana This should be fixed in master. Could you test the master version, please?

**Comment by lukehutch** [comment]
Should be working -- released in 4.8.1. Thanks for the bug report!

**Comment by ahamana** [comment]
@lukehutch It works fine. Many thanks for fixing the issue quickly.

**Comment by lukehutch** [comment]
@ahamana Great, thanks for testing and reporting back!
