### ISSUE TITLE
Resource path resolve error

### ISSUE THREAD

**Issue by chinamcafee** [classgraph/classgraph#325]
When I ran a multi-module maven project，resource URL was resolved as a jarfile path as follws:
![image](https://user-images.githubusercontent.com/3439961/53547398-e6b90200-3b69-11e9-83e5-275a3e1dbcba.png)
It's not a correct jarfile path, and what I expected path is a file path. 
My project structure as shown below：
![image](https://user-images.githubusercontent.com/3439961/53547628-7fe81880-3b6a-11e9-99dd-ddb805c568fe.png)

**Comment by lukehutch** [comment]
@chinamcafee where in the hierarchy is your `conf/command.properties` file?

**Comment by lukehutch** [comment]
@chinamcafee I just committed a probable fix for this problem. Can you please try the git master version?

**Comment by lukehutch** [comment]
I'm pretty sure this should be fixed. Released in 4.8.9, please let me know if this doesn't fix the issue for you and I'll reopen the bug. Thanks!
