### ISSUE TITLE
How to compare a parameter type with a class

### ISSUE THREAD

**Issue by xaviarias** [classgraph/classgraph#326]
Hi, I've been trying this in many ways but the API is very restrictive:

```java
var paramInfo = methodInfo.getParameterInfo()[0];

if (paramInfo.getTypeDescriptor().equalsIgnoringTypeParams(/* ??? */)) { ... }
```

What to put in the question marks to know if a parameter is of a specific type?

Thanks

**Comment by lukehutch** [comment]
I need to comment this better, and provide example code. The returned type descriptor object will have a different concrete subtype depending on whether the parameter is a simple type, or a parameterized generic type, or an array type, etc., and each of those type signature classes has different methods for getting the parts of the type (eg. the element type of an array type, or the base type and type parameters of a parameterized generic type). 

So you need some instanceof tests and casting, followed by method calls into the type signature subclass, to perform the type comparison you need.

The possible concrete subtypes of a type signature are listed in the documentation and Javadoc, but you could try this with a few examples.

Sorry that this is a bit vague! Let me know if this is not enough to get you started for now. I'll try to write some better docs soon.

**Comment by xaviarias** [comment]
Thanks @lukehutch, I was looking for something more straight forward so I ended up loading the class and method to obtain the parameter types. With a good scanning filter, is not too bad to load some extra methods to filter by parameter type.

**Comment by lukehutch** [comment]
I added more info on how to use the type signature classes here:

https://github.com/classgraph/classgraph/wiki/API:-TypeSignature

Let me know if anything is not clear.

**Comment by lukehutch** [comment]
> I was looking for something more straight forward so I ended up loading the class and method to obtain the parameter types. With a good scanning filter, is not too bad to load some extra methods to filter by parameter type.

@xaviarias the `loadClass()` methods do not initialize the class when the class is loaded, so what you're doing should be pretty fast. However check out the new documentation anyway (see previous comment), it is better to only load classes if you actually need them.

**Comment by xaviarias** [comment]
Thanks so much @lukehutch, your documentation is very clear. As you said is more work, so for my use case I think is ok to `loadClass`, and also because is only done once.
