### ISSUE TITLE
How to know if a method is void?

### ISSUE THREAD

**Issue by xaviarias** [classgraph/classgraph#327]
Hi, from the `MethodInfo` API I cannot find any reference to the return type, is it possible to obtain it?

**Comment by lukehutch** [comment]
Yes, check the documentation:

https://github.com/classgraph/classgraph/wiki/API:-TypeSignature#example-usage

https://github.com/classgraph/classgraph/wiki/API:-TypeSignature#basetypesignature

**Comment by lukehutch** [comment]
PS @xaviarias let me know if the above needs further clarification. Also, feel free to ask questions on the ClassGraph Gitter page:

https://gitter.im/classgraph/Lobby
