### ISSUE TITLE
Unable to scan classes in rt.jar using enableSystemJarsAndModules()

### ISSUE THREAD

**Issue by richardbelisle** [classgraph/classgraph#332]
Scanning appears to be disabled for `rt.jar`.

[verbose.log](https://github.com/classgraph/classgraph/files/2978849/verbose.log)

**Comment by lukehutch** [comment]
There was a Windows-specific bug here, to do with Windows using `\` as a path separator. Should be fixed now, released in 4.8.15. Thanks for the report!
