### ISSUE TITLE
potential for ConcurrentModificationException in AnnotationInfoList#getIndirectAnnotations

### ISSUE THREAD

**Issue by mer2github** [classgraph/classgraph#334]
AnnotationInfoList.getIndirectAnnotations uses the static constant EMPTY_LIST when there are no direct class annotations. it then sorts the constant:

    final AnnotationInfoList directAnnotationInfoSorted = directAnnotationInfo == null
            ? AnnotationInfoList.EMPTY_LIST
            : new AnnotationInfoList(directAnnotationInfo);
    Collections.sort(directAnnotationInfoSorted);

ArrayList.sort checks modCount throwing if it changes during the call. at the end sort bumps the modCount by 1. at start up we hit the EMPTY_LIST case multiple times across 2 threads. if we are unlucky 2 of these will happen concurrently causing the exception to be thrown.

**Comment by lukehutch** [comment]
@mer2github thanks for the report. Fixed and released in 4.8.21.
