### ISSUE TITLE
Add MethodInfo.isSynthetic

### ISSUE THREAD

**Issue by jodastephen** [classgraph/classgraph#337]
Thanks for this library!

`ClassInfo` has an `isSynthetic()` method, but `MethodInfo` does not. For my immediate needs, I dug into the source code to find the relevant modifier check (as it isn't on `java.lang.reflect.Modifier` either), But it would be great if the method was added to `MethodInfo` since it is already on `ClassInfo`.

**Comment by lukehutch** [comment]
Thanks for pointing out the omission. Added and released in 4.8.24:

https://github.com/classgraph/classgraph/releases/tag/classgraph-4.8.24

**Comment by lukehutch** [comment]
PS @jodastephen I'm glad it's working for you -- what projects are you using this with?

**Comment by jodastephen** [comment]
Its used in day job projects. Today I was using it to analyse the entire codebase to find uses of Joda-Beans.
