### ISSUE TITLE
Can not find classes with methods annotation in "test" package

### ISSUE THREAD

**Issue by danilohrsilva** [classgraph/classgraph#357]
In my project I have the following package structure:
<root>
 |-- src
 |   |-- main
 |   |   |-- java
 |   |   |   |-- com.xyz
 |   |   |   |   |-- controller
 |   |   |   |   |-- config
 |   |-- test
 |   |   |-- java
 |   |   |   |-- com.xyz
 |   |   |   |   |-- controller

In src.main.java.com.xyz.controller there is one class with one method annotated with "@Feature" annotation.
In src.test.java.com.xyz.controller there is one class with one method annotated with "@Scenario" annotation.

In src.main.java.com.xyz.config there is a class with the following method implementation:
`
        try (ScanResult scanResult = new ClassGraph().enableAllInfo().scan()) {
            final ClassInfoList featuresClassInfoList = scanResult
                .getClassesWithMethodAnnotation(Feature.class.getName());
            final ClassInfoList scenariosClassInfoList = scanResult
                .getClassesWithMethodAnnotation(Scenario.class.getName());
            System.out.println("featuresClassInfoList: " + featuresClassInfoList.size());
            System.out.println("scenariosClassInfoList: " + scenariosClassInfoList.size());
        }
`
The output of this code is:
featuresClassInfoList: 1
scenariosClassInfoList: 0

I'm not sure if I should be able to list my methods in "src.test.java.com.xyz.controller" package running the code from "src.main.java.com.xyz.config".
Is there another way to implement that? Or should it work?

Thanks

**Comment by lukehutch** [comment]
Hi, almost certainly the classes in `src/test` do not get integrated into the final build (usually if they do, it is a misconfiguration). You are doing runtime scanning, so the classes in `src/test` are nowhere to be found on the classpath.

The solution is to do compiletime scanning, not runtime scanning. You can do that as simply as running the scan from a unit test in `src/test` itself. But there are more exotic ways to do this:

https://github.com/classgraph/classgraph/wiki/Build-Time-Scanning

Please let me know if one of these suggestions resolves the issue for you.

**Comment by danilohrsilva** [comment]
Hi!
@lukehutch running the code from `src/test`, it worked.
Thanks!!

**Comment by lukehutch** [comment]
Great, thanks for confirming!
