### ISSUE TITLE
NPE in PackageInfo.getClassListRecursive

### ISSUE THREAD

**Issue by zyxist** [classgraph/classgraph#366]
I'm writing a unit test that ensures my classgraph scanner has certain packages blacklisted, so that they are not included in the scan result. The code looks like this:

```java
for (var roguePackage : roguePackages) {
    var packageInfo = classpathScanResult.getPackageInfo(roguePackage);
    if (null != packageInfo && !packageInfo.getClassInfoRecursive().isEmpty()) {
        detectedPackages.add(roguePackage);
    }
}
```
However, I get a `NullPointerException` from `getClassInfoRecursive()` method:

```
java.lang.NullPointerException
	at io.github.classgraph.PackageInfo.obtainClassInfoRecursive(PackageInfo.java:226)
	at io.github.classgraph.PackageInfo.getClassInfoRecursive(PackageInfo.java:239)
	at myproject.discovery.impl.UniversalDiscovererImplTest$RoguePackageDetector.discoverStuff(UniversalDiscovererImplTest.java:176)
```

I tracked the issue with the debugger and I think the root cause is pretty simple. Inside `PackageInfo`, we have:

```java
    private void obtainClassInfoRecursive(Set<ClassInfo> reachableClassInfo) {
        reachableClassInfo.addAll(this.memberClassNameToClassInfo.values());
```

The problem is that `this.memberClassNameToClassInfo` can be **null**, because it is created lazily once we call `addClassInfo()`. Apparently, ClassGraph can create `PackageInfo` objects without adding any `ClassInfo` to them, but the recursive code ignores that. An extra `if` for this corner case should solve the problem.

Tested on *4.8.44* and *4.8.27*.

**Comment by lukehutch** [comment]
Thank you for reporting this and tracking down the problem. There were a couple of other places too that needed the same null check. I didn't know anybody was actually using `PackageInfo` yet :-)  Fixed and released in 4.8.45.
