### ISSUE TITLE
classgraph-4.8.48 have not been published in Maven yet.

### ISSUE THREAD

**Issue by ahamana** [classgraph/classgraph#369]
classgraph-4.8.48 have not been published in Maven yet.
![maven-screen](https://user-images.githubusercontent.com/21101083/65286565-fd14c280-db7a-11e9-82b6-7ce98c2fd6c8.png)

Could you please republish classgraph-4.8.48 to Maven?

**Comment by lukehutch** [comment]
Unfortunately there is a problem with publishing to Sonatype, and I don't know how to fix it...

https://issues.sonatype.org/plugins/servlet/mobile#issue/OSSRH-51693

Any ideas?

**Comment by ahamana** [comment]
@lukehutch I don't have any ideas, it cannot be helped.

**Comment by lukehutch** [comment]
After a very long time trying to solve issues with both Sonatype and BinTray, Maven deployment is fixed again, and ClassGraph version 4.8.48 should be in Maven Central soon. Sorry for the delay.
