### ISSUE TITLE
Whitelisting classes in folder

### ISSUE THREAD

**Issue by ulrikls** [classgraph/classgraph#371]
I'm trying to find all classes implementing one of a list of interfaces (either directly or through a superclass). I'm scanning class files in a list of directories (not jars), as the output of the scan is supposed to go into the jar that I'm building.

The code below sometimes throw OutOfMemoryError, because I have a lot of classes, even with the package whitelist:
```java
List<URI> classpath = new ArrayList<>(); // Runtime classpath
// some code to populate classpath
URI scanPath = ... // URI of the classes I'm interested in.
classpath.add(scanPath);

Set<String> foundClasses = new HashSet<>();
try (ScanResult scanResult = new ClassGraph().enableClassInfo().whitelistPackages(PACKAGES).overrideClasspath(CLASSPATH).scan()) {
  for (String typeToFind : INTERFACES) {
    foundClasses.addAll(scanResult.getClassesImplementing(typeToFind)
        .filter(cls -> !cls.isInterface() && !cls.isAbstract() && scanPath.equals(cls.getClasspathElementURI()))
        .getNames());
  }
}
```

I'm thinking about splitting the scan into two, first to find the list of classes in `scanPath`, and second like the above, but using the class list as whitelist. The list can, however, be very long.

Is this the correct approach? Is it possible to whitelist classes based on path, like what I'm doing when filtering on `classpathElementURI`? I've tried with `whitelistPaths` and `whitelistClasspathElementsContainingResourcePath` but they seem to be doing something else.

**Comment by lukehutch** [comment]
Hi @ulrikls, the first thing that jumps out is that `.overrideClasspath(CLASSPATH)` followed by filtering for `scanPath.equals(cls.getClasspathElementURI())` reduces to simply `.overrideClasspath(scanPath)` (and then you don't need the filter test). Only scan what you actually need to scan, which is the path you're interested in.

Does that solve the `OutOfMemoryError` for you?

**Comment by ulrikls** [comment]
Well, that doesn't give the expected result. I'm interested in all classes implementing interface `I`. Let's say I have `class A extends B`, and `class B implements I`. Only `A` is on `scanPath`, but `B` and `I` are on `classpath`. If `B` is not included in the scan it won't find `A`, at least that's my experience.

**Comment by lukehutch** [comment]
OK, I see what you're saying. ClassGraph extends scanning "upwards" (to superclasses, interfaces, annotations, etc.), outside whitelisted packages, if the superclass/interface/annotation is not in a whitelisted package. But if those classes are not only not in whitelisted packages, but not in the classpath at all, then ClassGraph is not able to scan them at all, and so cannot trace more than one link in the upwards direction, and in the example you gave (which requires following two links to find the relationship between `A` and `I`), then yes, this will not be detected.

What I suggest doing is scanning one classpath element at a time in a loop, and for each separate `ScanResult`, iterating through all classes and outputting a set of graph edges linking each interface implemented by the class, to the class (i.e. the inverse of the `implements` direction). Also store a `HashMap` of the names of all classes that are not interfaces or abstract. Then for all interfaces you are interested in, find the transitive closure through this graph from the interface name to the names of all classes that are also in the non-interface, non-abstract class name set.

Finding this transitive closure is what ClassGraph does internally, when you ask for all classes implementing a given interface -- but if you can't fit the class graph in memory for your entire large classpath, you'll have to do this manually, one classpath element at a time, then allow the GC to collect the previous `ScanResult` (by `close()`ing it) before running the scan on the next classpath element.

If the transitive closure idea is not clear, let me know, and I'll give some pseudocode or something.

**Comment by ulrikls** [comment]
Thank you for the quick replies. I'm not quite sure I understand your suggestion, though. Currently I'm at this solution, which so far hasn't failed with OutOfMemoryError:
```java
List<URI> runClasspath = new ArrayList<>(); // Runtime classpath
// some code to populate classpath
URI scanPath = ... // URI of the classes I'm interested in.
runClasspath.add(scanPath);

String[] classesToScan;
try (ScanResult scanResult = new ClassGraph().enableClassInfo().overrideClasspath(scanPath).scan()) {
  classesToScan = scanResult.getAllClasses().getNames().toArray(new String[0]);
}

Set<String> foundClasses = new HashSet<>();
try (ScanResult scanResult = new ClassGraph().enableClassInfo().whitelistClasses(classesToScan).overrideClasspath(runClasspath).scan()) {
  for (String typeToFind : INTERFACES) {
    foundClasses.addAll(scanResult.getClassesImplementing(typeToFind)
        .filter(cls -> !cls.isInterface() && !cls.isAbstract())
        .getNames());
  }
}
```

As `scanPath` only contains the classes I'm interested in I've removed the package whitelist. Also `scanPath` is a lot smaller than `runClasspath`, so I think this is a good enough solution. If I run into OutOfMemoryError again I could split the last scan into chunks as suggested in #338.

My original question was just whether it's possible to combine the two scans into one using some sort of whitelisting, but I guess that's not the case.

**Comment by lukehutch** [comment]
> My original question was just whether it's possible to combine the two scans into one using some sort of whitelisting, but I guess that's not the case.

Unfortunately no, when the scan is performed, ClassGraph has no idea what sorts of queries you plan to run using the `ScanResult`, so you can only limit the size of the graph of `ClassInfo` objects if you can come up with a series of pre-filtering conditions that limit the size as closely as possible to the set of classes you actually want to work with in the `ScanResult` (e.g. whitelisting, as you have done).

The two-step solution you have come up with has the main benefit of allowing you to specify classpath roots in `scanPath`, and all classes in all sub-packages will be added to `classesToScan`. Otherwise if you already know the classes you want to scan, you can skip the first scan entirely, and just whitelist those classes directly. If you can't determine which classes you want to scan, but you can specify the classpath elements are all contained in (and if that set of classpath elements containing the target classes is much smaller than the entire classpath), then yes, you need a two-step scanning solution as you have implemented, and this is probably about the best you can do.

Actually come to think of it, there is one way you might be able to do this in a single scan, using the method you asked about, `whitelistClasspathElementsContainingResourcePath()`: The goal of this method is to whitelist only classpath elements that contain a specific file, so you could mark classpath elements for scanning by dropping some sort of uniquely named file into the jars you want to scan, at a known location, then whitelist jars that contain a file with that path. However I don't know off the top of my head if that would preclude jars that *don't* contain that file from "upwards extension" of scanning outside the whitelist, as I described previously -- I'd have to look closely at what stage of scanning classpath elements are excluded from consideration by this method, and it may or may not work for your usecase.

The two-stage scan shouldn't be too time consuming though, so it's not a bad solution.

If you do run out of RAM again, this is the sort of thing I was suggesting:

```java
import java.net.URI;
import java.util.ArrayDeque;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Queue;
import java.util.Set;

import io.github.classgraph.ClassGraph;
import io.github.classgraph.ClassInfo;
import io.github.classgraph.ScanResult;

public class LowRAMScanningMain {

    /** Add a key/value pair to a key-to-set map. */
    private static <K, V> void addToMultimap(K key, V val, Map<K, Set<V>> map) {
        Set<V> set = map.get(key);
        if (set == null) {
            map.put(key, set = new HashSet<V>());
        }
        set.add(val);
    }

    /**
     * Perform breadth-first search from interface to implementors, returning
     * implementors that are concrete standard classes.
     */
    private static Set<String> allImplementingClasses(String ifaceName,
            Map<String, Set<String>> ifaceToImplementors,
            Set<String> allConcreteStandardClasses) {
        Set<String> result = new HashSet<>();
        Set<String> visited = new HashSet<>();
        Queue<String> queue = new ArrayDeque<>();
        queue.add(ifaceName);
        while (!queue.isEmpty()) {
            String head = queue.remove();
            if (visited.add(head)) {
                if (allConcreteStandardClasses.contains(head)) {
                    result.add(head);
                }
                Set<String> implementors = ifaceToImplementors.get(head);
                if (implementors != null) {
                    queue.addAll(implementors);
                }
            }
        }
        return result;
    }

    public static void main(String[] args) {
        Map<String, Set<String>> ifaceToImplementors = new HashMap<>();
        Set<String> allConcreteStandardClasses = new HashSet<>();
        // Scan each classpath element separately 
        for (URI classpathURI : new ClassGraph().getClasspathURIs()) {
            try (ScanResult scanResult = new ClassGraph()
                    .overrideClasspath(classpathURI).enableClassInfo().scan()) {
                System.out.println("Scanning " + classpathURI);
                for (ClassInfo ci : scanResult.getAllClasses()) {
                    for (ClassInfo iface : ci.getInterfaces()) {
                        // Store all interface -> implementor links
                        addToMultimap(iface.getName(), ci.getName(),
                                ifaceToImplementors);
                    }
                    if (!ci.isAbstract() && ci.isStandardClass()) {
                        // Remember concrete non-interface classes
                        allConcreteStandardClasses.add(ci.getName());
                    }
                }
            }
        }

        // Example usage
        for (String ifaceName : ifaceToImplementors.keySet()) {
            System.out.println(
                    ifaceName + " -> " + allImplementingClasses(ifaceName,
                            ifaceToImplementors, allConcreteStandardClasses));
        }
    }

}
```

**Comment by lukehutch** [comment]
Also don't forget to use `.ignoreClassVisibility()` if you want to detect inheritance paths that traverse non-public classes.

**Comment by lukehutch** [comment]
@ulrikls ClassGraph 4.8.64 consumes dramatically less RAM (and virtual memory space) than before. Please see if this resolves your OOM issue.

**Comment by ulrikls** [comment]
@lukehutch thank you for working hard on making ClassGraph great. I've been using the two-step solution for a while now as part of our build pipeline. We get occasional OOM errors, but they don't seem to be related to ClassGraph.
I've just updated to GlassGraph 4.8.64 yesterday, and haven't seen any OOM issues so far.

**Comment by lukehutch** [comment]
@ulrikls Great, thanks for trying it out and letting me know!
