### ISSUE TITLE
Can't scan classes in Windows development environment

### ISSUE THREAD

**Issue by qwqeq** [classgraph/classgraph#388]
Hello, I use it to load classes in a package. But I found that it didn't load in the Windows environment, so I wrote a demo project and packaged it into a jar file, and I couldn't run the jar file in the Windows environment to get the effect I wanted, and then I ran the file in the Mac environment to get the effect I wanted. Here are the logs in the Windows environment.
` 2019-11-28T19:19:32.119+0800    ClassGraph      -- Opening jar: D:/demo/target/demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-context-5.2.1.RELEASE.jar 
 2019-11-28T19:19:32.119+0800    ClassGraph      ---- Could not open jarfile D:/demo/target/demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-context-5.2.1.RELEASE.jar : java.io.IOException: Could not get parent logical zipfile D:/demo/target/demo-0.0.1-SNAPSHOT.jar : nonapi.io.github.classgraph.concurrency.SingletonMap$NullSingletonException: newInstance returned null for key D:/demo/target/demo-0.0.1-SNAPSHOT.jar`
The demo project is [here](https://github.com/qwqeq/demo).

**Comment by qwqeq** [comment]
JDK version is 11.

**Comment by qwqeq** [comment]
When I used version 4.8.55, I was able to scan classes normally.

**Comment by lukehutch** [comment]
Thanks for the report. I added a new URL handling scheme, and Windows paths `C:/x/y` were being treated as URLs. The fix requires URL schemes to consist of at least two characters, so that Windows drives are not treated as URLs. I'll try to push out a release later today, since a couple of other things broke in 4.8.56 too.

**Comment by lukehutch** [comment]
Fixed and released in 4.8.57. Sorry for the trouble!

**Comment by lukehutch** [comment]
PS I only run Linux, but I added GitHub Actions build/test integration for Windows and Mac OS X, so hopefully Windows doesn't break again.
