### ISSUE TITLE
Scanning is broken on Windows

### ISSUE THREAD

**Issue by remal** [classgraph/classgraph#390]
File paths start with `C:/` on Windows. `JarUtils.URL_SCHEME_PATTERN` matches such paths and ClassGraph treats simple files as URLs. I suppose you should change the pattern to `[a-zA-Z][a-zA-Z0-9+-.]+[:].*` (`+` instead of `*`)

[Logs](https://github.com/classgraph/classgraph/files/3902670/log.txt) have been attached. As you can see all JARs and directories are skipped.

**Comment by lukehutch** [comment]
Yes, sorry, 4.8.56 is a [brown paper bag release](http://catb.org/jargon/html/B/brown-paper-bag-bug.html). This is a dup of #388, which is fixed, but I'm also fixing a performance regression. Will push out a new release soon. Sorry about that!

**Comment by lukehutch** [comment]
Fixed and released in 4.8.57.

**Comment by lukehutch** [comment]
PS I only run Linux, but I added GitHub Actions build/test integration for Windows and Mac OS X, so hopefully Windows doesn't break again!
