### ISSUE TITLE
Failed resolution of: Ljava/lang/management/ManagementFactory;

### ISSUE THREAD

**Issue by CreeJee** [classgraph/classgraph#404]
when android enviorment in kotlin throws error in [ModulePathInfo.java](https://github.com/classgraph/classgraph/blob/master/src/main/java/io/github/classgraph/ModulePathInfo.java)

    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;
        at io.github.classgraph.ModulePathInfo.<init>(ModulePathInfo.java:131)
        at nonapi.io.github.classgraph.scanspec.ScanSpec.<init>(ScanSpec.java:224)
        at io.github.classgraph.ClassGraph.<init>(ClassGraph.java:63)

**Comment by lukehutch** [comment]
I think you're missing a `requires` for the module containing that class (in your module descriptor). (Unfortunately there's no easy way to tell the name of the module that contains a given class.)

If not, please create a minimal test project.

**Comment by lukehutch** [comment]
Actually it looks like the module names are in the javadoc.

https://docs.oracle.com/javase/9/docs/api/java/lang/management/ManagementFactory.html

So you need `requires java.management;`

**Comment by lukehutch** [comment]
Another possibility is that you are deploying in a runtime environment that does not contain the required module.

**Comment by CreeJee** [comment]
wow thanks, I'll do it

**Comment by lukehutch** [comment]
Oh, you said Android, I didn't notice that. Android doesn't even support JPMS, so my advice about modules was wrong. Android doesn't even have this API:

https://stackoverflow.com/a/19595885/3950982

I'll take a look at where ClassGraph is depending on this when I get home. 

Be aware though that ClassGraph doesn't work for runtime scanning on Android, only for build time scanning:

https://github.com/classgraph/classgraph/wiki/Build-Time-Scanning

**Comment by lukehutch** [comment]
@CreeJee I made ClassGraph only access `java.lang.management.ManagementFactory` through reflection, so it will no longer fail at runtime on a system that does not contain this package. Please upgrade to 4.8.65, and let me know if there are any other issues in the Android build environment. Also notice the link to build time scanning in the previous comment. Thanks!
