### ISSUE TITLE
woodstox-core dependency crashes the project compilation with a reference to FastClasspathScanner

### ISSUE THREAD

**Issue by dontsu** [classgraph/classgraph#410]
I am running an AEM project on jdk11. 
Getting the following exception when I add the dependency to my AEM app module:

`[ERROR] Failed to execute goal org.apache.jackrabbit:filevault-package-maven-plugin:1.0.3:analyze-classes (default-analyze-classes) on project test.ui.apps: Error while analysing imports: Failed to scan the classpath: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unknown constant pool tag [I@26adb2bb in classfile module-info.class (element size unknown, cannot continue reading class. Please report this on the FastClasspathScanner GitHub page. -> [Help 1]`

Details on it:
`Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unknown constant pool tag [I@1b29c68f in classfile module-info.class (element size unknown, cannot continue reading class. Please report this on the FastClasspathScanner GitHub page.
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1408)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1439)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1462)
	at org.apache.jackrabbit.filevault.maven.packaging.impl.ImportPackageBuilder.scanClassPath(ImportPackageBuilder.java:336)
`

This is the dependency I try to add:
```
<!-- https://mvnrepository.com/artifact/com.fasterxml.woodstox/woodstox-core -->
<dependency>
    <groupId>com.fasterxml.woodstox</groupId>
    <artifactId>woodstox-core</artifactId>
    <version>6.1.1</version>
</dependency>

```
Any idea what is wrong? Project in confidential and I can't share the repo.

**Comment by lukehutch** [comment]
Unfortunately FastClasspathScanner is obsolete and no longer maintained, and was replaced around three years ago by ClassGraph. You will have to port your code or the code of your dependencies to ClassGraph to fix this.

https://github.com/classgraph/classgraph/wiki/Porting-FastClasspathScanner-code-to-ClassGraph

FastClasspathScanner does not support JDK9+ module descriptors, hence the exception you're seeing.

It looks like Woodstox depends upon Jackrabbit, which depends on FastClasspathScanner. You should report a bug upstream to these projects.

**Comment by dontsu** [comment]
Thanks @lukehutch for clarification. Will do that.

Regards,
Diana
