### ISSUE TITLE
Expose the class file major and minor version number in ClassInfo

### ISSUE THREAD

**Issue by adelel1** [classgraph/classgraph#418]
Hello,
We (Corda) have a requirement where we need to check the class file version we are reading. We are already using ClassGraph but unfortunately ClassGraph swallows the major and minor version number when it creates a ClassFile. Instead could this be stored and made accessible in ClassInfo? It would save us having to reread the class header.
Thanks,

**Comment by lukehutch** [comment]
Good suggestion -- added:

* `ClassInfo#getClassfileMinorVersion()`
* `ClassInfo#getClassfileMajorVersion()`

Released in 4.8.71.

**Comment by adelel1** [comment]
Thanks for the quick response!

**Comment by lukehutch** [comment]
You're welcome!
