### ISSUE TITLE
When used in gradle plugin, it throws Unable to load class 'io.github.classgraph.ClassGraph'

### ISSUE THREAD

**Issue by RoRoche** [classgraph/classgraph#427]
Hi,

I'm using the ClassGraph library inside a custom gradle plugin: https://github.com/RoRoche/plantuml-gradle-plugin/tree/feature/using_classgraph

It's OK during unit testing and while releasing into local Maven and used in another project.

But since it has been released to gradle plugin portal (https://plugins.gradle.org/plugin/com.github.roroche.plantuml), when using inside another project (https://github.com/RoRoche/eo-plantuml-builder), when running my `buildClassDiagram` task, it throws

```shell
* What went wrong:
Execution failed for task ':buildClassDiagram'.
> Lio/github/classgraph/ClassGraph;
```

Any idea of what's going wrong? Gradle plugin packaging?

**Comment by lukehutch** [comment]
Looks like a nice plugin. Are you using ClassGraph just to read class metadata, or are you also using its ability to export .dot (GraphViz) files?

Honestly I know nothing about Gradle. Off the top of my head, are you running this as a modular (JPMS) project? There might be an issue with needing to [add a `requires` or something](https://github.com/classgraph/classgraph/wiki#use-as-a-module).

Otherwise, try printing out the `java.class.path` property (or the Gradle path, if it has its own classpath? No idea) from within eo-plantuml-builder, and see if you can find the ClassGraph classpath entry there.

**Comment by RoRoche** [comment]
Hum, I did not use Java 9 modules :S
Maybe my plugin code structure is wrong and I have to define a module?
What kind of configuration do you suggest me?

**Comment by lukehutch** [comment]
No, I would say definitely stay away from modules for now. (At least in my experience, they only complicate things. But some people love them.)

If you're running the code on JDK11+, Try running the code on JDK 8 (if it compiles for JDK 8). If it works, it might be that your plugin is loading some classes as modules, even if your code is not.

However, I also suggested looking at `java.class.path` from whichever jar is failing to find ClassGraph. This will help you track down the problem.

Gradle will have some sort of classpath mechanism, and it seems that it is not set up right, or that the correct classpath is not being given to the plugins.

**Comment by RoRoche** [comment]
Still having the issue when compiling the plugin with JDK8 :'(

**Comment by lukehutch** [comment]
Can you please put together a minimal testcase project, and attach it here so I can take a look, with instructions about how to build and run the project?

**Comment by thc202** [comment]
When that happens you should run Gradle with `--stacktrace`, as it might help diagnose the problem, the error does not seem caused by ClassGraph:
```
Caused by: java.lang.NoClassDefFoundError: Lio/github/classgraph/ClassGraph;
        at ch.ifocusit.plantuml.classdiagram.ClassDiagramBuilder.readFields(ClassDiagramBuilder.java:346)
        at ch.ifocusit.plantuml.classdiagram.ClassDiagramBuilder.lambda$createJavaClass$20(ClassDiagramBuilder.java:313)
        at ch.ifocusit.plantuml.classdiagram.ClassDiagramBuilder.createJavaClass(ClassDiagramBuilder.java:313)
        at ch.ifocusit.plantuml.classdiagram.ClassDiagramBuilder.lambda$readClasses$19(ClassDiagramBuilder.java:305)
        at ch.ifocusit.plantuml.classdiagram.ClassDiagramBuilder.readClasses(ClassDiagramBuilder.java:305)
        at ch.ifocusit.plantuml.classdiagram.ClassDiagramBuilder.build(ClassDiagramBuilder.java:153)
        at com.github.roroche.plantuml.diagrams.ClassDiagram.<init>(ClassDiagram.kt:28)
        at com.github.roroche.plantuml.diagrams.ClassDiagram.<init>(ClassDiagram.kt:37)
```

In the plugin you are not passing/using the compile classpath of the project just the classes the project has (`BuildClassDiagramTask#getClassLoader()`) so the classes of the dependencies (in this case ClassGraph) will not be found.
If you change `ClsInPackage.kt` in `eo-plantuml-builder` to not use ClassGraph it will generate the diagram.

**Comment by RoRoche** [comment]
Here are the steps to reproduce:

```shell
$ git clone https://github.com/RoRoche/plantuml-gradle-plugin
$ git fetch
$ git checkout feature/using_classgraph 
```

Then in the `build.gradle` file, change the line 18 to set the version you.

Then publish it to local Maven using `./gradlew publishToMavenLocal`

In another Gradle-based project, define the Local Maven repository for plugin management in `settings.gradle` such as:

```groovy
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenLocal()
    }
}
```

Then, in the `build.gradle` file:

```groovy
plugins {
    id "com.github.roroche.plantuml" version "{version}"
}

classDiagram {
    packageName = "{your_package}"
    outputFile = project.file('diagrams/class_diagram.plantuml')
}
```

And launch task `./gradlew buildClassDiagram`

**Comment by lukehutch** [comment]
@thc202 thanks for adding this info. So how do you add the compile classpath of dependencies to the porject?

**Comment by RoRoche** [comment]
> @thc202 thanks for adding this info. So how do you add the compile classpath of dependencies to the porject?

Here is the code to build classLoader in the context of a Gradle plugin:

```groovy
    protected ClassLoader getClassLoader() {
        final URL[] urls = project.sourceSets.main.output.classesDirs.files.collect {
            if (it != null) {
                it.toURI().toURL()
            }
        }.findAll {
            it != null
        } as URL[]
        getLogger().debug(
                "URLs to scan: " + urls
        )
        return new URLClassLoader(urls)
    }
```

Cf. https://discuss.gradle.org/t/gradle-plugin-with-reflections/22690/14

It's to get URL of the including project output dirs (typically, `build/classes/kotlin/main` and `build/classes/java/main`).

I don't know exactly how to add the compile classpath of dependencies to the project :S

**Comment by thc202** [comment]
That can be obtained with:
```Java
project.getConfigurations().named(JavaPlugin.COMPILE_CLASSPATH_CONFIGURATION_NAME);
```

**Comment by lukehutch** [comment]
@RoRoche I think you have all the info you need to get this working now? I suspect this is a classparh issue, not a ClassGraph bug. I won't have time to run your code before tomorrow, however.

**Comment by RoRoche** [comment]
> That can be obtained with:
> 
> ```java
> project.getConfigurations().named(JavaPlugin.COMPILE_CLASSPATH_CONFIGURATION_NAME);
> ```
> 
> https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_plugin_and_dependency_management
> https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#N14F9E
> https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.Configuration.html

I don't see how to deal with `project.getConfigurations().named(JavaPlugin.COMPILE_CLASSPATH_CONFIGURATION_NAME)`

**Comment by thc202** [comment]
You can apply the same logic/handling as done for the `classesDirs`:
```Groovy
// ...

URL[] classpathUrls = project.configurations["compileClasspath"].files.collect { /* ... */ } as URL[]

return new URLClassLoader((urls + classpathUrls) as URL[])
```

**Comment by RoRoche** [comment]
Oh yeah! It works with Maven Local.
I commit/push all the things and re-publish the plugin to try it for real.
I'll let you know.
Thank you very much for help!

**Comment by thc202** [comment]
Great! btw, ideally the task `BuildClassDiagramTask` should have that (i.e. source set, classpath, data from `ClassDiagramExtension`) as [inputs](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_input_output_annotations) (and the class diagram as output), it should be responsibility of the plugin to wire the inputs to the default task. That would allow the user to easily create other tasks for other use cases (e.g. a class diagram from, say, `example` or `test` source sets; or more diagrams from the main source set with different groups of classes).

**Comment by RoRoche** [comment]
Brilliant! I'll try it soon

**Comment by lukehutch** [comment]
Glad you solved it, @RoRoche! 

Thanks for all the help, @thc202! I really don't know anything about Gradle, so couldn't have come up with the solution easily. Not many community members jump in on bug reports -- I'm curious how you saw this bug and decided to help resolve the issue?
