### ISSUE TITLE
Make InputStreamConsumer to be able to throw IOException

### ISSUE THREAD

**Issue by mike-neck** [classgraph/classgraph#430]
`ResourceList#forEachInputStream` has the `ignoreIOException` and really handles `IOException` as such, but `InputStreamConsumer#accept` has no method signature to throw `IOException`.

Expected Behaviour
---

- `IOException` can be thrown from `InputStreamConsumer`.
- `ResourceList#forEachInputStream` can catch `IOException` thrown from `InputStreamConsumer`.
- If `true` as the `ignoreIOExceptions` options is given to `ResourceList#forEachInputStream` method, an exceptions thrown from `InputStreamConsumer` will be ignored.

Actual Behaviour
---

- `InputStreamConsumer#accept` has no method signature to throw `IOException`.
- Users should surround with there IO operation code with `try`/`catch` and rethrow `IOException` wrapped with `UncheckedIOException` or any other `RuntimeException`.
- But `UncheckedIOException`s or any other `RuntimeException`s won't be catched in `forEachInputStream` method.
- The `ignoreIOExceptions` option will be ignored.

https://github.com/classgraph/classgraph/blob/8e6b18e60b2e8ca76ebca1cdf607c5f9a1345e4a/src/main/java/io/github/classgraph/ResourceList.java#L400-L413

https://github.com/classgraph/classgraph/blob/8e6b18e60b2e8ca76ebca1cdf607c5f9a1345e4a/src/main/java/io/github/classgraph/ResourceList.java#L372-L384

Reporduce Code
---

The following code gives a compile error.

```java
try (ScanResult scanResult = new ClassGraph()
    .scan()) {
  scanResult.getAllResources()
  .forEachInputStream((resource, inputStream) -> {
    throw new IOException("test");
  }, true);
}
```

The compilation error can be eliminated, but `UncheckedIOException` won't be ignored.

```java
try (ScanResult scanResult = new ClassGraph()
    .scan()) {
  scanResult.getAllResources()
  .forEachInputStream((resource, inputStream) -> {
    try {
      throw new IOException("test");
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
  }, true);
}
```

---

Other methods
---

`ResourceList#forEachByteBuffer` has the same problem. `IOException` cannot be thrown from `ByteBufferConsumer`, but only `IOException` can be ignored.

**Comment by lukehutch** [comment]
Thanks for reporting this.

* Added three new classes:
  * `ResourceList#ByteArrayConsumerThrowsIOException`
  * `ResourceList#InputStreamConsumerThrowsIOException`
  * `ResourceList#ByteBufferConsumerThrowsIOException`
* Deprecated:
  * `ResourceList#forEachByteArray(ByteArrayConsumer consumer, boolean ignoreIOExceptions)`
  * `ResourceList#forEachByteArray(final ByteArrayConsumer consumer)`
  * `ResourceList#forEachInputStream(InputStreamConsumer consumer, boolean ignoreIOExceptions)`
  * `ResourceList#forEachInputStream(InputStreamConsumer consumer)`
  * `ResourceList#forEachByteBuffer(ByteBufferConsumer consumer, boolean ignoreIOExceptions)`
  * `ResourceList#forEachByteBuffer(ByteBufferConsumer consumer)`
* Added:
  * `ResourceList#forEach(ByteArrayConsumer byteArrayConsumer)`
  * `ResourceList#forEach(ByteArrayConsumerThrowsIOException consumer) throws IOException`
  * `ResourceList#forEach(InputStreamConsumer byteArrayConsumer)`
  * `ResourceList#forEach(InputStreamConsumerThrowsIOException consumer) throws IOException`
  * `ResourceList#forEach(ByteBufferConsumer byteArrayConsumer)`
  * `ResourceList#forEach(ByteBufferConsumerThrowsIOException consumer) throws IOException`

Fixed and released in 4.8.79.

**Comment by lukehutch** [comment]
Thanks for reporting this.

* Added three new classes:
  * `ResourceList#ByteArrayConsumerThrowsIOException`
  * `ResourceList#InputStreamConsumerThrowsIOException`
  * `ResourceList#ByteBufferConsumerThrowsIOException`
* Deprecated:
  * `ResourceList#forEachByteArray(ByteArrayConsumer consumer, boolean ignoreIOExceptions)`
  * `ResourceList#forEachByteArray(final ByteArrayConsumer consumer)`
  * `ResourceList#forEachInputStream(InputStreamConsumer consumer, boolean ignoreIOExceptions)`
  * `ResourceList#forEachInputStream(InputStreamConsumer consumer)`
  * `ResourceList#forEachByteBuffer(ByteBufferConsumer consumer, boolean ignoreIOExceptions)`
  * `ResourceList#forEachByteBuffer(ByteBufferConsumer consumer)`
* Added:
  * `ResourceList#forEachByteArrayIgnoringIOException(ByteArrayConsumer byteArrayConsumer)`
  * `ResourceList#forEachByteArrayThrowingIOException(ByteArrayConsumerThrowsIOException consumer) throws IOException`
  * `ResourceList#forEachInputStreamIgnoringIOException(InputStreamConsumer byteArrayConsumer)`
  * `ResourceList#forEachInputStreamThrowingIOException(InputStreamConsumerThrowsIOException consumer) throws IOException`
  * `ResourceList#forEachByteBufferIgnoringIOException(ByteBufferConsumer byteArrayConsumer)`
  * `ResourceList#forEachByteBufferThrowingIOException(ByteBufferConsumerThrowsIOException consumer) throws IOException`

Fixed and released in 4.8.80.

**Comment by mike-neck** [comment]
Thank you for your quick improvement.

**Comment by lukehutch** [comment]
You're welcome, I appreciate all the detail and thought you put into the bug report!
