### ISSUE TITLE
wiki: unable to checkout working tree due to error: invalid path 'API:-AnnotationInfo.md'

### ISSUE THREAD

**Issue by spyluxos** [classgraph/classgraph#432]
whilst trying to git clone the wiki, I was confronted with the following error:

>**git clone https://github.com/classgraph/classgraph.wiki.git**
> Cloning into 'classgraph.wiki'...
> remote: Enumerating objects: 6, done.
> remote: Counting objects: 100% (6/6), done.
> remote: Compressing objects: 100% (6/6), done.
> remote: Total 4648 (delta 2), reused 0 (delta 0), pack-reused 4642 eceiving objects:  99% (4602/4648), 2.00 MiB | 3.97 MiB/s
> Receiving objects: 100% (4648/4648), 2.80 MiB | 4.84 MiB/s, done.
> Resolving deltas: 100% (2934/2934), done.
> **error: invalid path 'API:-AnnotationInfo.md'**
> **fatal: unable to checkout working tree**
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry with 'git restore --source=HEAD :/'
`

Checking the status did not reveal any issues...
>**git status**
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean

So could you please do a 
**git restore --source=HEAD :/**
on your side?

**Comment by lukehutch** [comment]
Hi, I think you're the first person that has ever tried to clone the wiki :)

I just tried this:

```
$ git clone https://github.com/classgraph/classgraph.wiki.git
Cloning into 'classgraph.wiki'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 4648 (delta 2), reused 0 (delta 0), pack-reused 4642
Receiving objects: 100% (4648/4648), 2.80 MiB | 6.39 MiB/s, done.
Resolving deltas: 100% (2934/2934), done.
```

I had a thought -- maybe your operating system doesn't allow colon characters in paths? What OS are you using?

**Comment by lukehutch** [comment]
I renamed all the pages that contain `:` and `?` in their title. Can you please try again?

**Comment by lukehutch** [comment]
I'm going to assume this is fixed, but if not, please comment here and I'll reopen the issue.
