### ISSUE TITLE
Is it possible to use getConstantInitializerValue() on a statically declared String field using MyClass.class.getCanonicalName()?

### ISSUE THREAD

**Issue by ronnybremer** [classgraph/classgraph#455]
Reading through the documentation it is clearly stated, that you can only use getConstantInitializerValue() on static fields using any initialization value which can be derived without having to instantiate the class. This includes simple arithmetic for ints or String operations.
I was wondering, whether
`
class MyClass {
   @anAnnotation
   public final static String CLASS_NAME = MyClass.class.getCanonicalName();
}
`
would be supportable, as it should not required the class to be instantiated.

Any insight would be highly appreciated.

Thanks, Ron

**Comment by lukehutch** [comment]
I don't know how that method gets the class name, but I have to assume that the only way for that value to be statically determined would be if the compiler had special case logic for that method call -- which it doesn't. The Java compiler simply does not support partial evaluation, other in the very few compiletime expression simplification cases discussed in the docs. Unfortunately there's no way around this. (GraalVM does support partial evaluation, but ClassGraph doesn't work in that environment.)

If you would like to verify this, it should only take a few lines of code to test it.
