### ISSUE TITLE
User Jars Under lib Directory Treated as External

### ISSUE THREAD

**Issue by akagixxer** [classgraph/classgraph#456]
Hello,

`ClassGraph` has been a great tool! Thank you!

```
Java Version
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

ClassGraph Version
4.8.87
```

I came across this issue. It seems like `ClassGraph` is treating jar files under **ANY** directory called `lib` as external (i.e. part of the Java JDK installation).

For example we put our production jars under a folder called `lib`: `D:\path\to\app\lib`
Then we call `java` like: `java -cp D:\path\to\app\lib\* com.MainClass`

The code:
```java
    try (ScanResult scan = new ClassGraph()
      .acceptPaths("root")
      .scan())
    {
	  scan.getResourcesWithExtension("yaml").stream()
	  ...
    }
```

The verbose logging prints this for *ALL* of our jar files:
```
Juli 01, 2020 9:31:19 VORM. nonapi.io.github.classgraph.utils.LogNode <init>
INFORMATION: 2020-07-01T09:31:19.723-0700       ClassGraph      Scanning disabled for lib or ext jar: D:/path/to/app/lib/Something.jar
```

The only way I can get it to work is to configure `ClassGraph` with `acceptLibOrExtJars()` even though I'm not trying to scan system jars
OR
rename the folder to something other than `lib`.

Is this expected behavior?
I'm just asking because I've seen a fair number of software products put their jar files under a folder named `lib`.

**Comment by lukehutch** [comment]
Hi, glad ClassGraph (mostly) works for you!

This is not expected behavior. However, I can't replicate this issue on either Windows or Linux. Can you please attach a complete working project that demonstrates the issue?

You could also take a look at the code here to try to figure out where this is failing:

https://github.com/classgraph/classgraph/blob/master/src/main/java/nonapi/io/github/classgraph/classpath/SystemJarFinder.java

Perhaps the `java.home` property is set incorrectly or something?

**Comment by akagixxer** [comment]
Ah, thanks.
That source file was very enlightening!

It appears that the issue might be environmental.
The software in question is deploying its own JRE install and the installation has a directory structure like this:
```
/install/deployment/jre/.....
/install/deployment/lib/(production jars)
```
and `java.home` is being set at runtime to: `/install/deployment/jre`

So I'm guessing `ClassGraph` is anticipating a JDK install and looking for a `lib` at: {java.home}../lib
or
`/install/deployment/jre/../lib`
which is where the production jars happen to be and thus they are getting ignored.

Does this seem like the plausible cause for the observed behavior?
If so, I believe the issue is entirely environmental and not an issue with `ClassGraph`.

**Comment by lukehutch** [comment]
Yes, that is exactly the issue: if you're deploying your jars into `%JAVA_HOME%\lib`, then you are actually deploying into the JDK's `lib` directory (the JDK home is found at `jre\..`). Therefore ClassGraph is working as expected.

Note that deploying jars into `%JAVA_HOME%\lib` is a perfectly valid way to extend the JRE with library jars, particularly when those jars need to be accessed by multiple projects. However, most of the time these jars don't contain resources or classes that users of ClassGraph want to scan -- therefore, lib jars are not scanned by default. The difference here seems to be that the main project jar (not a library jar) is deployed into `lib`, and although even main project jars can be added to the classpath that way, it is not really the intent of the `lib` dir to be able to deploy whole applications as library jars.

For this application, either of the two workarounds you proposed should fix the problem.

Thanks for the report!
