### ISSUE TITLE
[Delete This] RePlAcE BlAcKlIsT wItH dEnYLiSt and WhIteLiSt wItH aLlOwLiSt

### ISSUE THREAD

**Issue by Ceikry** [classgraph/classgraph#478]
Blacklist and whitelist are incredibly racist and insensitive terms and this NEEDS to be RECTIFIED.

(Who am I kidding no one fucking cares)

Great project btw, I use this a lot.

**Comment by lukehutch** [comment]
Looks like you realized this is fixed in the latest version. Actually I moved on this about 5 weeks before the rest of the open source community, several versions ago.
