### ISSUE TITLE
io.github.classgraph.MethodTypeSignature#getTypeParameters is package private

### ISSUE THREAD

**Issue by lastrix** [classgraph/classgraph#490]
`
    /**
     * Get the type parameters for the method. N.B. this is non-public, since the types have to be aligned with
     * other parameter metadata. The type of a parameter can be obtained post-alignment from the parameter's
     * {@link MethodParameterInfo} object.
     * 
     * @return The type parameters for the method.
     */
    List<TypeParameter> getTypeParameters() {
        return typeParameters;
    }`

The TypeParameters could not be fetched through MethodParameterInfo because it has no connection (TypeParameter can only be declared in class or method).
Since this description is same as for getParameterTypeSignatures

`
    /**
     * Get the type signatures of the method parameters. N.B. this is non-public, since the types have to be aligned
     * with other parameter metadata. The type of a parameter can be obtained post-alignment from the parameter's
     * {@link MethodParameterInfo} object.
     * 
     * @return The parameter types for the method, as {@link TypeSignature} parsed type objects.
     */
    List<TypeSignature> getParameterTypeSignatures() {
        return parameterTypeSignatures;
    }`
I could see this as typo.
Also, i should note that same method (getTypeParameters) for classInfo is public:

`
    /**
     * Get the type parameters for the class.
     *
     * @return The type parameters for the class.
     */
    public List<TypeParameter> getTypeParameters() {
        return typeParameters;
    }`

please add public modifier to io.github.classgraph.MethodTypeSignature#getTypeParameters

**Comment by lukehutch** [comment]
Hi, there's a reason you can't call that method. Unfortunately the generic type parameter info for methods is not correctly generated by all compilers. There are several pieces of information that have to be aligned using a best-fit heuristic. If you look at where ClassGraph calls that API internally, you'll see how the information is aligned.

The fix is to call `ClassInfo#getMethodInfo()`, which gives you the properly aligned info, then you can get the type parameters you need from there.

Let me know if that works for you.

**Comment by lastrix** [comment]
Wait a sec, but i get methods this way: x.getMethodAndConstructorInfo which gives exact same result as you suggestion.
Rigth now i have no other option but to use reflection in order to fetch type parameters (it works exactly as expected, but too slow comparing to simple getter).
Just a note: getMethodInfo() returns MethodInfoList which contains MethodInfo. It has access to Array[MethodParameterInfo], and no way to get TypeParameter list. 
See the selected line:
![image](https://user-images.githubusercontent.com/677198/102012400-1c3cd880-3d5b-11eb-8099-2fdd01cfb8cb.png)

This thing is not accessible through MethodInfo#getTypeParameters() or any other way. If you look at MethodInfo#toString() then you'll see that even there you use type parameters from descriptor, if there is a way to get it using MethodInfo, then why you go this way?
Searching through MethodInfo for any occurence of TypeParameter leads to toString method only, no other reference.


As you described, you can't allow access from descriptor, is it possible to add MethodInfo#getTypeParameters then?

**Comment by lukehutch** [comment]
I think what you're missing is a typecast from `TypeSignature` to `ClassRefTypeSignature`. The hierarchy of `TypeSignature` classes is documented, but probably not well enough.

```java
package main;

import java.util.List;

import io.github.classgraph.ClassGraph;
import io.github.classgraph.ClassInfo;
import io.github.classgraph.ClassRefTypeSignature;
import io.github.classgraph.MethodInfo;
import io.github.classgraph.MethodTypeSignature;
import io.github.classgraph.ScanResult;
import io.github.classgraph.TypeArgument;
import io.github.classgraph.TypeSignature;

public class TestReadingTypeArgs {
    static class A<X> {
    }

    static abstract class B {
        abstract A<Integer> a();
    }

    public static void main(String[] args) {
        try (ScanResult scanResult = new ClassGraph()
                .acceptPackages(TestReadingTypeArgs.class.getPackage().getName()).enableAllInfo().scan()) {
            ClassInfo bClass = scanResult.getClassInfo(B.class.getName());
            MethodInfo aMethodInfo = bClass.getMethodInfo("a").get(0);
            MethodTypeSignature aType = aMethodInfo.getTypeSignatureOrTypeDescriptor();
            TypeSignature aResultType = aType.getResultType();
            ClassRefTypeSignature aResultTypeConcrete = (ClassRefTypeSignature) aResultType;
            String aTypeBaseClassName = aResultTypeConcrete.getBaseClassName();
            List<TypeArgument> aTypeArgs = aResultTypeConcrete.getTypeArguments();
            TypeArgument aTypeArg0 = aTypeArgs.get(0);
            String aTypeArg0BaseClassName = ((ClassRefTypeSignature) aTypeArg0.getTypeSignature())
                    .getBaseClassName();
            System.out.println("Method a() returns type " + aTypeBaseClassName + " with parameter type "
                    + aTypeArg0BaseClassName);
        }
    }
}
```

This prints:

```
Method a() returns type main.TestReadingTypeArgs$A with parameter type java.lang.Integer
```

Let me know if this works for you.

**Comment by lukehutch** [comment]
See docs here:

https://github.com/classgraph/classgraph/wiki/TypeSignature-API

**Comment by lastrix** [comment]
I have a method public static < T > void echo(T t);
All i need is to get < T > - the generic type parameter, which is represented by TypeParameter class in classgraph, not void returned by echo.

Your code will return me void, but i need T!
And as a note, if method is public static <T,E,F> void echo(T t, E e, F f) i need to get all of T, E, F, not void again, because this  is return type. And i'm not talking about method parameters.
If i have method public static < T > T getT(), then i need to get generic type parameter T again, not T type.

**Comment by lukehutch** [comment]
Well I was just giving an example, but you need to adapt that to your own usecase. This works for me:

```java
    static abstract class Cls {
        abstract <T, E, F> void echo(T t, E e, F f);
    }

    public static void main(String[] args) {
        try (ScanResult scanResult = new ClassGraph()
                .acceptPackages(TestReadingTypeArgs.class.getPackage().getName()).enableAllInfo().scan()) {
            ClassInfo bClass = scanResult.getClassInfo(Cls.class.getName());
            MethodInfo methodInfo = bClass.getMethodInfo("echo").get(0);
            for (MethodParameterInfo paramInfo : methodInfo.getParameterInfo()) {
                TypeVariableSignature typeVar = (TypeVariableSignature) paramInfo.getTypeSignature();
                System.out.println(typeVar.getName());
            }
        }
    }
```

**Comment by lukehutch** [comment]
You can also resolve type variables to concrete types using the `TypeVariableSignature#resolve()`

**Comment by lukehutch** [comment]
Here's how `resolve()` works:

```java
    static class A {
    }

    static class B<T extends A> {
        T get() {
            return null;
        }
    }

    public static void main(String[] args) {
        try (ScanResult scanResult = new ClassGraph()
                .acceptPackages(TestReadingTypeArgs.class.getPackage().getName()).enableAllInfo().scan()) {
            ClassInfo bClass = scanResult.getClassInfo(B.class.getName());
            final var methodInfo = bClass.getMethodInfo("get").get(0);
            TypeVariableSignature resultType = (TypeVariableSignature) methodInfo.getTypeSignature()
                    .getResultType();
            System.out.println(resultType);
            TypeParameter resolvedResultType = resultType.resolve();
            System.out.println(resolvedResultType);
        }
    }
```

Output:

```
T
T extends main.TestReadingTypeArgs$A
```

**Comment by lastrix** [comment]
`public < T extends A > void dosmth()`
Okay, let's see what you'll do to print actual generic type parameter this time.
Remember that it must be method generic parameter, not class generic parameter.

I need method generic type parameters https://docs.oracle.com/javase/tutorial/extra/generics/methods.html .
Result type or parameter types are irrelevant to me. The method TypeParameter array inside signature is final array and initialized after signature construction, what could be wrong here in order access it is beyond me. You do not modify it or replace. No modification occurs.

**Comment by lukehutch** [comment]
Please provide a complete example. In that one line you gave, you don't even use the type T. The compiler could very easily just drop this unused type.

**Comment by lastrix** [comment]
This is not type, it's generic type parameter, it goes to method generic signature which should give something like this:
< T >()Z
Returned by getTypeSignatureOrTypeDescriptorStr. The first part is generics, inside parens - method parameters followed by return type. 

The complete example:
`public class Example { public static <T> void smthng() { T a = (T)(Object)"fail"; } }`

This will not warn you about unused declarations.

Please open class io.github.classgraph.MethodTypeSignature, then find field typeParameters. It got initialized once in constructor and no processing occurs afterwards.
Why i should guess whether method has generics or not analyzing it's return type and parameters?

**Comment by lastrix** [comment]
![image](https://user-images.githubusercontent.com/677198/102045414-0f1afa80-3dea-11eb-869e-aae9273cdde2.png)
Here your example inside your library. How i supposed to get list of T, E generics?

**Comment by lukehutch** [comment]
Ah! I finally see what you mean. I have never seen code before in Java that declares a method type parameter like that but then never uses the type among the method parameter types. Usually Java bounds the type parameter using the concrete parameter types -- otherwise any generic type parameter to a method is pretty useless, and may as well be `Object` in the case of a parameter `<T>`, or `Widget` in the case of a bounded generic parameter like `<T extends Widget>`, when `T` is not used at all among the method parameters.

To be honest I have no idea why you would even want to use a method type parameter in this way without using it among the types of the method parameters. But I see what you mean about the fact that it still should be valid to get this info. And it had been so long since I wrote this code that I forgot it was obtained from the raw type signature string directly. I also managed to trip myself up because a copy/paste of the Javadoc for `getParameterTypeSignatures()` meant that the comment for `getTypeParameters()` was wrong.

OK, I'll expose this getter publicly, for whatever you need it for!

**Comment by lukehutch** [comment]
Thanks for your patience. Fixed in 4.8.95.

**Comment by lastrix** [comment]
Misunderstaning is not an excuse for impatience. =)
Thanks, everything works fine now.

**Comment by lukehutch** [comment]
I hardly think I was impatient here, I produced several examples for you, and turned around this bug for you to a new release in less than a day. I was misguided though, because I had some flawed assumptions about what this Java language feature was actually used for. I thought nobody would ever need to access this generic type except through parameter types and the return type, because I thought it served no other purpose. Actually I still think that that's the only way a method's generic type parameter is actually useful, if it's used as a formal parameter's type -- but you were right that the getter needed to be public.

**Comment by lastrix** [comment]
No-no, you was great, i saw that you try to convince me about your point.
I'm greatful for your job, if i somehow hurt you - i'm really sorry.
I tried to tell you that **i** have no excuse for impatience, because what i saw - you can't understand what i'm talking about because of my poor english or lack of info.

Anyway, thanks you. You are breathtaking.

**Comment by lukehutch** [comment]
Oh! Sorry, I misunderstood that too! No, your English is great, don't worry about that at all. I'm glad we got it sorted out, and I'm glad that it's working for you now. Thanks for the bug report.
