### ISSUE TITLE
What interface name does 'getClassesImplementing' receive?

### ISSUE THREAD

**Issue by KaimingWan** [classgraph/classgraph#499]
As we know that scanResult.getClassesImplementing(interfaceName) need pass an interfacename into it. Do we need to pass the full interface name into it ?

I have an interface class called IStudent ,and its subclass is StudentA and StudentB. I need get all the subclass by classgraph.

Here is my code that reference to the offical doc. 
```java
       final String pkg = "com.clougence.xxx";
        try (ScanResult scanResult =
                     new ClassGraph()
                             .verbose()               // Log to stderr
                             .enableAllInfo()         // Scan classes, methods, fields, annotations
                             .acceptPackages(pkg)     // Scan com.xyz and subpackages (omit to scan all packages)
                             .scan()) {               // Start the scan
            for (ClassInfo classInfo : scanResult.getClassesImplementing(IStudent.class.getName())) { 
                //do something with class info
            }
        }
```

What method should I use to get the right interface name:
1. IStudent.class.getCanonicalName
2. IStudent.class.getName
3. IStudent.class.getSimpleName

**Comment by KaimingWan** [comment]
I tryied and getCanonicalName works

**Comment by lukehutch** [comment]
`getName()` is what you want. The interface name must be fully qualified, and `getSimpleName()` provides only the class name, not the package prefix. `getCanonicalName()` switches `$` signs for `.` for inner classes, but internally ClassGraph uses the name, not the canonical name.
