### ISSUE TITLE
Big file issue

### ISSUE THREAD

**Issue by cwmccann** [classgraph/classgraph#514]
Hi,

I ran into an interesting issue.  If the jar files are very large the order of the files (ZipEntries) matter.  If the classes come first then they can be found in a scan.  If the classes come last they will not be found.

Here's a script and a unit test that shows the issue:

`src/test/resources/makeBigJar.sh`
```
#!/usr/bin/env bash

mkdir -p tmp/;
cd tmp;
jar -xf ../record.jar

#ASSET_DIR="zz" # Works
ASSET_DIR="aa" # Doesn't Works

mkdir -p ${ASSET_DIR}
cd ${ASSET_DIR}

for number in {1..23}; do
  echo "Making file ${number}"
  ## make a bunch of big files that won't compress
  dd if=/dev/urandom of="output${number}.bin" bs=1024 count=102400 2> /dev/null
done

cd ..
echo "Building big jar"
jar -cf ../bigjar.jar *
```
 
//Copy of the RecordTest
Test `src/test/java/io/github/classgraph/issues/BigFileTest.java`
```
public class BigFileTest {
    /** The jar URL. */
    private static final URL jarURL = RecordTest.class.getClassLoader().getResource("bigjar.jar");

    /**
     * Test records (JDK 14+).
     *
     * @throws Exception
     *             the exception
     */
    @Test
    public void recordJar() throws Exception {
        try (ScanResult scanResult = new ClassGraph().overrideClassLoaders(new URLClassLoader(new URL[] { jarURL }))
            .enableAllInfo().scan()) {
            final ClassInfoList classInfoList = scanResult.getAllRecords();
            assertThat(classInfoList).isNotEmpty();
            final ClassInfo classInfo = classInfoList.get(0);
            final FieldInfo fieldInfo = classInfo.getFieldInfo("x");
            assertThat(fieldInfo).isNotNull();
        }
    }
}
```
```

**Comment by lukehutch** [comment]
Hi, the `RecordTest` and `record.jar` are missing... can you please attach these? (Meanwhile I'll try creating a simple record to see if I can replicate...)

**Comment by cwmccann** [comment]
I based them off the your github repo.  I could do a PR if you want but you could just create them in a clean copy of master from this github repo.

**Comment by cwmccann** [comment]
Here's a patch:
[Big_file_test.patch.txt](https://github.com/classgraph/classgraph/files/6408394/Big_file_test.patch.txt)

**Comment by lukehutch** [comment]
Got it! Sorry, I somehow missed that. Much appreciated for making it easy :-)  I am able to replicate the problem.

There is indeed a 2GB limit bug in the Zip64 code. The unzip code (including the Zip64 code) is entirely custom, and jars larger than 2GB are very rare, so has not been heavily tested. I'll try to get a fix out soon.

**Comment by lukehutch** [comment]
OK, this is fixed in 4.8.105. The problem was that I thought the original Zip spec only supported 2GB archives, and anything over that required the Zip64 extensions. However, the original Zip spec actually supports archives up to almost 4GB, via the use of unsigned ints (which are mandated in the spec). So the bug was only triggered for zipfiles between 2GB and 4GB in size, when the zip entry was past the 2GB point in the file (which sets bit 31 of the position, making it go negative).

Many thanks for the bug report and helpful example! This is fixed and released in version 4.8.105.

**Comment by cwmccann** [comment]
Thanks for the quick turn around on this issue!  I can confirm the fix is working on my end as well.

**Comment by lukehutch** [comment]
I try to make bugfixing a top priority always! Thanks for confirming the fix!
