### ISSUE TITLE
Getter AnnotationInfo.getRawParamValues() needed.

### ISSUE THREAD

**Issue by zerikv** [classgraph/classgraph#535]
Hello,

First thank you for your great tool.

I'm interested for retrieve the parameters of an annotation without the default values. I guess I  just need a getter on the field `annotationParamValues` of the class `AnnotationInfo`. If you think it's a usefull method, would it possible to add it in the API ?

Thanks

**Comment by lukehutch** [comment]
Sounds like a good addition. Are you willing to give it a shot, and submit a pull request? It shouldn't require much code.

**Comment by lukehutch** [comment]
Hi @zerikv -- please test the change I just committed. Thanks!

**Comment by zerikv** [comment]
Thank you Luke for your quick reply. I've tested and it's ok for me.

**Comment by lukehutch** [comment]
Great, thanks for testing! Released in version 4.8.110. I appreciate the feature request!
