### ISSUE TITLE
Annotation's `short` parameter value is always `0`

### ISSUE THREAD

**Issue by liangzengle** [classgraph/classgraph#548]
Annotation's parameter which type is `short`, it's value in `AnnotationInfo` is always `0`.

```
@Retention(RetentionPolicy.CLASS)
@Target(ElementType.TYPE)
public @interface MyAnnotation {
    short value();
}
```
```
@MyAnnotation(1)
public class MyClass {
    public static void main(String[] args) {
        new ClassGraph()
                .enableAllInfo()
                .scan(ForkJoinPool.commonPool(), 8)
                .getClassesWithAnnotation(MyAnnotation.class.getName())
                .forEach(classInfo -> {
                    AnnotationInfo annotationInfo = classInfo.getAnnotationInfo(MyAnnotation.class.getName());
                    Object value = annotationInfo.getParameterValues().get("value").getValue();
                    System.out.println(value); // prints: 0
                });
    }
}
```
I beleive the `short` type value is handled incorrectly at [return (short) cpReadUnsignedShort(reader.readUnsignedShort());](https://github.com/classgraph/classgraph/blob/984d35c25dfcf1384993840e2689a5f9effac6ef/src/main/java/io/github/classgraph/Classfile.java#L988)
And I tried `cpReadInt` instead of `cpReadUnsignedShort`, it works fine.

**Comment by lukehutch** [comment]
@liangzengle Wow, great job debugging the problem right down to the source! You're totally right, all types other than long use a full 4 bytes (in big endian order) in the constant pool table. So the top two bytes will be zero for a short.

Fixed and released in version 4.8.114. Xiexie!

**Comment by lukehutch** [comment]
PS @liangzengle make sure you call `.scan()` in try-with-resources, so that the returned `ScanResult` is closed when you have finished with it.

**Comment by liangzengle** [comment]
@lukehutch Thanks for the heads up and the fast fix-release.
