### ISSUE TITLE
Cannot read annotation within a collection type

### ISSUE THREAD

**Issue by AdityaPadhy** [classgraph/classgraph#556]
I have a class as follows:

```
public class Test {
 @NotNull
 private List<@Size(100)String> values;

// Getter
//Setter
}
```

When i do :

```
ScanResult result = new ClassGraph().enableAllInfo().whitelistClasses(Test.class.getName()).scan();
ClassInfoList classInfos = result.getAllClasses();
```

The class info does have the details of annotation @NotNull inside fieldInfo but it does not have the details of @Size annotation. Is this a bug?

**Comment by lukehutch** [comment]
That's a type annotation. The way to get the information is to find the class, get the `FieldInfo` for that named field, get the type signature for the field, then get the type annotations for the type signature:

https://github.com/classgraph/classgraph/blob/latest/src/main/java/io/github/classgraph/TypeSignature.java#L90

**Comment by lukehutch** [comment]
Actually it may be more complicated than this in this case, because the annotation is actually on a type parameter. I'm not by my computer, but look at the concrete subtype of the `TypeSignature` for this field, then call the method to get the type parameters of the type, then get the type annotations for the first parameter.

**Comment by AdityaPadhy** [comment]
Don't have the details of the annotation inside type signature. 
See this screenshot. Also i don't see parameterInfo inside the `fieldInfo` or `TypeSignature`. am i looking at the right place?

![image](https://user-images.githubusercontent.com/14880537/133601974-bb3b9933-4bd5-4671-adb6-4f1916288f6e.png)

If you could find the right place to look for, could you please give an example?

**Comment by lukehutch** [comment]
Sorry, it's not super straightforward to find your way through the API! Here is a working example -- it prints `100`:

```
public class TypeAnnotation {
    @Retention(RetentionPolicy.RUNTIME)
    public @interface Size {
        int value();
    }

    public class Test {
        private List<@Size(100) String> values;
    }

    public static void main(String[] args) {
        try (ScanResult scanResult = new ClassGraph()
                .acceptPackages(TypeAnnotation.class.getPackage().getName())
                .enableAllInfo()
                .scan()) {
            ClassInfo ci = scanResult.getClassInfo(Test.class.getName());
            FieldInfo fi = ci.getFieldInfo().get(0);
            ClassRefTypeSignature ts = (ClassRefTypeSignature) fi.getTypeSignature();
            List<TypeArgument> taList = ts.getTypeArguments();
            TypeArgument ta = taList.get(0);
            ReferenceTypeSignature taSig = ta.getTypeSignature();
            AnnotationInfoList aiList = taSig.getTypeAnnotationInfo();
            AnnotationInfo ai = aiList.get(0);
            AnnotationParameterValueList apVals = ai.getParameterValues();
            AnnotationParameterValue apVal = apVals.get(0);
            int size = (int) apVal.getValue();
            System.out.println(size);
        }
    }
}
```
