### ISSUE TITLE
classgraph-4.8.118.jar - ClassGraph.CIRCUMVENT_ENCAPSULATION is final

### ISSUE THREAD

**Issue by eitan-rosenberg** [classgraph/classgraph#564]
Hello,

According to: https://github.com/classgraph/classgraph/releases/tag/classgraph-4.8.118

If you run into troubles with JDK versions 16+ (I have 17)

you need to Set ClassGraph.CIRCUMVENT_ENCAPSULATION = true; 

![image](https://user-images.githubusercontent.com/48506054/135751911-1632ab7e-6dfa-4b3b-b561-b2d00043b2cb.png)

ClassGraph.CIRCUMVENT_ENCAPSULATION is final

Also looking at the source of io.github.classgraph.ClassGraph 

![image](https://user-images.githubusercontent.com/48506054/135751925-26f575b1-e678-4a0a-b5d1-ea158095719d.png)

Regards.

**Comment by eitan-rosenberg** [comment]
Hi,
I try classgraph-4.8.119.jar but I get:
Could not load Narcissus reflection driver: java.lang.NoSuchMethodException: getDeclaredMethods
**### Do you want to use zoom ?**
Eitan.


this "ClassGraph.CIRCUMVENT_ENCAPSULATION = true;" is ok now.

My code: 

package myClassInfo;

import java.lang.annotation.Annotation;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

import io.github.classgraph.ClassGraph;
import io.github.classgraph.ClassInfo;
import io.github.classgraph.ScanResult;

public class MyClassInfo {

	static {
		ClassGraph.CIRCUMVENT_ENCAPSULATION = true;
	}

	public static Map<String, ClassInfo> getClassesWithAnnotation(final Class<? extends Annotation> annotation) {

		final ScanResult scanResult = new ClassGraph().enableExternalClasses().enableInterClassDependencies()
				.enableAllInfo().acceptPackages("my*", "main").scan();

		return scanResult.getClassesWithAnnotation(annotation).stream().sorted().distinct()
				.collect(Collectors.toMap(ClassInfo::getName, Function.identity(), (a, b) -> a, LinkedHashMap::new));

	}

}

**Comment by lukehutch** [comment]
Yes, sorry, I discovered this right after release. Fixed in 4.8.120.

Please let me know if you have more issues.

**Comment by eitan-rosenberg** [comment]
Testing.....

**Comment by eitan-rosenberg** [comment]
@lukehutch 

Seems to be working...

May the force be with you !!!

Many thanks.

**Comment by lukehutch** [comment]
@eitan-rosenberg Great, thanks for testing! You shouldn't need the `ClassGraph.CIRCUMVENT_ENCAPSULATION = true;` line unless your code does not work without it. This is for solving a special case, as described in the release notes for this release.
