### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by alessandroargentieri** [classgraph/classgraph#565]
From the docs is not clear if it can be used to scan files and packages that are external to the project itself.

**Comment by lukehutch** [comment]
Sorry, I know there's too much documentation to read it all, but this is documented here:

https://github.com/classgraph/classgraph/wiki/Code-examples#scanning-specific-urls

Feel free to open a discussion topic in the new GitHub Discussions tab if you have further questions:

https://github.com/classgraph/classgraph/discussions
