### ISSUE TITLE
version 4.8.124 "Could not load JVM-Driver reflection driver"

### ISSUE THREAD

**Issue by eitan-rosenberg** [classgraph/classgraph#568]
When using version 4.8.124 I get: "Could not load JVM-Driver reflection driver: java.lang.ClassNotFoundException: io.github.toolfactory.jvm.DefaultDriver"

**But the show goes on....**

Regards

**Comment by eitan-rosenberg** [comment]
It seems that io.github.classgraph.ClassGraph is doing:

public static CircumventEncapsulationMethod CIRCUMVENT_ENCAPSULATION = CircumventEncapsulationMethod.JVM_DRIVER;

so later on at nonapi.io.github.classgraph.reflection.ReflectionUtils.class we have :

![image](https://user-images.githubusercontent.com/48506054/136332734-39521c8f-93c5-4d99-afaa-df1113eec38f.png)

I hope that I am correct....
Regards

**Comment by lukehutch** [comment]
Yes, that is left over from debugging, sorry! Thanks for reporting! I'll set it back to `NONE` and re-release.

**Comment by lukehutch** [comment]
Fixed in 4.8.125.
