### ISSUE TITLE
Illegal reflective access warning on Classpath.getClasspathURIs() with Adopt JDK 11

### ISSUE THREAD

**Issue by UlrichLohrmann** [classgraph/classgraph#605]
I use AdopJDK on Windows with the following version:

```
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20210120_899 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 0a86953833 based on jdk-11.0.10+9)
```
With ClassGraph 4.8.135 I have a JEE application running in Open Liberty that does the following ClassGraph call:

```
List<URI>       classpathEntries = new ClassGraph().getClasspathURIs();
```

With this I get the following warning from the JDK:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by nonapi.io.github.classgraph.reflection.ReflectionDriver (file:/D:/Programme/openLiberty/openLiberty-SAMV/wlp/usr/servers/SAMV-Liberty/apps/expanded/Gradle___de_dsv_samv___SamvEAR_ear.ear/lib/classgraph-4.8.135.jar) to method com.ibm.java.lang.management.internal.RuntimeMXBeanImpl.getInputArguments()
WARNING: Please consider reporting this to the maintainers of nonapi.io.github.classgraph.reflection.ReflectionDriver
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
As the warning mentions that illegal reflective access might be denied in future releases of the JDK it would be interesting how to handle this situation.

**Comment by lukehutch** [comment]
Thanks for the report, I made a change so that `getRuntimeMXBean` is only called if the module path info is directly requested, via `ClassGraph.getModulePathInfo()` or `ScanResult.getModulePathInfo()` is called. Released in ClassGraph 4.8.137.

In case those methods need to be called, the illegal access warning can be removed by including the optional runtime dependency Narcissus, or alternatively JVM-Driver, as detailed here: https://github.com/classgraph/classgraph#running-on-jdk-16

**Comment by UlrichLohrmann** [comment]
Thank you for working on this issue and for fixing it so fast.

**Comment by UlrichLohrmann** [comment]
One more info.
If I include classgraph as a dependency using Gradle and using the versionstring '4.8.+', version 4.8.132 is selected instead of 4.8.137. Seems to be something wrong with the publishing of the versions later than 4.8.132.

**Comment by UlrichLohrmann** [comment]
Tested with version 4.8.137 and the warning does not occur any more. Thanly again for your help.

**Comment by lukehutch** [comment]
Great, thank you for confirming!

I have no idea where Gradle looks up the latest version. Is this a Gradle thing, or a Gradle IDE plugin thing?

**Comment by UlrichLohrmann** [comment]
Your are right. Seems to be a problem with my environment. The correct version is selected from Gradle.
