### ISSUE TITLE
Module-info.class with version 17

### ISSUE THREAD

**Issue by gurinderu** [classgraph/classgraph#623]
If classgraph exists on the classpath while you running a jdeps with a "multi-release 17" flag it throws a MultiReleaseException.
I guess the jar file should also have a "module-info.class" descriptor also for all versions

**Comment by lukehutch** [comment]
What is this exception, and what does it mean? I don't know how to replicate this, can you please provide more info?

**Comment by gurinderu** [comment]
@lukehutch I am not sure that it is a library bug.

Just run the command with correct paths
jdeps -v -R --multi-release 17 classgraph-4.8.138.jar jackson-jr-objects-2.13.0.jar jackson-core-2.13.0.jar

jackson-jr-objects has a version 11 Module-info.class and 
classgraph has a 9

**Comment by lukehutch** [comment]
Thanks, I can replicate using this.

This seems to be a `jdeps` bug: https://stackoverflow.com/a/70011064/3950982

ClassGraph puts `module-info.class` into `META-INF/versions/9` for maximum compatibility (honestly I don't think the module descriptor should ever be anywhere other than `META-INF/versions/9`, for this reason).

Please try JDK 18's `jdeps`, build 26 or later.

**Comment by lukehutch** [comment]
Closing, as this does not appear to be a ClassGraph bug. If you find otherwise, please comment here, and I will reopen it. Thanks!
