### ISSUE TITLE
"Could not parse type signature" in Kotlin test classes

### ISSUE THREAD

**Issue by polovkovaaa** [classgraph/classgraph#645]
Hello,

When parsing test code, an error occurs if the test method name contains parentheses, and the body contains curly brackets. Because of this, ClassInfo.isExternalClass == true and dependencies are not parsed. There is an error message in the logs "Invalid classfile: Could not parse type signature". Logs and an example project in the attached files.
[class_graph_logs.txt](https://github.com/classgraph/classgraph/files/7997305/class_graph_logs.txt)
[TestClassGraph.zip](https://github.com/classgraph/classgraph/files/7997306/TestClassGraph.zip)

**Comment by lukehutch** [comment]
Thanks, I'm traveling right now, but I'll try to get to this in the next few days.

**Comment by lukehutch** [comment]
Wait, you mean to tell me that `sample test (Could not parse type signature)` is a valid function name in Kotlin? :-o

I'll have to trace through to see where the paren is disallowed by the current parser...

**Comment by polovkovaaa** [comment]
Yes, it's valid name for test methods.
Coding conventions - https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods

**Comment by lukehutch** [comment]
This is fixed in the git main version, please test it and let me know if there are any more issues. I have several bugs I need to fix and close, but once that is done, this will be in the next release. Thank you for the report!

**Comment by polovkovaaa** [comment]
I checked the git main version. Now it works correctly. Thank you, looking forward to the next release.

**Comment by lukehutch** [comment]
Thank you for testing!
