### ISSUE TITLE
nonapi.io.github.classgraph.classpath.CallStackReader: illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by patrickhancke** [classgraph/classgraph#646]
It seems a similar issue was already reported previously and fixed but now it seems to be back.
This is the output I get on the console:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by nonapi.io.github.classgraph.classpath.CallStackReader (file:/C:/Users/ph/.m2/repository/io/github/classgraph/classgraph/4.8.138/classgraph-4.8.138.jar) to method java.lang.SecurityManager.getClassContext()
WARNING: Please consider reporting this to the maintainers of nonapi.io.github.classgraph.classpath.CallStackReader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
I'm using Java 11:
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

**Comment by lukehutch** [comment]
Sorry for the delay, I am traveling right now.

I haven't seen this on any platform or JDK version, and just tried now on JDK 11, and could not reproduce this. Are you using a SecurityManager? Is there anything special about how you are launching your application or anything? Are you running inside some sort of module system or enterprise Java environment?

Are you able to please put together a complete minimal test project that demonstrates the problem?

**Comment by patrickhancke** [comment]
hi Luke,

Thanks for your reply.

I've seen the above message in my Intellij IDE (version 2021.3.2) when I was working on the upgrade from Java 8 to 11 from my Spring Boot application. Later on, I realized that my IDE didn't pick up correctly the JDK compiler options, like for example `-parameters`, I put in my `pom.xml` file. I then refreshed / rebuilt my project in Intellij: if I remember correctly, I haven't seen the above error anymore since then.

I think you can close this issue then.

**Comment by lukehutch** [comment]
@patrickhancke OK, thank you for our followup. I'm not sure what commandline parameters would cause the change in behavior. But I'm glad it's working for you now! I will close the bug.

**Comment by lukehutch** [comment]
I think I finally figured this out, and why I couldn't reproduce it. I'm not sure what the version "11+28" means (is that 11.0.0 build 28?), but if your JVM was version 11 prior to 11.0.4, it had a crasher bug that precluded the use of `StackWalker`, so ClassGraph had to fall back to another method of getting the call stack. See #663.
