### ISSUE TITLE
NPE in JBossClassLoaderHandler#findClasspathOrder 

### ISSUE THREAD

**Issue by arthware** [classgraph/classgraph#651]
In our scenario we get a `NullPointerException` in `JBossClassLoaderHandler#findClasspathOrder `

The `moduleMap` is null in our case, leading to an NPE in the next line, when accessing the entrySet.

https://github.com/classgraph/classgraph/blob/f874380e58ac3e9e4834df199129a58c79d15f33/src/main/java/nonapi/io/github/classgraph/classloaderhandler/JBossClassLoaderHandler.java#L213-L215

I was able to fix this with a simple null check. The scan returns the expected results. 

**Before:** 
` for (final Entry<Object, Object> ent : moduleMap.entrySet() ) {`

**After:**
` Set<Entry<Object, Object>> moduleMapEntries = moduleMap != null ? moduleMap.entrySet() : Collections.emptySet();
    for (final Entry<Object, Object> ent : moduleMapEntries) {`

**Comment by lukehutch** [comment]
Fixed via #652. Thank you!

**Comment by arthware** [comment]
Thank you for merging and your efforts!

**Comment by arthware** [comment]
@lukehutch any chance to get a release pushed out in the next two weeks? That'd be awesome. Thank you very much!

**Comment by lukehutch** [comment]
Yes, I'm sorry for the delay. I will do it in a few hours once my current flight lands!

**Comment by lukehutch** [comment]
OK, I was able to push out version 4.8.140 with this fix. I probably should have just done this after merging. Thanks again for your fix!
