### ISSUE TITLE
CWE 73: PathTraversal issue

### ISSUE THREAD

**Issue by donacarr** [classgraph/classgraph#675]
ASOC source scan found high severity vulnerability issue https://github.com/classgraph/classgraph/blob/3203c980081e20b09e31be40087a3c908302459b/src/main/java/nonapi/io/github/classgraph/fastzipfilereader/NestedJarHandler.java#L555

Here is the detail:
```
Calling Method nonapi.io.github.classgraph.fastzipfilereader.NestedJarHandler.downloadJarFromURL(java.lang.String;nonapi.io.git
hub.classgraph.utils.LogNode):nonapi.io.github.classgraph.fastzipfilereader.PhysicalZipFile
Line 555
Source File nonapi.io.github.classgraph.fastzipfilereader.NestedJarHandler
CWE: 73
Source: java.net.URL.openConnection():URLConnection via nonapi.io.github.classgraph.fastzipfilereader.NestedJarHandle
r:538
Sink: java.io.File(URI):void via nonapi.io.github.classgraph.fastzipfilereader.NestedJarHandler:555
```

Stack trace:
![image](https://user-images.githubusercontent.com/13415391/162978532-7944cc67-2991-433e-b3ef-ae26d3ffa56b.png)

Could you comment on this please?
Thx

**Comment by lukehutch** [comment]
Thanks for reporting... Does this tool explain why this is a high-priority security issue? Nothing about this looks like a problem to me.

**Comment by donacarr** [comment]
The ASOC report contains just this info:
```
**Cause**
The application receives the name of a directory or file from the user. If this is used to create the file path directly, the path can be
manipulated to point to directories and files which should not be allowed access or which may contain malicious data or code.
In particular, user input is not checked for the '..' (dot dot) pattern or directory separators (usually slash), and the file permissions are not
restricted.
**Risk**
It is possible to modify, delete, or read the contents of any file (for example, databases, user information or configuration files) on the
web server that the application can access.
An attacker may try to corrupt or remove critical files used by the application or operating system to cause a DoS attack, or even add
data to a file.
The attack can also be used to delete log files containing information that could be used to track down an attacker.
```

**Comment by lukehutch** [comment]
This is a false positive. the URL in question comes from the classpath, and it represents a jar that needs to be scanned. Yes, someone could mess with the classpath to make ClassGraph read jars it is not supposed to read, but this is not a security problem for ClassGraph itself, it is the caller's responsibility to validate the classpath if that is needed, because ClassGraph has no way to know which classpath elements are valid, it just has to scan what it is told to scan.

I committed a slight fix to how this `File` object is obtained. Can you please try scanning the latest version in git again to see if the warning is suppressed? Thank you.

**Comment by donacarr** [comment]
If you provide the new jar lib file I will try a new scan.

**Comment by lukehutch** [comment]
You can build it very simply, just download the git source and do `./mvnw install` (recommended with JDK 8, but it might work with newer versions). It will build a `-SNAPSHOT` jar and install it into your local maven repository. Then in your project, you just have to change the version of ClassGraph that you depend upon to the snapshot version that you built.

**Comment by donacarr** [comment]
The warning is gone.
Appreciated your fast response.
Thx

**Comment by lukehutch** [comment]
Great, thank you! I'll close this. I'm fixing another issue right now, but this will be in the next release.
