### ISSUE TITLE
scan can't find my classes in Adobe AEM project

### ISSUE THREAD

**Issue by jchambers-crescendo** [classgraph/classgraph#709]
So the scan seems to work, the `scanResult` object has a `classpathOrder` list that's 216 elements long, and it's finding lots of classes, but MY classes, which are in the *very same package* as is the code I'm currently executing (and debugging through, in fact the current class implements `BaseModel`), my `relevantClasses` ALWAYS gets 0 results, even though there are dozens of classes implementing (descendants of) `BaseModel`, though when I do similar attempts to find those directly, they also aren't being found!

```java
    private static Map<String, Class<?>> models = null;
    public static Map<String, Class<?>> modelClassesByName() {
        if (models == null) {
            models = new HashMap<>();
            try (ScanResult scanResult = new ClassGraph().enableClassInfo().scan()) {
                ClassInfoList relevantClasses = scanResult.getClassesImplementing(BaseModel.class);
                for (ClassInfo clazz : relevantClasses) {
                    Class<? extends BaseModel> modelClass = (Class<? extends BaseModel>) clazz.loadClass();
                    models.put(BaseModel.modelName(modelClass), modelClass);
                }
            }
        }
        return models;
    }
```

I'm on Java 11, in an Adobe AEM project.  Any leads would be much appreciated, this library has always worked well everywhere else I've used it.

**Comment by hiroshi-yamamoto-dublr** [comment]
Hi @jchambers-crescendo,

The first thing to check is the verbose logs -- add `.verbose()` before `.scan()`.

The logs should be self-explanatory, and are hierarchically-organized. Check to see whether the classpath element you are trying to scan is being found, and if it is being scanned, look to see if there are error messages on any of the classes that it's not finding.

**Comment by jchambers-crescendo** [comment]
@hiroshi-yamamoto-dublr Thank you, that `verbose()` does create a lot of output... I see it listing through a whole lot of jars, and lots and lots of "Ignoring duplicate (masked) class", but no error messages in evidence.

**Comment by jchambers-crescendo** [comment]
When I look at what the `maven-install-plugin` outputs during build, it's putting it into a `target` directory in my build path... but I don't see that path anywhere in the output of that verbose scan, so I guess it's not scanning the right JARS for classes... but how can I be executing code that isn't in the classpath?!

**Comment by jchambers-crescendo** [comment]
I am deploying the code using this maven profile, which all came with the whole AEM mess.  I presume this is deploying the JAR somewhere that `classGraph` doesn't know about, so isn't finding... but how can I get it to just use the currently loaded classes directly, or something?  Or do I need to somehow point it to the JAR?
```xml
<profile>
            <id>autoInstallPackage</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>org.apache.jackrabbit</groupId>
                            <artifactId>filevault-package-maven-plugin</artifactId>
                            <executions>
                                <execution>
                                    <id>create-package</id>
                                    <goals>
                                        <goal>package</goal>
                                    </goals>
                                </execution>
                            </executions>
                        </plugin>
                        <plugin>
                            <groupId>com.day.jcr.vault</groupId>
                            <artifactId>content-package-maven-plugin</artifactId>
                            <executions>
                                <execution>
                                    <id>install-package</id>
                                    <goals>
                                        <goal>install</goal>
                                    </goals>
                                    <configuration>
                                        <targetURL>http://${aem.host}:${aem.port}/crx/packmgr/service.jsp</targetURL>
                                    </configuration>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
```

**Comment by lukehutch** [comment]
Hi @jchambers-crescendo, I don't know anything about AEM, but it is very possible that AEM defines its own classloader that ClassGraph doesn't know anything about yet. Are you able to attach the verbose logs, please, along with information about the paths you actually want to scan?

The first thing to check is whether any classloader is detected that ClassGraph was not able to extract classpath entries from. And you need to check whether ClassGraph scanned the paths that you wanted it to scan.

**Comment by lukehutch** [comment]
Also if you're able to create a minimal reproducer testcase, that would help to get to the bottom of what is going on. Thanks!

**Comment by jchambers-crescendo** [comment]
@lukehutch Aha, there it is, classgraph didn't know about the class loader that was being used (when I put a breakpoint and call `getClass().getClassLoader()` on whatever class, I get an instance of `org.apache.sling.commons.classloader.impl.BundleProxyClassLoader`)... 

Adding a single `.addClassLoader(BaseModel.class.getClassLoader())` to the configuration of the ClassGraph scan result did the trick!  This now works perfectly:

```java
    private static Map<String, Class<?>> models = null;
    public static Map<String, Class<?>> modelClassesByName() {
        if (models == null) {
            models = new HashMap<>();
            try (ScanResult scanResult = new ClassGraph().addClassLoader(BaseModel.class.getClassLoader()).enableClassInfo().scan()) {
                ClassInfoList relevantClasses = scanResult.getClassesImplementing(BaseModel.class);
                for (ClassInfo clazz : relevantClasses) {
                    Class<? extends BaseModel> modelClass = (Class<? extends BaseModel>) clazz.loadClass();
                    models.put(BaseModel.modelName(modelClass), modelClass);
                }
            }
        }
        return models;
    }
```

**Comment by lukehutch** [comment]
Great, glad you found a fix! But this begs the question, why could ClassGraph not find that classloader? Can you please investigate where else a reference to that classloader can be obtained from, in a generic way? (classloader of the current thread, etc)

**Comment by jchambers-crescendo** [comment]
Hmm... good question, @lukehutch. I haven't so far found any useful generic way to do it, I have tried getting `Thread.currentThread().getContextClassLoader()` and `Thread.currentThread().getClass().getClassLoader()`, and neither of those (when used as above), give me the classes I need... 🤔

But making a static class reference as shown above (as is usually done with static logger objects), and it works with any class in my project.
