### ISSUE TITLE
Incorrect base path for relative paths

### ISSUE THREAD

**Issue by raner** [classgraph/classgraph#731]
I'm trying to troubleshoot a problem with ClassGraph in a proprietary project. I'm not 100% sure this is a bug, it's very possible that I'm just not using ClassGraph correctly.

The problem is that certain classes are skipped from scanning during some tests. This happens in an OSGi environment, and I see similar problems when running in Eclipse via "Run As ▶︎ JUnit Plug-in Test" or in Maven via `tycho-surefire-plugin`. However, the problem does not happen when running outside of an OSGi container. In both cases, the problematic classes are loaded from a local directory rather than from a packaged JAR file.

In the verbose output I see the following for the skipped classes:
```
2022-11-20T17:34:27.376-0800	ClassGraph	------------ Scanning directory: /Users/mirko/git/fxx/fxx.api/target/classes (took 0.005631 sec)
2022-11-20T17:34:27.376-0800	ClassGraph	-------------- Scanning directory: /Users/mirko/git/fxx/fxx.api/target/classes/fxx (took 0.005489 sec)
2022-11-20T17:34:27.376-0800	ClassGraph	---------------- Scanning directory: /Users/mirko/git/fxx/fxx.api/target/classes/fxx/annotation (took 0.001166 sec)
2022-11-20T17:34:27.379-0800	ClassGraph	------------------ Found classfile within subpackage of accepted package: fxx/fxx.api/target/classes/fxx/lang/String.class
2022-11-20T17:34:40.495-0800	ClassGraph	-------------------- Parsing classfile (took 0.000126 sec)
2022-11-20T17:34:40.495-0800	ClassGraph	---------------------- Skipping classfile: Relative path fxx/fxx.api/target/classes/fxx/lang/String.class does not match class name fxx.lang.String
```
As indicated by the verbose output, the `fxx.lang.String` class is not scanned for annotations, and neither are any of the other classes in the same bundle.

What strikes me as odd in this output are the relative paths shown in the skip messages. For example, if `fxx/fxx.api/target/classes/fxx/lang/String.class` is the _relative_ path for the `fxx.lang.String` class, this would seem to indicate that this path is _relative to_ my local git folder (`/Users/mirko/git`), which seems completely random. It might make a little more sense to me if the paths were relative to my home folder (`/Users/mirko`) or to the current directory where the build is executed (`/Users/mirko/git/fxx` in this case). In my mind, the correct base path for relative path names should be `/Users/mirko/git/fxx/fxx.api/target/classes`, in which case the derived relative paths would end up correctly (I believe).

The scanning code itself is also fairly standard (using [Xtend](https://www.eclipse.org/xtend/) syntax):
```xtend
  Supplier<Map<Double, String>> bindings = Suppliers.memoize
  [
    val ClassGraph classGraph = new ClassGraph()
      . enableClassInfo
      . enableAnnotationInfo
      . rejectPackages(skippedPackages)
      . verbose
    newImmutableMap
    (
      try (val ScanResult scan = classGraph.scan)
      {
        scan.getClassesWithAnnotation(integrationPointAnnotation).loadClasses.map
        [
          integrationPoint -> it
        ]
        . filter[key !== null]
        . flatMap
        [
          #[key.annotationValue -> value.name] + value.declaredMethods
          . map[integrationPoint -> name]
          . filter[key !== null]
          . map[key.annotationValue -> value]
        ]
      }
    )
  ]
```
Am I missing some configuration here or could this be a bug in ClassGraph? I'm using (the slightly outdated) version 4.8.138, and upgrading is a bit involved with the way the build is set up.

**Comment by raner** [comment]
Indeed, for some reason, ClassGraph scans my entire git folder including many other unrelated projects:
```
⋮
2022-11-20T17:34:26.552-0800	ClassGraph	-- Scanning directory classpath element /Users/mirko/git (took 13.545840 sec)
2022-11-20T17:34:26.553-0800	ClassGraph	---- Scanning directory: /Users/mirko/git (took 13.545228 sec)
2022-11-20T17:34:26.555-0800	ClassGraph	------ Found resource within accepted package: .DS_Store
2022-11-20T17:34:26.555-0800	ClassGraph	------ Found resource within accepted package: db.sqlite3
⋮
```
In the classpath order I do see the correct directory for the bundle that is not being processed:
```
Final classpath element order:
⋮
-- file:///Users/mirko/git/fxx/fxx.api/target/classes/
⋮
```
It might be noteworthy that this entry is one of only two in the list that are in the format of a `file:///`... URL (the other one being `file:///usr/local/Cellar/maven/3.6.3_1/libexec/conf/logging/`, presumably due to the tests ultimately being run via Maven). Other than that, the list of classpath elements consists mostly of expected entries, e.g. stuff like
```
⋮
-- /Users/mirko/.m2/repository/org/eclipse/tycho/tycho-bundles-external/2.1.0/eclipse/plugins/org.eclipse.osgi.compatibility.state_1.2.100.v20200811-1344.jar
-- /Users/mirko/.m2/repository/dev/fxx/fxx.compiler/0.1.0-SNAPSHOT/fxx.compiler-0.1.0-SNAPSHOT.jar
-- /Users/mirko/.m2/repository/dev/fxx/fxx/0.1.0-SNAPSHOT/fxx-0.1.0-SNAPSHOT.jar
-- /Users/mirko/git/fxx/fxx.core/target/fxx.core-0.1.0-SNAPSHOT.jar
-- /Users/mirko/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
-- /Users/mirko/.m2/repository/com/google/inject/guice/5.1.0/guice-5.1.0.jar
-- /Users/mirko/.m2/repository/com/sun/xml/dtd-parser/dtd-parser/1.4.5/dtd-parser-1.4.5.jar
-- /Users/mirko/.m2/repository/p2/osgi/bundle/javax.xml/1.3.4.v201005080400/javax.xml-1.3.4.v201005080400.jar
-- /Users/mirko/.m2/repository/p2/osgi/bundle/javax.inject/1.0.0.v20091030/javax.inject-1.0.0.v20091030.jar
⋮
```
Notably, I don't see an entry that lists my git folder, `/Users/mirko/git`, neither as a plain path nor as a `file:///` URL.

**Comment by raner** [comment]
After some more digging and grepping I found this in the verbose output, which basically confirms that the classpath entry in question is not being processed (though the specific reason is not clear to me):
```
2022-11-20T17:28:23.228-0800	ClassGraph	-- Skipping invalid classpath element file:/Users/mirko/git/fxx/fxx.api/target/classes : java.io.IOException: Cannot get classpath element for classpath entry file:/Users/mirko/git/fxx/fxx.api/target/classes [java.net.URLClassLoader@2f52b57e] : java.io.FileNotFoundException
```

**Comment by lukehutch** [comment]
@raner On your first comment -- it looks like the root directory of your filesystem is being scanned, or possibly `/Users/mirko`. Can you please include the top part of the log that shows all the classpath entries that are found from the classloaders?

On your second comment -- can you please set a debugger breakpoint on `FileNotFoundException`, and see why that `file:` URL is not being found?

**Comment by raner** [comment]
[log.txt](https://github.com/classgraph/classgraph/files/10134502/log.txt)

Sorry for the delayed response, I'm currently traveling. I've attached the full list of detected classpath elements. I did set a breakpoint for FNFEs, but unfortunately they seem to occur pretty frequently, so I haven't had the time to trace it down to the relevant one.

I'll report back when I have a better understanding of what's going on; I suspect that there are a few things not 100% correct with some of the `build.properties` files for some of the skipped modules.

**Comment by raner** [comment]
Oops, I just realized that one of the modules in question (`fxx.api`) is not in the list that I just sent... I did make some experimental changes to the `build.properties` files for some of the modules, so I might be onto something here... Feel free to have a look at the list I sent and let me know if you see anything out of the ordinary, but the actual problem might be masked in that list.

**Comment by lukehutch** [comment]
Sorry for the slow response times!

If `/Users/mirko/git` is not included in the list of classpath elements, at the top of the logfile, then that directory should not be scanned recursively. The fact it is being scanned means that some classloader added that directory to the classpath. Are you sure that directory is not listed on the classpath for some reason? I don't see it in the last you sent, however, so I'm puzzled as to what you're seeing.

The `file:///` prefix should not cause a classpath entry to be treated differently. Internally this is supposed to be normalized/standardized, no matter how a classpath element is specified.

You gave this example in your original bug report:

```
2022-11-20T17:34:27.376-0800	ClassGraph	------------ Scanning directory: /Users/mirko/git/fxx/fxx.api/target/classes (took 0.005631 sec)
2022-11-20T17:34:27.376-0800	ClassGraph	-------------- Scanning directory: /Users/mirko/git/fxx/fxx.api/target/classes/fxx (took 0.005489 sec)
2022-11-20T17:34:27.376-0800	ClassGraph	---------------- Scanning directory: /Users/mirko/git/fxx/fxx.api/target/classes/fxx/annotation (took 0.001166 sec)
2022-11-20T17:34:27.379-0800	ClassGraph	------------------ Found classfile within subpackage of accepted package: fxx/fxx.api/target/classes/fxx/lang/String.class
2022-11-20T17:34:40.495-0800	ClassGraph	-------------------- Parsing classfile (took 0.000126 sec)
2022-11-20T17:34:40.495-0800	ClassGraph	---------------------- Skipping classfile: Relative path fxx/fxx.api/target/classes/fxx/lang/String.class does not match class name fxx.lang.String
```

However you cut off the top of the log, so I can't see what the classpath element is that was being scanned. I suspect it is `/Users/mirko/git` in this case.

So it sounds like there are two main questions here:

1. Why is `/Users/mirko/git` being added to the classpath? The logs will show you which classloader added this classpath element.
2. Why is `/Users/mirko/git/fxx/fxx.api/target/classes` not being found as a classpath element? Look at the logs to see if a classloader added this classpath element. If not, it is possible that ClassGraph is not properly discovering all classpath elements from all classloaders. If you can figure out which classloader contains this path, then we can figure out why ClassGraph can't find it.

After all classpath elements are found, a test is run to see which classpath entries are prefixes of other entries. In this case if both `/Users/mirko/git` and  `/Users/mirko/git/fxx/fxx.api/target/classes` are found as classpath entries, then the recursive scan of `/Users/mirko/git` is supposed to stop when it hits `/Users/mirko/git/fxx/fxx.api/target/classes` (it is possible that this doesn't work, which would mean that the classes inside `target/classes` would be found twice, and rejected for the `/Users/mirko/git` scan, because the path is incorrect, but accepted when `/Users/mirko/git/fxx/fxx.api/target/classes` is scanned as a classpath root -- the end result is your class would still be found).

**Comment by lukehutch** [comment]
Ping :-)

**Comment by raner** [comment]
Sorry for the radio silence. I can no longer reproduce this issue, it was possibly a bug in my own code, not in ClassGraph. I'll close it for now and will re-open in case it resurfaces in a more reproducible fashion.

**Comment by lukehutch** [comment]
@raner no worries, I'm glad it's no longer an issue! Hopefully it will stay that way :-)
