### ISSUE TITLE
Missing API access for annotations on type parameters and wildcard type arguments 

### ISSUE THREAD

**Issue by platosha** [classgraph/classgraph#741]
`TypeParameter` and `TypeArgument` (in case of using a wildcard) could hold annotations, but they do not have a `getTypeAnnotationInfo()` getter exposed, despite parsing works seemingly correctly in both cases. 

Consider analysing annotations specified on the method parameter types in the scan result of the following class:

```java
class GenericTypeAnnotationTest {
    @Target({ ElementType.FIELD, ElementType.TYPE_USE, ElementType.TYPE_PARAMETER })
    private static @interface A {
    }

    <@A T> void saveT(T param) {
    }

    void saveUList(List<@A ?> param) {
    }
}
```

`typeParameter.toString()` and `typeArgument.toString()` results show the `@A` annotation where expected, but there is no API to access the `@A` annotation info other than `toString()`.

Apart from Java, this has a big impact on working with Kotlin compiled code, as for some types (`BigDecimal` and `BigInteger` are known examples, my wild guess, for supporting Kotlin language extensions) compiler emits `List<@A ? extends Type> param` in JVM bytecode whereas the source had `List<@A Type> param`.

**Comment by lukehutch** [comment]
@platosha Thanks for reporting this, for explaining the background, and for providing the complete fix! Much appreciated. I'll roll out a release tonight with this.

**Comment by lukehutch** [comment]
This is released in 4.8.153, but then I subsequently committed https://github.com/classgraph/classgraph/commit/42753efb26cfa16be0daf761ca5a8e8c36401e40, which moves this method into the superclass -- that way all type signature classes support getting type annotation information. (Adds support for `ClassTypeSignature`, `MethodTypeSignature`, `BaseTypeSignature`, `ReferenceTypeSignature`, etc.)

**Comment by platosha** [comment]
@lukehutch thanks a lot!

**Comment by lukehutch** [comment]
@platosha The weird thing is I went to document this API call in the wiki docs, and it was already there! So it looks like I always planned to add this getter, I just forgot to do it. 🤦‍♂️  I'm glad you caught it!
