### ISSUE TITLE
How do I scan jdk17? For example, java.lang

### ISSUE THREAD

**Issue by natarol** [classgraph/classgraph#744]
```
public static void main(String[] args) {
		ClassGraph.CIRCUMVENT_ENCAPSULATION = CircumventEncapsulationMethod.JVM_DRIVER;
		ClassGraph classGraph = new ClassGraph() ;
		ScanResult result = classGraph
				.enableAllInfo()
				.acceptPackages("java.lang")
				.scan() ;
		result.getAllClasses().forEach( c -> System.out.println(c) );
}

output : No information
```

In this way, the classes in java.lang cannot be obtained

My project needs to find all subclasses of throwable(Include jdk, such as NullPointerException). Can classgraph help me?

**Comment by lukehutch** [comment]
You need to call `.enableSystemJarsAndModules()` before scanning to scan these modules.

You shouldn't need the `CIRCUMVENT_ENCAPSULATION` thing unless something is not working due to encapsulation.
