### ISSUE TITLE
GraalVM native image failures during build-time scanning

### ISSUE THREAD

**Issue by justin-tay** [classgraph/classgraph#756]
This is actually a continuation of #681 which was closed.

I was trying with ClassGraph `4.8.154` and encountered the same issue. I have set the appropriate `--initialize-at-build-time` arguments so that ClassGraph and my class performing the scan are initialized at build time.

I referenced the project on https://github.com/SoftInstigate/classgraph-on-graalvm and found that this particular issue was introduced in `4.8.128`. The last version that worked on that project was `4.8.127`. https://github.com/classgraph/classgraph/compare/classgraph-4.8.127...classgraph-4.8.128.

This particular issue was introduced by the change to add a `ClassMemberCache`. This cache ends up being statically held because `ReflectionUtils` statically stores the `ReflectionDriver`.
https://github.com/classgraph/classgraph/blob/dc3253595946048d2dbf4ce01e0b6333fa956b33/src/main/java/nonapi/io/github/classgraph/reflection/ReflectionUtils.java#L43

I can get around this issue by setting the `reflectionDriver` to `null` after the scan has completed.

```java
nonapi.io.github.classgraph.reflection.ReflectionUtils.reflectionDriver = null;
```

In my actual application I encountered another issue with the `CallStackReader` statically storing `callStack`.

https://github.com/classgraph/classgraph/blob/8b358c63db2b4a5dc844f96e9453809b8f83adf8/src/main/java/nonapi/io/github/classgraph/classpath/CallStackReader.java#L45

I had to use reflection to clear this out after the scan has completed for the image building process to complete successfully.

```java
try {
	Class<?> clazz = Class.forName("nonapi.io.github.classgraph.classpath.CallStackReader");
	Field field = clazz.getDeclaredField("callStack");
	field.setAccessible(true);
	field.set(null, null);
} catch (ClassNotFoundException | NoSuchFieldException | SecurityException | IllegalArgumentException
		| IllegalAccessException e) {
	throw new RuntimeException(e);
}
```
I will try to find time to create a small test case project that demonstrates this.

**Comment by lukehutch** [comment]
Thanks for the detailed report. I included code to fix both cases.

Note that to clear the `reflectionDriver` reference, you need to call `ScanResult#close()` when the scan is complete (i.e. scan in `try-catch` as recommended in the docs).

Released in 4.8.155.

**Comment by justin-tay** [comment]
Thanks for the quick response! It's now fixed.

**Comment by lukehutch** [comment]
You're welcome :)
