### ISSUE TITLE
ClassGraph not writing to System.err

### ISSUE THREAD

**Issue by sngillis** [classgraph/classgraph#789]
I'm running ClassGraph (4.8.160) in a project and getting strange results (incomplete Class listings, etc.), so I'm trying to debug things.  I've called ClassGraph verbose() and enableRealTimeLogging() and the System.err stream remains empty.

I have attempted to capture the System.err stream like so:

```
ByteArrayOutputStream err = new ByteArrayOutputStream();
System.setErr(new PrintStream(err));

ClassGraph graph = new ClassGraph()...options...enableRealTimeLogging();
ScanResult scan = graph.scan();

String errMsg= new String(err.toByteArray());
System.out.println(errMsg);
```

And the errMsg String and the ByteArrayOutputStream err are both quite empty.

What am I not doing correctly here?

**Comment by lukehutch** [comment]
That's very weird, I have never seen ClassGraph not write to `System.err` when `verbose()` has been called (you're doing the right thing).

(`enableRealtimeLogging()` just calls `verbose()`, but then outputs logs immediately, rather than in a hierarchical tree as produced by just calling `verbose()`, where the child nodes of any tree node are sorted into a sensible order, e.g. by filename, and output at the end.)

I have a couple of tests that redirect `System.err` in order to check that things are logged correctly, by calling `System.setErr`. I assume that your runtime environment is doing something similar... (and this is what you tried doing)

https://github.com/classgraph/classgraph/blob/5f94ed6f590fa52047814eb92e67f23aa410019e/src/test/java/io/github/classgraph/test/utils/LogNodeTest.java#L39

I don't know how to check if this is what's going on, but maybe try calling `System.setErr(System.err)` before the scan?

https://github.com/classgraph/classgraph/blob/5f94ed6f590fa52047814eb92e67f23aa410019e/src/test/java/io/github/classgraph/test/utils/LogNodeTest.java#L29

**Comment by lukehutch** [comment]
The only other thing I can think of is that the default logger of your runtime environment may be set up with a `ConsoleHandler` that has writing to stderr suppressed. I have to set the `ConsoleHandler` in the test to ensure that the logger will write to stderr (although I can't remember the reason for this):

https://github.com/classgraph/classgraph/blob/5f94ed6f590fa52047814eb92e67f23aa410019e/src/test/java/io/github/classgraph/test/utils/LogNodeTest.java#L43

I just create a default logger instance:

https://github.com/classgraph/classgraph/blob/5f94ed6f590fa52047814eb92e67f23aa410019e/src/main/java/nonapi/io/github/classgraph/utils/LogNode.java#L59

This pulls in a logger implementation from the classpath -- so this might be a question of which logger you're including on the classpath, and what the default settings of that logger are:

https://github.com/classgraph/classgraph/blob/5f94ed6f590fa52047814eb92e67f23aa410019e/src/main/java/nonapi/io/github/classgraph/utils/LogNode.java#L52-L55

**Comment by sngillis** [comment]
It seems this is a weakness with the approach of having the logging dump to System.err.  If the runtime environment is handling the System.err within it's internal logging, and that logging system is not readily accessible to the developer (either because it's private / protected, or because it's just poorly documented), then the ClassGraph logs are lost.

You are doing all this work to create structured logs that will make sense, there should be an option to have ClassGraph direct logging to an alternate stream that can not be captured by the runtime environment behind the scenes.

Edit: I've spent all morning in the debugger looking over the runtime environment.  I know the RE has captured System.err, but everything I've tried to redirect it back to something I can access has failed to produce a stream with any content.

**Comment by lukehutch** [comment]
But the ClassGraph logging system doesn't write to stderr at all. It uses the standard Java logging system, which has pluggable backends that are configured in the runtime environment, outside of ClassGraph. It does request that logger to make sure logging to stderr is activated, but I guess loggers don't have to honor that request. The problem though is in your runtime environment configuration, not in ClassGraph, as far as I can determine.

I am interested in the other flaky behavior you have observed, so I hope you can get to the bottom of the logging issue in your setup.

**Comment by sngillis** [comment]
OK, so I did this:
```
Logger cgLog = Logger.getLogger(ClassGraph.class.getName());
FileHandler fh = new FileHandler("C:\\temp\\cgLog.txt");
SimpleFormatter format = new SimpleFormatter();
fh.setFormatter(format);
cgLog.addHandler(fh);
ClassGraph graph = new ClassGraph()
                .acceptPackages(acceptPkg)
                .rejectPackages(rejectPkg)  
                .enableAllInfo()
                .verbose();
graph.scan();
```
And I got some logs.

I can't post the logs here, but I can send them to you if your curious.

**Comment by lukehutch** [comment]
Great!

First try digging through the logs, comparing the logs with different behaviors of the scanner between runs, and see if you can spot the reason for any discrepancies. Thanks.

**Comment by lukehutch** [comment]
Hi @sngillis , any updates?

**Comment by sngillis** [comment]
The logs helped and I was able to get the desired Class Loader and get my code to work.

Thank you!

**Comment by lukehutch** [comment]
OK, good to hear it!
