### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by neo-expert** [classgraph/classgraph#807]
ClassGraph promises to find "all classes that implement a given interface". I think it is important to mention, that these classes need to be loaded? Or at least exists on the classpath.  I doubt, that ClassGraph can find an implementation of an interface, which exists only in my thoughts.

**Comment by thc202** [comment]
IMO that it is a `classpath scanner and module scanner` already implies that it will not scan your thoughts (but maybe).

**Comment by lukehutch** [comment]
No, the classes don't need to be loaded. But they do need to be on the classpath, or loaded into a module layer that is visible to the calling class.

> I doubt, that ClassGraph can find an implementation of an interface, which exists only in my thoughts.

Yes, but do you really think I need to update the documentation to say "...but it can't find classes that exist only in the thoughts of @neo-expert"? I have to give my users a bit of credit that they can figure this sort of thing out...
