### ISSUE TITLE
Get the Class and method comments

### ISSUE THREAD

**Issue by dbschema-pro** [classgraph/classgraph#818]
Can Classgraph return the class and method comments from the sources.jar files? Searching the documentation I couldn't find out how.

I am looking to extend a [language server protocol for Groovy](https://github.com/GroovyLanguageServer/groovy-language-server), which basically provides auto-completion for Groovy scripts. Showing the method or class comments is an essential feature in a text-editor.

**Comment by lukehutch** [comment]
Unfortunately no, comments never make it into the classfile, and ClassGraph only scans classfiles, not Java source. You would need a Java parser for that. Probably ecj (the Eclipse Compiler for Java) would be the one you would want to use for that sort of task, but maybe somebody has already built an ecj tool to extract just comments. Also, you could probably just write an HTML parser that read the JavaDoc files and autocompleted based on that. (Actually this second idea is the one I would try first.)

**Comment by lukehutch** [comment]
Or, maybe you can see if the `javadoc` tool can be modified to output JavaDoc in JSON format or something.

Actually I just googled this, and I found this tool. There are probably more like this too:

https://github.com/tantaman/jsonDoclet
