### ISSUE TITLE
Feature request：Add getClassesWithAllAnnotations

### ISSUE THREAD

**Issue by He-Pin** [classgraph/classgraph#821]
Motivation:
It would be nice to get a `ClassInfoList` which contains the Classes annotated with both annotations, currently, only one annotation is supported.

**Comment by lukehutch** [comment]
Do you want an AND or an OR operator, if multiple annotations are specified?

**Comment by He-Pin** [comment]
Currently, I'm using `ClassinfoList#intersect` method to handle this.

**Comment by lukehutch** [comment]
Hi, I added your requested method in the git version, can you please test it?

**Comment by He-Pin** [comment]
Cool, I'm currently using 
```kotlin
           val classInfoList = scanResult.getClassesWithAnnotation(FeatureSpec::class.java)
                .intersect(scanResult.getClassesWithAnnotation(Component::class.java))
```

code like this.

**Comment by lukehutch** [comment]
@He-Pin please test the latest git version. Thanks.

**Comment by lukehutch** [comment]
Released in 4.8.167. Thanks for the request!

**Comment by He-Pin** [comment]
@lukehutch Thanks, it works well. refs: https://github.com/classgraph/classgraph/commit/e66ee3c902bcc60397d6ec07765726bf6109aa30#comments

**Comment by lukehutch** [comment]
Great, thanks for confirming.
