### ISSUE TITLE
#rejectPaths usage with relative paths

### ISSUE THREAD

**Issue by mlntdrv** [classgraph/classgraph#871]
I have scanned for duplicates and I get a lot of this kind:

> org/apache/commons/logging/Log.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-dae9b43971d6e39a/WEB-INF/lib/commons-logging-1.2.jar!/org/apache/commons/logging/Log.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/commons-logging-1.2.jar-39eb46b48fcec75a/commons-logging-1.2.jar!/org/apache/commons/logging/Log.class

I tried to exclude the temp directory with:
```java
.rejectPaths("WEB-INF/classes", "WEB-INF/lib")
.rejectPaths("WEB-INF")
.rejectPaths("*WEB-INF*")
.rejectPaths("temp*")
.rejectPaths("temp")
.rejectPaths("tmp/vfs/temp")
.rejectPaths("*tmp/vfs/temp")
.rejectPaths("standalone/tmp/vfs/temp")
.rejectPaths("standalone/tmp/vfs/temp/")
.rejectPaths("standalone/tmp/vfs/temp/*")
.rejectPaths("*/devruntime/wildfly/standalone/tmp/vfs/temp/*")
.rejectPaths("*/devruntime/wildfly/standalone/tmp/vfs/temp/")
.rejectPaths("devruntime/wildfly/standalone/tmp/vfs/temp/")
.rejectPaths("C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp")
```
however nothing seems to work. What am I missing?
v4.8.174

**Comment by lukehutch** [comment]
rejectPaths only works for paths that are within a classpath element's hierarchy, not above the element in the directory tree.

You can reject individual classpath elements based on the path of the classpath element itself (but I can't remember what I called this, and I'm boarding a plane right now). 

(It's possible some of this reject/accept logic needs to be improved/fixed, it wasn't tested super extensively...)

It's also possible we need to ignore the vfs-expanded directory in WildFly, or the jar version, if it is always true that the jar is expanded at runtime. I don't know anything about WildFly though, so I would need a PR for that.

**Comment by mlntdrv** [comment]
Thank you for your quick answer.
> You can reject individual classpath elements based on the path of the classpath element itself (but I can't remember what I called this, and I'm boarding a plane right now).
> 
`#rejectClasspathElementsContainingResourcePath` I suppose then?
> It's also possible we need to ignore the vfs-expanded directory in WildFly, or the jar version, if it is always true that the jar is expanded at runtime. I don't know anything about WildFly though, so I would need a PR for that.

Sorry, I don't know anything about ClassGraph itself and thus am unable to publish an adequate PR.

**Comment by mlntdrv** [comment]
Alright!
```java
.rejectClasspathElementsContainingResourcePath("*WEB-INF*")
```
worked for ignoring
```C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-dae9b43971d6e39a/WEB-INF/lib/commons-logging-1.2.jar```
Thank you for the hints, Luke.
