### ISSUE TITLE
#rejectClasses usage for module-info.class

### ISSUE THREAD

**Issue by mlntdrv** [classgraph/classgraph#872]
I have scanned for duplicates and I get this for module-info.class:

> module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/azure-core-1.45.1.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/azure-core-http-netty-1.13.11.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/azure-json-1.1.0.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/azure-storage-blob-12.16.0.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/azure-storage-blob-nio-12.0.0-beta.18.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/azure-storage-common-12.15.1.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/azure-storage-internal-avro-12.2.1.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/classgraph-4.8.174.jar!/META-INF/versions/9/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/commons-compress-1.26.1.jar!/META-INF/versions/9/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/commons-io-2.15.1.jar!/META-INF/versions/9/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/commons-lang3-3.14.0.jar!/META-INF/versions/9/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/commons-text-1.12.0.jar!/META-INF/versions/9/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/jackson-annotations-2.12.7.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/jackson-core-2.12.7.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/jackson-databind-2.12.7.1.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/jackson-dataformat-xml-2.12.7.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/jackson-dataformat-yaml-2.12.7.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/jackson-datatype-jsr310-2.12.7.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/temp/temp9d8f833605807052/content-17ab0278f7c19ac/WEB-INF/lib/junit-vintage-engine-5.8.2.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/azure-core-1.45.1.jar-fc672d8fc403ba14/azure-core-1.45.1.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/azure-core-http-netty-1.13.11.jar-921a386228cff928/azure-core-http-netty-1.13.11.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/azure-json-1.1.0.jar-4ca936350ba6073c/azure-json-1.1.0.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/azure-storage-blob-12.16.0.jar-b7748711c716dcc4/azure-storage-blob-12.16.0.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/azure-storage-blob-nio-12.0.0-beta.18.jar-13b4cc6732831571/azure-storage-blob-nio-12.0.0-beta.18.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/azure-storage-common-12.15.1.jar-c624fbd5e6b92f81/azure-storage-common-12.15.1.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/azure-storage-internal-avro-12.2.1.jar-981c1dcc88c2859f/azure-storage-internal-avro-12.2.1.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/classgraph-4.8.174.jar-f5c99a1cef969b43/classgraph-4.8.174.jar!/META-INF/versions/9/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/commons-compress-1.26.1.jar-ee479294777c30a0/commons-compress-1.26.1.jar!/META-INF/versions/9/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/commons-io-2.15.1.jar-d70f981136d89c59/commons-io-2.15.1.jar!/META-INF/versions/9/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/commons-lang3-3.14.0.jar-5abb656db88af3af/commons-lang3-3.14.0.jar!/META-INF/versions/9/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/commons-text-1.12.0.jar-be1727b279f52701/commons-text-1.12.0.jar!/META-INF/versions/9/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/jackson-annotations-2.12.7.jar-e1e144ebd41f5682/jackson-annotations-2.12.7.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/jackson-core-2.12.7.jar-3c166e76f745e77b/jackson-core-2.12.7.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/jackson-databind-2.12.7.1.jar-fb3c7f967fb07592/jackson-databind-2.12.7.1.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/jackson-dataformat-xml-2.12.7.jar-2b909c6973d2fcfc/jackson-dataformat-xml-2.12.7.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/jackson-dataformat-yaml-2.12.7.jar-3f79ab28a755350f/jackson-dataformat-yaml-2.12.7.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/jackson-datatype-jsr310-2.12.7.jar-5c7dca4ff5515f2e/jackson-datatype-jsr310-2.12.7.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/standalone/tmp/vfs/deployment/deployment9f4926ddfb92a2ee/junit-vintage-engine-5.8.2.jar-cfd3036c0b6135d0/junit-vintage-engine-5.8.2.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/javax/activation/api/main/jakarta.activation-1.2.2.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/javax/json/api/main/jakarta.json-api-1.1.6.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/javax/json/bind/api/main/jakarta.json.bind-api-1.0.2.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/org/eclipse/yasson/main/yasson-1.0.11.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/javax/inject/api/main/jakarta.inject-api-1.0.5.jar!/META-INF/versions/9/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/javax/ws/rs/api/main/jboss-jaxrs-api_2.1_spec-2.0.2.Final.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/fasterxml/jackson/core/jackson-annotations/main/jackson-annotations-2.12.7.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/fasterxml/jackson/core/jackson-core/main/jackson-core-2.12.7.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/fasterxml/jackson/core/jackson-databind/main/jackson-databind-2.12.7.1.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/main/jackson-jaxrs-json-provider-2.12.7.jar!/META-INF/versions/11/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/main/jackson-jaxrs-base-2.12.7.jar!/META-INF/versions/11/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/main/jackson-module-jaxb-annotations-2.12.7.jar!/META-INF/versions/11/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/main/jackson-datatype-jdk8-2.12.7.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/main/jackson-datatype-jsr310-2.12.7.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/org/apache/logging/log4j/api/main/log4j-api-2.17.2.jar!/META-INF/versions/9/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/javax/mail/api/main/jakarta.mail-1.6.7.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/sun/xml/bind/main/istack-commons-runtime-3.0.12.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/sun/xml/bind/main/istack-commons-tools-3.0.12.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/sun/xml/bind/main/rngom-2.3.3-b02-jbossorg-2.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/sun/xml/bind/main/relaxng-datatype-2.3.3-b02-jbossorg-2.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/sun/xml/bind/main/codemodel-2.3.3-b02-jbossorg-2.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/sun/xml/bind/main/jaxb-jxc-2.3.3-b02-jbossorg-2.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/sun/xml/bind/main/jaxb-runtime-2.3.3-b02-jbossorg-2.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/sun/xml/bind/main/jaxb-xjc-2.3.3-b02-jbossorg-2.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/sun/xml/bind/main/xsom-2.3.3-b02-jbossorg-2.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/sun/xml/bind/main/txw2-2.3.3-b02-jbossorg-2.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/sun/xml/messaging/saaj/main/saaj-impl-1.5.3.jar!/module-info.class
>   L jar:file:/C:/messdatenplattform-3/devruntime/wildfly/modules/system/layers/base/com/sun/xml/messaging/saaj/main/stax-ex-1.8.3.jar!/module-info.class

I tried to exclude module-info.class with:

```java
.rejectClasses("module-info")
.rejectClasses("module-info.class")
```

however both seem to not work. What am I missing?
v4.8.174

**Comment by lukehutch** [comment]
Hmm, the first one should work, I think, so this is probably a bug... I'm swamped right now though, about to launch a company, so it would be great if you could please track down why this doesn't actually work. I would start by printing the class name obtained from the class metadata when Classfile.java scans a module-info.class (I can't remember if the class name is "module-info" or not).

**Comment by mlntdrv** [comment]
I was able to ignore `module-info.class` like this:
```java
.rejectClasspathElementsContainingResourcePath("module-info*")
```
