### ISSUE TITLE
Cannot find private methods in Kotlin files

### ISSUE THREAD

**Issue by sergio-sastre** [classgraph/classgraph#873]
First of all, thanks for this amazing lib!

I've built another Kotlin library on top of it, in order to scan methods annotated with Compose `@Preview` s.
The scannings return only those methods that are **either internal or public, but not private.**

Here I have a test on that library that confirms it
[`GIVEN private previews THEN those previews are excluded`](https://github.com/sergio-sastre/ComposablePreviewScanner/blob/master/tests/src/test/java/sergio/sastre/composable/preview/scanner/tests/AndroidComposablePreviewScannerTest.kt) (Line 175)

And [here it is the class where I configure ClassGraph](https://github.com/sergio-sastre/ComposablePreviewScanner/blob/master/core/src/main/java/sergio/sastre/composable/preview/scanner/core/scanner/ComposablePreviewScanner.kt). Nothing fancy.
I've also tried with `ClassGraph().enableAllInfo()` without luck.

Although the project where I'm testing it, is configured with JDK 17, since it does not work only for private methods, I doubt I need Narcissus or JVM-Driver according to the docu, right?

Not sure whether it has to do with Kotlin visibility differing from that of Java?
Or maybe I am missing something?

Thanks in advance!

**Comment by lukehutch** [comment]
Hey, you're welcome! 

(I don't know how many Kotlin users there are, and this is completely unrelated, but just as an aside, I have had to work around at least a couple of Kotlin compiler bugs in the past, where the compiler was generating incorrect classfiles :-D )

No, you should be able to see everything private, as long as it is not protected with strong encapsulation (that's what the Narcissus hack is for -- and you don't want to use that if you can avoid it!). Pretty much strong encapsulation only applies to scanning modules. If you're using the traditional classpath, you can see everything.

However, you have to call one of these first:
* `.ignoreClassVisibility()`
* `.ignoreFieldVisibility()`
* `.ignoreMethodVisibility()` (the one you want for your current task).

I know the docs are overwhelming, but: https://github.com/classgraph/classgraph/wiki/ClassGraph-Constructor-API

That should work for you -- if not, there might be a bug somewhere...

**Comment by sergio-sastre** [comment]
Thanks for the info!
It actually works, and seems that I have a problem in my code.

I'll close the issue :)
