### ISSUE TITLE
Different behaviors on JDK 21 and JDK 8

### ISSUE THREAD

**Issue by PARADOXST** [classgraph/classgraph#875]
Hi there,

I am trying switch from `reflections` library which is no longer under maintenance to classgraph in https://github.com/apache/kafka/. (See my pr here https://github.com/apache/kafka/pull/16604). I was able to get the related unit tests working on JDK 21 but some are failing on JDK8.

Namely it is that in these two tests ([test1](https://github.com/apache/kafka/blob/738d8cc91e405be9af785d603d0ee279d83bc7d5/connect/runtime/src/test/java/org/apache/kafka/connect/runtime/isolation/PluginScannerTest.java#L119) and [test2](https://github.com/apache/kafka/blob/738d8cc91e405be9af785d603d0ee279d83bc7d5/connect/runtime/src/test/java/org/apache/kafka/connect/runtime/isolation/PluginScannerTest.java#L60)): The class [`test.plugins.SubclassOfClasspathConverter`](https://github.com/apache/kafka/blob/738d8cc91e405be9af785d603d0ee279d83bc7d5/connect/runtime/src/test/resources/test-plugins/subclass-of-classpath/test/plugins/SubclassOfClasspathConverter.java#L27) is missing in the results. (It extends `ByteArrayConverter` which implements `org.apache.kafka.connect.storage.Converter` so it should be detected from the logic [here](https://github.com/apache/kafka/pull/16604/files#diff-fa2e44dfa6d9f24d42ab629db03306d43075f04142d4bf6f2959b90a3dc743a9R120) (It is indeed detected in JDK 21 but not JDK 8).

The result for test `testScanningMixOfValidAndInvalidPlugins` is:

```
Gradle Test Run :connect:runtime:test > Gradle Test Executor 3 > PluginScannerTest > testScanningMixOfValidAndInvalidPlugins(PluginScanner) > "testScanningMixOfValidAndInvalidPlugins(PluginScanner).scanner=org.apache.kafka.connect.runtime.isolation.ReflectionScanner@cae2a97" FAILED
    org.opentest4j.AssertionFailedError: expected: <[test.plugins.ThingTwo, test.plugins.SamplingConfigProvider, test.plugins.SamplingHeaderConverter, test.plugins.ThingOne, test.plugins.SubclassOfClasspathConverter, test.plugins.ServiceLoaderPlugin, test.plugins.VersionMethodThrowsConnector, test.plugins.SamplingConnector, test.plugins.SamplingConverter, test.plugins.CoLocatedPlugin, test.plugins.SubclassOfClasspathOverridePolicy, test.plugins.AliasedStaticField, test.plugins.ReadVersionFromResource, test.plugins.SamplingConfigurable]> but was: <[test.plugins.ThingTwo, test.plugins.SamplingHeaderConverter, test.plugins.SamplingConfigProvider, test.plugins.ThingOne, test.plugins.ServiceLoaderPlugin, test.plugins.VersionMethodThrowsConnector, test.plugins.SamplingConnector, test.plugins.SamplingConverter, test.plugins.CoLocatedPlugin, test.plugins.SubclassOfClasspathOverridePolicy, test.plugins.AliasedStaticField, test.plugins.ReadVersionFromResource, test.plugins.SamplingConfigurable]>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
        at org.apache.kafka.connect.runtime.isolation.PluginScannerTest.testScanningMixOfValidAndInvalidPlugins(PluginScannerTest.java:124)
```

Where the actual result set is only missing `test.plugins.SubclassOfClasspathConverter`.

Here is the test log for `org.apache.kafka.connect.runtime.isolation.PluginScannerTest.testScanningMixOfValidAndInvalidPlugins(PluginScanner)[1]` with `ClassGraph.verbose()` enabled (it a bit large so I compressed it):

[jdk8_res.zip](https://github.com/user-attachments/files/16393525/jdk8_res.zip)

Here is the result of the passing tests on JDK 21 (from [github CI](https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-16690/2/cloudbees-pipeline-explorer/?filter=40), and i upload it here for convenience (you can search for `testScanningMixOfValidAndInvalidPlugins`)

[PR-16690_build-2_filter-40 (1).txt](https://github.com/user-attachments/files/16393638/PR-16690_build-2_filter-40.1.txt)

We'd really want to make this work to proceed with the library switch so appreciate your help!

**Comment by cushon** [comment]
I have an example in https://github.com/classgraph/classgraph/pull/876 that I think demonstrates the same difference between JDK 8 and JDK 11.

@PARADOXST can you try removing `.ignoreParentClassLoaders()`?

**Comment by PARADOXST** [comment]
@cushon Thanks, I have tried removing `.ignoreParentClassLoaders()` but it OOMs. I then tried to update `-Xmx` from 2G to 8G in [gradle.properties](https://github.com/apache/kafka/blob/a07294a732704b5322df6611088d8d33bc7d3048/gradle.properties#L32) but it still OOMs.

**Comment by cushon** [comment]
Ok. The specific test failure works for me with `ignoreParentClassLoaders` removed:

```
JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/ ./gradlew :connect:runtime:test --tests '*testScanningMixOfValidAndInvalidPlugins*'
```

To double-check, have you enabled logging when it OOMs?

**Comment by PARADOXST** [comment]
I now remove the `.enableInterClassDependencies()` and it passes for JDK 8, I am not sure if this would impact the results of JDK 21 so am still testing it out.

Also I am using JDK 8 from [here](https://www.oracle.com/java/technologies/javase/javase8-archive-downloads.html) which seems different from yours above.

**Comment by lukehutch** [comment]
> I have tried removing `.ignoreParentClassLoaders()` but it OOMs.

Huh? Scanning fewer classloaders should take less memory, not more memory. That doesn't seem right.

To at least address this issue, ClassGraph can build a pretty large object graph. Please make sure you are only enabling scanning of the information you actually need, for the packages that you are actually interested in. If you limit the scanning in this way, and it still OOMs, then maybe you found a bug.

> I have an example in #876 that I think demonstrates the same difference between JDK 8 and JDK 11.

Yes, `java.class.path` is manually added to the scan for JDK >= 9, because there is no classloader we can use to obtain the traditional classpath.

**Comment by lukehutch** [comment]
Also, memory usage goes up a lot if you call `.verbose()`.

I put some notes in @cushon's test PR, #876.

Thanks for providing the logs and the testcases, @PARADOXST. However, I will need a minimal testcase if after looking at #876 you still think something is wrong with the scanning here.

**Comment by PARADOXST** [comment]
Thanks [lukehutch](https://github.com/lukehutch) for taking a look! The solution from [cushon](https://github.com/cushon) works for me so I will mark this closed.

**Comment by lukehutch** [comment]
Thanks, but since I didn't fully understand the issue, let me just check -- do you believe there is a bug in ClassGraph?

**Comment by cushon** [comment]
> Thanks, but since I didn't fully understand the issue, let me just check -- do you believe there is a bug in ClassGraph?

I don't think we've seen evidence of a bug in ClassGraph. The difference in behaviour is explained by `java.class.path` being added on JDK >= 9, and I think the OOM was related to `.verbose()`.

Thanks for taking a look, and for the help understanding what we were seeing here!

**Comment by lukehutch** [comment]
Great, thanks for confirming!
