### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "io.github.classgraph.MethodParameterInfo.setScanResult(io.github.classgraph.ScanResult)" because "this.parameterInfo[i]" is null

### ISSUE THREAD

**Issue by inphoenitic** [classgraph/classgraph#883]
I have a veeeery strange NPE in my project related to ClassGraph. The issue is that I receive an NPE from the MethodInfo class right after constructing the new object MethodParameterInfo object.
The environment is JDK 22 (temurin) build on linux, but I had similar issues with the Oracle JDK 22 and also with JDK versions 19 and 21 in the past. I have tested with version 4.8.175 of ClassGraph, as that seems to be the latest available version now.

The relevant part of the stack trace is:

```
   Caused by: java.lang.NullPointerException: Cannot invoke "io.github.classgraph.MethodParameterInfo.setScanResult(io.github.classgra
ph.ScanResult)" because "this.parameterInfo[i]" is null
        at io.github.classgraph.MethodInfo.getParameterInfo(MethodInfo.java:579)
        at io.github.classgraph.MethodInfo.loadParameterClasses(MethodInfo.java:623)
        at io.github.classgraph.MethodInfo.loadClassAndGetMethod(MethodInfo.java:672)
        at com.dawnspill.data.helper.Reflections.lambda$getMethodsAnnotatedWith$3(Reflections.java:117)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
```

What I do is (in various parts of my code, but in this order):
```
     final var scan = new ClassGraph()
                             //.verbose()
                             .enableAllInfo()
                             .ignoreClassVisibility()
                             .ignoreFieldVisibility()
                             .ignoreMethodVisibility()
                             .scan();
[...]
      final var classname = annotationClass.getName();
      final var classList = scan.getClassesWithMethodAnnotation( classname );
      if ( classList.isEmpty() )
         { return Collections.emptyList(); }
      final List<Method> methods = new Vector<>();
      for( final ClassInfo classInfo : classList ) {
         classInfo.getMethodAndConstructorInfo()
                  .filter( mi -> mi.hasAnnotation( classname ) )
                  .forEach( mi -> { methods.add( mi.loadClassAndGetMethod() ); } );
      }
      return methods;
```

I have checked the ClassGraph source code at MethodInfo.java:579 and right before this method call, the instance is just assigned a newly constructed MethodParameterInfo object.

How can that be possible???
:(

**Comment by lukehutch** [comment]
@inphoenitic I agree, that's very strange, and doesn't make sense at all. Can you set a breakpoint on that line and see if you can tell what is going on?

**Comment by inphoenitic** [comment]
Sorry, I have new clues!
I (falsely) assumed, that ClassGraph is thread safe and the call to scan(), that returns the completed scan results - because of the information that you use multiple threads optimized for performance to do the scan.

Actually - after explaining the problem in this ticket - I rechecked my problems and the code and found that in MethodInfo.getParameterInfo you redefine the transient 'parameterInfo' field, but you don't do it in a temporary local variable and assign that at the end of the transaction, but it takes some time in a loop, and during that time another thread can reallocate the same field with an empty array and causing this weird situation.

So my issue was clearly about thread safety. Now I implemented locking where I use the scan results, so it seems to be safe for me.

**Comment by lukehutch** [comment]
Every object reachable from a `ScanResult`, such as `MethodInfo`, is either created before you can access it, or generated single-threaded in the current thread of the caller. So no, that can't be the problem. Are you calling it from two threads? Again please try to set a breakpoint or something to see what is going on.

**Comment by inphoenitic** [comment]
After I create the `ScanResult` object, I use it from multiple threads. I tried to debug this issue, but it is not easy to breakpoint this, because pausing on a breakpoint usually breaks race conditions... However I managed to analyse the situation and I found, that sometimes more threads (sometimes more that two!) are racing for the same information, calling `MethodInfo.getParameterInfo` parallel on the same `MethodInfo` instance.

**Comment by lukehutch** [comment]
Yeah, the API is not threadsafe, and you cannot in general assume that you can call any API in a multithreaded way unless it is declared explicitly threadsafe.

However by convention, methods that start with "get" should probably not have side effects, and these ones do. So I can wrap those parts in a synchronized block.

**Comment by lukehutch** [comment]
@inphoenitic Should be fixed in 4.8.176. Thanks for the report!

**Comment by inphoenitic** [comment]
Thank you for taking care of this!

Maybe you should also consider the Thread Pinning issue of Virtual Threads with synchronized blocks.

**Comment by lukehutch** [comment]
What is the benefit of thread pinning? The main thing that needs to be done here is simply to ensure that side effects happen within synchronized blocks.

**Comment by inphoenitic** [comment]
That is a JDK21+ problem, it has not benefits. Virtual threads in a synchronized block _might_ get pinned to their carrier platform threads and if this happens a few times, all carrier threads _might_ get blocked and thus all virtual threads will wait for a carrier thread forever. :) https://todd.ginsberg.com/post/java/virtual-thread-pinning/
The recommended solution is using locks, but it is known that locks are slow compared to synchronized methods/blocks. If you run into the issue and you own the code, it is easy to fix, but libraries containing synchronized methods are harder to fix. As this is still a JDK preview feature, it is not a serious/general problem at the moment, I just wanted warn you about it for the future...

**Comment by lukehutch** [comment]
These are all blnonblocking

**Comment by lukehutch** [comment]
These are all nonblocking methods, so there is no issue here. Yes, a platform thread has to become unavailable for other work while one of these methods is running. But there is no problem with that when the task is CPU-bound.
